import type { DsaProblemListItem } from '@/lib/cms/types';

export const defaultDsaProblems: DsaProblemListItem[] = [
  // Arrays & Hashing
  {
    id: 'dsa-two-sum',
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'easy',
    category: 'arrays-hashing',
    link: 'https://leetcode.com/problems/two-sum/',
    videoSolution: 'https://www.youtube.com/watch?v=KLlXCFG5TnA',
    tags: ['Array', 'Hash Table'],
    companies: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple'],
    editorial: 'two-sum',
    approach: 'Use a hash map to record seen values and their indices. For each element num, check if target - num exists in the map in O(1) time.',
    hints: ['Can you solve it in a single pass?', 'What data structure gives O(1) lookup?'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    order: 1,
    status: 'published',
  },
  {
    id: 'dsa-contains-duplicate',
    slug: 'contains-duplicate',
    title: 'Contains Duplicate',
    difficulty: 'easy',
    category: 'arrays-hashing',
    link: 'https://leetcode.com/problems/contains-duplicate/',
    videoSolution: 'https://www.youtube.com/watch?v=3OamzN90kPg',
    tags: ['Array', 'Hash Table', 'Sorting'],
    companies: ['Amazon', 'Apple', 'Adobe'],
    editorial: 'contains-duplicate',
    approach: 'Insert items into a hash set. If an element is already present, return true; otherwise return false after full traversal.',
    hints: ['Sets only keep unique elements. Compare set size or early exit.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    order: 2,
    status: 'published',
  },
  {
    id: 'dsa-valid-anagram',
    slug: 'valid-anagram',
    title: 'Valid Anagram',
    difficulty: 'easy',
    category: 'arrays-hashing',
    link: 'https://leetcode.com/problems/valid-anagram/',
    videoSolution: 'https://www.youtube.com/watch?v=9UtInBqnCgA',
    tags: ['Hash Table', 'String', 'Sorting'],
    companies: ['Uber', 'Bloomberg', 'Google'],
    editorial: 'valid-anagram',
    approach: 'Count character frequencies using an integer array of size 26 or a hash map and verify counts match exactly.',
    hints: ['Can you use fixed-size array of 26 integers instead of a map?'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 3,
    status: 'published',
  },
  {
    id: 'dsa-group-anagrams',
    slug: 'group-anagrams',
    title: 'Group Anagrams',
    difficulty: 'medium',
    category: 'arrays-hashing',
    link: 'https://leetcode.com/problems/group-anagrams/',
    videoSolution: 'https://www.youtube.com/watch?v=vzdNOK2oDA4',
    tags: ['Array', 'Hash Table', 'String'],
    companies: ['Amazon', 'Microsoft', 'Meta', 'Salesforce'],
    editorial: 'group-anagrams',
    approach: 'Map sorted string or character count tuple to a list of original words.',
    hints: ['What key can uniquely represent all anagrams of a word?'],
    timeComplexity: 'O(n * k log k)',
    spaceComplexity: 'O(n * k)',
    order: 4,
    status: 'published',
  },
  {
    id: 'dsa-top-k-frequent-elements',
    slug: 'top-k-frequent-elements',
    title: 'Top K Frequent Elements',
    difficulty: 'medium',
    category: 'arrays-hashing',
    link: 'https://leetcode.com/problems/top-k-frequent-elements/',
    videoSolution: 'https://www.youtube.com/watch?v=YPTqKIgVk-k',
    tags: ['Array', 'Hash Table', 'Heap', 'Bucket Sort'],
    companies: ['Amazon', 'Meta', 'Netflix'],
    editorial: 'top-k-frequent-elements',
    approach: 'Count frequencies in a map, then use bucket sort where index represents frequency to achieve O(n) runtime.',
    hints: ['Bucket sort avoids the O(n log k) heap overhead.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    order: 5,
    status: 'published',
  },

  // Two Pointers
  {
    id: 'dsa-valid-palindrome',
    slug: 'valid-palindrome',
    title: 'Valid Palindrome',
    difficulty: 'easy',
    category: 'two-pointers',
    link: 'https://leetcode.com/problems/valid-palindrome/',
    videoSolution: 'https://www.youtube.com/watch?v=jJXJ16kPFWg',
    tags: ['Two Pointers', 'String'],
    companies: ['Meta', 'Microsoft', 'Spotify'],
    editorial: 'valid-palindrome',
    approach: 'Initialize two pointers at opposite ends, skipping non-alphanumeric characters and comparing lowercase equality.',
    hints: ['Skip non-alphanumeric characters while left < right.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 6,
    status: 'published',
  },
  {
    id: 'dsa-3sum',
    slug: '3sum',
    title: '3Sum',
    difficulty: 'medium',
    category: 'two-pointers',
    link: 'https://leetcode.com/problems/3sum/',
    videoSolution: 'https://www.youtube.com/watch?v=jzZsG8n2R9A',
    tags: ['Array', 'Two Pointers', 'Sorting'],
    companies: ['Amazon', 'Meta', 'Apple', 'Google'],
    editorial: '3sum',
    approach: 'Sort the array. Fix the first element with a loop and run two-pointer inward search for the remaining pair, skipping duplicates.',
    hints: ['Sorting first makes duplicate elimination straightforward.'],
    timeComplexity: 'O(n^2)',
    spaceComplexity: 'O(1)',
    order: 7,
    status: 'published',
  },
  {
    id: 'dsa-container-with-most-water',
    slug: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'medium',
    category: 'two-pointers',
    link: 'https://leetcode.com/problems/container-with-most-water/',
    videoSolution: 'https://www.youtube.com/watch?v=UuiTKBwPgAo',
    tags: ['Array', 'Two Pointers', 'Greedy'],
    companies: ['Google', 'Amazon', 'Adobe'],
    editorial: 'container-with-most-water',
    approach: 'Start two pointers at the boundaries. Calculate area and always shift the pointer pointing to the shorter vertical bar inward.',
    hints: ['The shorter bar limits container height. Moving the taller one cannot increase area.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 8,
    status: 'published',
  },

  // Sliding Window
  {
    id: 'dsa-best-time-to-buy-and-sell-stock',
    slug: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'easy',
    category: 'sliding-window',
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    videoSolution: 'https://www.youtube.com/watch?v=1pkOGcDnx5o',
    tags: ['Array', 'Dynamic Programming'],
    companies: ['Amazon', 'Microsoft', 'Apple', 'Goldman Sachs'],
    editorial: 'best-time-to-buy-and-sell-stock',
    approach: 'Track minimum buying price seen so far while computing potential profit at each day price.',
    hints: ['Single pass tracking minimum entry price.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 9,
    status: 'published',
  },
  {
    id: 'dsa-longest-substring-without-repeating-characters',
    slug: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'medium',
    category: 'sliding-window',
    link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    videoSolution: 'https://www.youtube.com/watch?v=wiGpQwVHdE0',
    tags: ['Hash Table', 'String', 'Sliding Window'],
    companies: ['Amazon', 'Bloomberg', 'Meta', 'Google'],
    editorial: 'longest-substring-without-repeating-characters',
    approach: 'Maintain a sliding window [left, right] and a map of character positions. When a duplicate is seen, jump left to max(left, lastSeen + 1).',
    hints: ['Store the most recent index of each character to skip left pointer directly.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(min(m, n))',
    order: 10,
    status: 'published',
  },

  // Stack
  {
    id: 'dsa-valid-parentheses',
    slug: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'easy',
    category: 'stack',
    link: 'https://leetcode.com/problems/valid-parentheses/',
    videoSolution: 'https://www.youtube.com/watch?v=WTzjTskDFMg',
    tags: ['String', 'Stack'],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
    editorial: 'valid-parentheses',
    approach: 'Push expected closing brackets onto stack when seeing opening brackets. For closing brackets, pop and verify equality.',
    hints: ['Check if stack is empty when encountering a closing brace.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    order: 11,
    status: 'published',
  },
  {
    id: 'dsa-daily-temperatures',
    slug: 'daily-temperatures',
    title: 'Daily Temperatures',
    difficulty: 'medium',
    category: 'stack',
    link: 'https://leetcode.com/problems/daily-temperatures/',
    videoSolution: 'https://www.youtube.com/watch?v=cTBiBSnjO3c',
    tags: ['Array', 'Stack', 'Monotonic Stack'],
    companies: ['Meta', 'Amazon', 'Google'],
    editorial: 'daily-temperatures',
    approach: 'Maintain a monotonic decreasing stack of indices. When encountering a warmer day, pop elements and record index differences.',
    hints: ['Monotonic stack allows finding next greater element in linear total time.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    order: 12,
    status: 'published',
  },

  // Binary Search
  {
    id: 'dsa-binary-search',
    slug: 'binary-search',
    title: 'Binary Search',
    difficulty: 'easy',
    category: 'binary-search',
    link: 'https://leetcode.com/problems/binary-search/',
    videoSolution: 'https://www.youtube.com/watch?v=s4DPM8ct1pI',
    tags: ['Array', 'Binary Search'],
    companies: ['Microsoft', 'Apple', 'Google'],
    editorial: 'binary-search',
    approach: 'Maintain left and right bounds. Halve the search space by comparing the middle element with the target.',
    hints: ['Calculate mid as left + (right - left) // 2 to avoid integer overflow.'],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    order: 13,
    status: 'published',
  },
  {
    id: 'dsa-search-in-rotated-sorted-array',
    slug: 'search-in-rotated-sorted-array',
    title: 'Search in Rotated Sorted Array',
    difficulty: 'medium',
    category: 'binary-search',
    link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    videoSolution: 'https://www.youtube.com/watch?v=U8XENwh8Oy8',
    tags: ['Array', 'Binary Search'],
    companies: ['Meta', 'Amazon', 'Microsoft', 'ByteDance'],
    editorial: 'search-in-rotated-sorted-array',
    approach: 'One half is always strictly sorted. Determine which half is sorted and check if target lies within that sorted range.',
    hints: ['Compare nums[mid] with nums[left] to identify which half is normally sorted.'],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    order: 14,
    status: 'published',
  },

  // Linked List
  {
    id: 'dsa-reverse-linked-list',
    slug: 'reverse-linked-list',
    title: 'Reverse Linked List',
    difficulty: 'easy',
    category: 'linked-list',
    link: 'https://leetcode.com/problems/reverse-linked-list/',
    videoSolution: 'https://www.youtube.com/watch?v=G0_I-ZF0S38',
    tags: ['Linked List', 'Recursion'],
    companies: ['Amazon', 'Google', 'Apple', 'Microsoft'],
    editorial: 'reverse-linked-list',
    approach: 'Iterate through nodes, saving next pointer and swinging curr.next back to prev pointer.',
    hints: ['Three pointers: prev, curr, and temp next.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 15,
    status: 'published',
  },
  {
    id: 'dsa-merge-two-sorted-lists',
    slug: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    difficulty: 'easy',
    category: 'linked-list',
    link: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    videoSolution: 'https://www.youtube.com/watch?v=XIdigk956u0',
    tags: ['Linked List', 'Recursion'],
    companies: ['Amazon', 'Meta', 'Microsoft'],
    editorial: 'merge-two-sorted-lists',
    approach: 'Create a dummy head node and append the smaller node of list1 and list2 until one is exhausted.',
    hints: ['Using a dummy pre-head simplifies pointer updates.'],
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(1)',
    order: 16,
    status: 'published',
  },

  // Trees
  {
    id: 'dsa-invert-binary-tree',
    slug: 'invert-binary-tree',
    title: 'Invert Binary Tree',
    difficulty: 'easy',
    category: 'trees',
    link: 'https://leetcode.com/problems/invert-binary-tree/',
    videoSolution: 'https://www.youtube.com/watch?v=OnSn2XEQ4MY',
    tags: ['Tree', 'DFS', 'BFS', 'Binary Tree'],
    companies: ['Google', 'Amazon', 'Meta'],
    editorial: 'invert-binary-tree',
    approach: 'Recursively swap left and right child pointers for every node.',
    hints: ['Base case: null node returns null.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    order: 17,
    status: 'published',
  },
  {
    id: 'dsa-maximum-depth-of-binary-tree',
    slug: 'maximum-depth-of-binary-tree',
    title: 'Maximum Depth of Binary Tree',
    difficulty: 'easy',
    category: 'trees',
    link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    videoSolution: 'https://www.youtube.com/watch?v=hTM38Lr857I',
    tags: ['Tree', 'DFS', 'BFS', 'Binary Tree'],
    companies: ['LinkedIn', 'Amazon', 'Microsoft'],
    editorial: 'maximum-depth-of-binary-tree',
    approach: 'Return 1 + max(depth(left), depth(right)). Can also be solved iteratively via level-order BFS.',
    hints: ['Post-order DFS traversal naturally gives max child height.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    order: 18,
    status: 'published',
  },
  {
    id: 'dsa-lowest-common-ancestor-of-a-binary-search-tree',
    slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    title: 'Lowest Common Ancestor of a BST',
    difficulty: 'medium',
    category: 'trees',
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    videoSolution: 'https://www.youtube.com/watch?v=gs2LMfuOR9k',
    tags: ['Tree', 'DFS', 'BST', 'Binary Tree'],
    companies: ['Amazon', 'Meta', 'Uber'],
    editorial: 'lowest-common-ancestor-of-a-binary-search-tree',
    approach: 'Leverage BST property: if both values are greater than root, go right; if both are smaller, go left; otherwise current node is split point (LCA).',
    hints: ['No need to traverse both subtrees in a BST.'],
    timeComplexity: 'O(h)',
    spaceComplexity: 'O(1)',
    order: 19,
    status: 'published',
  },

  // Graphs
  {
    id: 'dsa-number-of-islands',
    slug: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'medium',
    category: 'graphs',
    link: 'https://leetcode.com/problems/number-of-islands/',
    videoSolution: 'https://www.youtube.com/watch?v=pV2kpPD66nE',
    tags: ['Array', 'DFS', 'BFS', 'Union Find', 'Matrix'],
    companies: ['Amazon', 'Google', 'Microsoft', 'Bloomberg'],
    editorial: 'number-of-islands',
    approach: 'Iterate across the grid. When encountering land "1", increment island count and run BFS/DFS to sink all connected land cells.',
    hints: ['Mutate visited cells to "0" to avoid maintaining an explicit visited set.'],
    timeComplexity: 'O(m * n)',
    spaceComplexity: 'O(m * n)',
    order: 20,
    status: 'published',
  },
  {
    id: 'dsa-clone-graph',
    slug: 'clone-graph',
    title: 'Clone Graph',
    difficulty: 'medium',
    category: 'graphs',
    link: 'https://leetcode.com/problems/clone-graph/',
    videoSolution: 'https://www.youtube.com/watch?v=mQeF6bN8hMk',
    tags: ['Hash Table', 'DFS', 'BFS', 'Graph'],
    companies: ['Meta', 'Amazon', 'Google'],
    editorial: 'clone-graph',
    approach: 'Use a hash map to map original nodes to their cloned copies. Traverse using DFS/BFS to recursively copy edges.',
    hints: ['The map prevents infinite loops in cyclic graphs.'],
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    order: 21,
    status: 'published',
  },

  // Dynamic Programming
  {
    id: 'dsa-climbing-stairs',
    slug: 'climbing-stairs',
    title: 'Climbing Stairs',
    difficulty: 'easy',
    category: 'dynamic-programming',
    link: 'https://leetcode.com/problems/climbing-stairs/',
    videoSolution: 'https://www.youtube.com/watch?v=Y0lT9Fck7qI',
    tags: ['Math', 'Dynamic Programming', 'Memoization'],
    companies: ['Amazon', 'Apple', 'Google', 'Adobe'],
    editorial: 'climbing-stairs',
    approach: 'dp[i] = dp[i-1] + dp[i-2]. Equivalent to Fibonacci sequence. Optimize to O(1) space with two variables.',
    hints: ['To reach step i, you can only come from step i-1 or step i-2.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 22,
    status: 'published',
  },
  {
    id: 'dsa-coin-change',
    slug: 'coin-change',
    title: 'Coin Change',
    difficulty: 'medium',
    category: 'dynamic-programming',
    link: 'https://leetcode.com/problems/coin-change/',
    videoSolution: 'https://www.youtube.com/watch?v=H9bfqozJoqs',
    tags: ['Array', 'Dynamic Programming', 'BFS'],
    companies: ['Amazon', 'Meta', 'Goldman Sachs', 'Microsoft'],
    editorial: 'coin-change',
    approach: 'Bottom-up DP table dp[a] = min(dp[a], 1 + dp[a - coin]) for each coin in coins. Initialize with infinity.',
    hints: ['dp array size is amount + 1. dp[0] = 0.'],
    timeComplexity: 'O(amount * coins.length)',
    spaceComplexity: 'O(amount)',
    order: 23,
    status: 'published',
  },

  // Intervals
  {
    id: 'dsa-merge-intervals',
    slug: 'merge-intervals',
    title: 'Merge Intervals',
    difficulty: 'medium',
    category: 'intervals',
    link: 'https://leetcode.com/problems/merge-intervals/',
    videoSolution: 'https://www.youtube.com/watch?v=44H3cEC2fFM',
    tags: ['Array', 'Sorting'],
    companies: ['Google', 'Meta', 'Amazon', 'Microsoft'],
    editorial: 'merge-intervals',
    approach: 'Sort intervals by start timestamp. Merge interval with previous if current.start <= prev.end; otherwise push new interval.',
    hints: ['Sort by start time first.'],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    order: 24,
    status: 'published',
  },

  // Math & Bit Manipulation
  {
    id: 'dsa-single-number',
    slug: 'single-number',
    title: 'Single Number',
    difficulty: 'easy',
    category: 'math-bit-manipulation',
    link: 'https://leetcode.com/problems/single-number/',
    videoSolution: 'https://www.youtube.com/watch?v=qMPX1AOa83k',
    tags: ['Array', 'Bit Manipulation'],
    companies: ['Amazon', 'Google', 'Microsoft'],
    editorial: 'single-number',
    approach: 'XOR all numbers together. Since a ^ a = 0 and a ^ 0 = a, duplicate pairs cancel out, leaving the single unique number.',
    hints: ['XOR operation is commutative and associative.'],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    order: 25,
    status: 'published',
  },
];
