export interface DsaProblem {
  id: number;
  title: string;
  difficulty: 'easy' | 'medium' | 'hard';
  link: string;
  tags: string[];
  companies: string[];
}

export interface DsaTopic {
  id: string;
  title: string;
  description: string;
  icon: string;
  problems: DsaProblem[];
}

export const dsaTopics: DsaTopic[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. ARRAYS & HASHING
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'arrays-hashing',
    title: 'Arrays & Hashing',
    description:
      'Foundation of DSA — master array traversals, hash maps, frequency counting, and prefix techniques.',
    icon: 'grid-3x3',
    problems: [
      {
        id: 1,
        title: 'Two Sum',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/two-sum/',
        tags: ['array', 'hash-map'],
        companies: ['Google', 'Amazon', 'Microsoft', 'Meta', 'Apple'],
      },
      {
        id: 2,
        title: 'Contains Duplicate',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/contains-duplicate/',
        tags: ['array', 'hash-set'],
        companies: ['Amazon', 'Apple', 'Adobe'],
      },
      {
        id: 3,
        title: 'Valid Anagram',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/valid-anagram/',
        tags: ['string', 'hash-map', 'sorting'],
        companies: ['Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 4,
        title: 'Group Anagrams',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/group-anagrams/',
        tags: ['string', 'hash-map', 'sorting'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 5,
        title: 'Top K Frequent Elements',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/top-k-frequent-elements/',
        tags: ['array', 'hash-map', 'heap', 'bucket-sort'],
        companies: ['Amazon', 'Meta', 'Google', 'Apple'],
      },
      {
        id: 6,
        title: 'Product of Array Except Self',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/product-of-array-except-self/',
        tags: ['array', 'prefix-sum'],
        companies: ['Amazon', 'Meta', 'Apple', 'Microsoft', 'Google'],
      },
      {
        id: 7,
        title: 'Longest Consecutive Sequence',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-consecutive-sequence/',
        tags: ['array', 'hash-set', 'union-find'],
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 8,
        title: 'Encode and Decode Strings',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/encode-and-decode-strings/',
        tags: ['string', 'design'],
        companies: ['Google', 'Meta', 'Apple'],
      },
      {
        id: 9,
        title: 'Move Zeroes',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/move-zeroes/',
        tags: ['array', 'two-pointers'],
        companies: ['Meta', 'Amazon', 'Apple', 'Bloomberg'],
      },
      {
        id: 10,
        title: 'Majority Element',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/majority-element/',
        tags: ['array', 'hash-map', 'sorting', 'divide-and-conquer'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 11,
        title: 'Sort Colors',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/sort-colors/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Microsoft', 'Amazon', 'Meta', 'Google'],
      },
      {
        id: 12,
        title: 'Next Permutation',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/next-permutation/',
        tags: ['array', 'two-pointers'],
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 13,
        title: 'Maximum Subarray',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/maximum-subarray/',
        tags: ['array', 'dynamic-programming', 'divide-and-conquer'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Apple', 'Meta'],
      },
      {
        id: 14,
        title: 'Best Time to Buy and Sell Stock II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/',
        tags: ['array', 'greedy', 'dynamic-programming'],
        companies: ['Amazon', 'Goldman Sachs', 'Microsoft'],
      },
      {
        id: 15,
        title: 'Subarray Sum Equals K',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/subarray-sum-equals-k/',
        tags: ['array', 'hash-map', 'prefix-sum'],
        companies: ['Meta', 'Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 16,
        title: 'Set Matrix Zeroes',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/set-matrix-zeroes/',
        tags: ['array', 'matrix', 'hash-set'],
        companies: ['Amazon', 'Microsoft', 'Meta'],
      },
      {
        id: 17,
        title: 'Spiral Matrix',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/spiral-matrix/',
        tags: ['array', 'matrix', 'simulation'],
        companies: ['Amazon', 'Microsoft', 'Apple', 'Google'],
      },
      {
        id: 18,
        title: 'Rotate Image',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/rotate-image/',
        tags: ['array', 'matrix', 'math'],
        companies: ['Amazon', 'Microsoft', 'Apple', 'Google'],
      },
      {
        id: 19,
        title: 'Pascal\'s Triangle',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/pascals-triangle/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 20,
        title: 'Find All Duplicates in an Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-all-duplicates-in-an-array/',
        tags: ['array', 'hash-map'],
        companies: ['Amazon', 'Microsoft', 'Apple'],
      },
      {
        id: 21,
        title: 'First Missing Positive',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/first-missing-positive/',
        tags: ['array', 'hash-set', 'cyclic-sort'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 22,
        title: 'Longest Substring Without Repeating Characters',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple'],
      },
      {
        id: 23,
        title: '4Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/4sum/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 24,
        title: 'Continuous Subarray Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/continuous-subarray-sum/',
        tags: ['array', 'hash-map', 'prefix-sum', 'math'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 25,
        title: 'Range Sum Query - Immutable',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/range-sum-query-immutable/',
        tags: ['array', 'prefix-sum', 'design'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 26,
        title: 'Maximum Product Subarray',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/maximum-product-subarray/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'LinkedIn'],
      },
      {
        id: 27,
        title: 'Find the Duplicate Number',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-the-duplicate-number/',
        tags: ['array', 'two-pointers', 'binary-search'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 28,
        title: 'Brick Wall',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/brick-wall/',
        tags: ['array', 'hash-map'],
        companies: ['Meta', 'Bloomberg'],
      },
      {
        id: 29,
        title: 'Replace Elements with Greatest Element on Right Side',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/',
        tags: ['array'],
        companies: ['Amazon'],
      },
      {
        id: 30,
        title: 'Valid Sudoku',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/valid-sudoku/',
        tags: ['array', 'hash-set', 'matrix'],
        companies: ['Amazon', 'Apple', 'Microsoft', 'Uber'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. TWO POINTERS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'two-pointers',
    title: 'Two Pointers',
    description:
      'Efficiently solve problems using two converging or diverging pointers — eliminates unnecessary nested loops.',
    icon: 'arrow-left-right',
    problems: [
      {
        id: 31,
        title: 'Valid Palindrome',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/valid-palindrome/',
        tags: ['string', 'two-pointers'],
        companies: ['Meta', 'Microsoft', 'Amazon'],
      },
      {
        id: 32,
        title: 'Two Sum II - Input Array Is Sorted',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
        tags: ['array', 'two-pointers', 'binary-search'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 33,
        title: '3Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/3sum/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 34,
        title: 'Container With Most Water',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/container-with-most-water/',
        tags: ['array', 'two-pointers', 'greedy'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Goldman Sachs'],
      },
      {
        id: 35,
        title: 'Trapping Rain Water',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/trapping-rain-water/',
        tags: ['array', 'two-pointers', 'stack', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Goldman Sachs', 'Apple'],
      },
      {
        id: 36,
        title: 'Remove Duplicates from Sorted Array',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
        tags: ['array', 'two-pointers'],
        companies: ['Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 37,
        title: 'Remove Element',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/remove-element/',
        tags: ['array', 'two-pointers'],
        companies: ['Amazon', 'Microsoft'],
      },
      {
        id: 38,
        title: 'Boats to Save People',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/boats-to-save-people/',
        tags: ['array', 'two-pointers', 'greedy', 'sorting'],
        companies: ['Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 39,
        title: 'Sort Colors',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/sort-colors/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Microsoft', 'Amazon', 'Meta', 'Google'],
      },
      {
        id: 40,
        title: 'Squares of a Sorted Array',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/squares-of-a-sorted-array/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 41,
        title: 'Merge Sorted Array',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/merge-sorted-array/',
        tags: ['array', 'two-pointers', 'sorting'],
        companies: ['Meta', 'Amazon', 'Microsoft', 'Apple'],
      },
      {
        id: 42,
        title: 'Longest Palindromic Substring',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-palindromic-substring/',
        tags: ['string', 'two-pointers', 'dynamic-programming'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
      },
      {
        id: 43,
        title: 'Palindrome Linked List',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/palindrome-linked-list/',
        tags: ['linked-list', 'two-pointers', 'stack'],
        companies: ['Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 44,
        title: 'String Compression',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/string-compression/',
        tags: ['string', 'two-pointers'],
        companies: ['Meta', 'Goldman Sachs', 'Apple'],
      },
      {
        id: 45,
        title: 'Partition Labels',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/partition-labels/',
        tags: ['string', 'two-pointers', 'greedy', 'hash-map'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. SLIDING WINDOW
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'sliding-window',
    title: 'Sliding Window',
    description:
      'Maintain a dynamic window over data to solve substring and subarray problems in linear time.',
    icon: 'panel-right-open',
    problems: [
      {
        id: 46,
        title: 'Best Time to Buy and Sell Stock',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        tags: ['array', 'sliding-window', 'dynamic-programming'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 47,
        title: 'Longest Substring Without Repeating Characters',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple'],
      },
      {
        id: 48,
        title: 'Longest Repeating Character Replacement',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 49,
        title: 'Permutation in String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/permutation-in-string/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Microsoft', 'Amazon', 'Google'],
      },
      {
        id: 50,
        title: 'Minimum Window Substring',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/minimum-window-substring/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple', 'Uber'],
      },
      {
        id: 51,
        title: 'Sliding Window Maximum',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/sliding-window-maximum/',
        tags: ['array', 'sliding-window', 'deque', 'monotonic-queue'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 52,
        title: 'Find All Anagrams in a String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 53,
        title: 'Maximum Average Subarray I',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/maximum-average-subarray-i/',
        tags: ['array', 'sliding-window'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 54,
        title: 'Minimum Size Subarray Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
        tags: ['array', 'sliding-window', 'binary-search', 'prefix-sum'],
        companies: ['Meta', 'Amazon', 'Goldman Sachs'],
      },
      {
        id: 55,
        title: 'Fruit Into Baskets',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/fruit-into-baskets/',
        tags: ['array', 'hash-map', 'sliding-window'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 56,
        title: 'Substring with Concatenation of All Words',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/',
        tags: ['string', 'hash-map', 'sliding-window'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 57,
        title: 'Max Consecutive Ones III',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/max-consecutive-ones-iii/',
        tags: ['array', 'sliding-window', 'binary-search', 'prefix-sum'],
        companies: ['Google', 'Meta', 'Microsoft'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. STACK
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'stack',
    title: 'Stack',
    description:
      'Last-in-first-out data structure — essential for parsing expressions, monotonic patterns, and backtracking.',
    icon: 'layers',
    problems: [
      {
        id: 58,
        title: 'Valid Parentheses',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/valid-parentheses/',
        tags: ['string', 'stack'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Bloomberg'],
      },
      {
        id: 59,
        title: 'Min Stack',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/min-stack/',
        tags: ['stack', 'design'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Bloomberg'],
      },
      {
        id: 60,
        title: 'Evaluate Reverse Polish Notation',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
        tags: ['stack', 'math'],
        companies: ['Amazon', 'Google', 'Microsoft', 'LinkedIn'],
      },
      {
        id: 61,
        title: 'Generate Parentheses',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/generate-parentheses/',
        tags: ['string', 'stack', 'backtracking'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 62,
        title: 'Daily Temperatures',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/daily-temperatures/',
        tags: ['array', 'stack', 'monotonic-stack'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 63,
        title: 'Car Fleet',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/car-fleet/',
        tags: ['array', 'stack', 'sorting', 'monotonic-stack'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 64,
        title: 'Largest Rectangle in Histogram',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        tags: ['array', 'stack', 'monotonic-stack'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 65,
        title: 'Next Greater Element I',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/next-greater-element-i/',
        tags: ['array', 'stack', 'hash-map', 'monotonic-stack'],
        companies: ['Amazon', 'Bloomberg'],
      },
      {
        id: 66,
        title: 'Simplify Path',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/simplify-path/',
        tags: ['string', 'stack'],
        companies: ['Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 67,
        title: 'Asteroid Collision',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/asteroid-collision/',
        tags: ['array', 'stack', 'simulation'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 68,
        title: 'Decode String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/decode-string/',
        tags: ['string', 'stack', 'recursion'],
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 69,
        title: 'Online Stock Span',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/online-stock-span/',
        tags: ['stack', 'monotonic-stack', 'design'],
        companies: ['Amazon', 'Bloomberg'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. BINARY SEARCH
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'binary-search',
    title: 'Binary Search',
    description:
      'Divide-and-conquer search over sorted or monotonic spaces — reduces O(n) to O(log n).',
    icon: 'search',
    problems: [
      {
        id: 70,
        title: 'Binary Search',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/binary-search/',
        tags: ['array', 'binary-search'],
        companies: ['Amazon', 'Microsoft', 'Google'],
      },
      {
        id: 71,
        title: 'Search a 2D Matrix',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/search-a-2d-matrix/',
        tags: ['array', 'binary-search', 'matrix'],
        companies: ['Amazon', 'Microsoft', 'Meta'],
      },
      {
        id: 72,
        title: 'Koko Eating Bananas',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/koko-eating-bananas/',
        tags: ['array', 'binary-search'],
        companies: ['Google', 'Amazon', 'Meta'],
      },
      {
        id: 73,
        title: 'Find Minimum in Rotated Sorted Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        tags: ['array', 'binary-search'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
      },
      {
        id: 74,
        title: 'Search in Rotated Sorted Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        tags: ['array', 'binary-search'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 75,
        title: 'Time Based Key-Value Store',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/time-based-key-value-store/',
        tags: ['hash-map', 'binary-search', 'design'],
        companies: ['Google', 'Amazon', 'Netflix'],
      },
      {
        id: 76,
        title: 'Median of Two Sorted Arrays',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
        tags: ['array', 'binary-search', 'divide-and-conquer'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta', 'Apple', 'Goldman Sachs'],
      },
      {
        id: 77,
        title: 'Find Peak Element',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-peak-element/',
        tags: ['array', 'binary-search'],
        companies: ['Meta', 'Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 78,
        title: 'Search in Rotated Sorted Array II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/',
        tags: ['array', 'binary-search'],
        companies: ['Amazon', 'Microsoft', 'Meta'],
      },
      {
        id: 79,
        title: 'Find First and Last Position of Element in Sorted Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
        tags: ['array', 'binary-search'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 80,
        title: 'Capacity To Ship Packages Within D Days',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/',
        tags: ['array', 'binary-search', 'greedy'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 81,
        title: 'Split Array Largest Sum',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/split-array-largest-sum/',
        tags: ['array', 'binary-search', 'dynamic-programming', 'greedy'],
        companies: ['Google', 'Amazon', 'Meta'],
      },
      {
        id: 82,
        title: 'Aggressive Cows (Magnetic Balls)',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/magnetic-force-between-two-balls/',
        tags: ['array', 'binary-search', 'sorting'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 83,
        title: 'Allocate Books',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/split-array-largest-sum/',
        tags: ['array', 'binary-search', 'greedy'],
        companies: ['Google', 'Amazon', 'Microsoft'],
      },
      {
        id: 84,
        title: 'Single Element in a Sorted Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/single-element-in-a-sorted-array/',
        tags: ['array', 'binary-search'],
        companies: ['Amazon', 'Microsoft', 'Google'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. LINKED LIST
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'linked-list',
    title: 'Linked List',
    description:
      'Dynamic linear data structure — practice pointer manipulation, reversal, and cycle detection.',
    icon: 'link',
    problems: [
      {
        id: 85,
        title: 'Reverse Linked List',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/reverse-linked-list/',
        tags: ['linked-list', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple'],
      },
      {
        id: 86,
        title: 'Merge Two Sorted Lists',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/merge-two-sorted-lists/',
        tags: ['linked-list', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Apple'],
      },
      {
        id: 87,
        title: 'Linked List Cycle',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/linked-list-cycle/',
        tags: ['linked-list', 'two-pointers', 'hash-set'],
        companies: ['Amazon', 'Microsoft', 'Meta', 'Apple'],
      },
      {
        id: 88,
        title: 'Reorder List',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/reorder-list/',
        tags: ['linked-list', 'two-pointers', 'stack'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 89,
        title: 'Remove Nth Node From End of List',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        tags: ['linked-list', 'two-pointers'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 90,
        title: 'Copy List with Random Pointer',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
        tags: ['linked-list', 'hash-map'],
        companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
      },
      {
        id: 91,
        title: 'Add Two Numbers',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/add-two-numbers/',
        tags: ['linked-list', 'math', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple'],
      },
      {
        id: 92,
        title: 'Find the Duplicate Number',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/find-the-duplicate-number/',
        tags: ['linked-list', 'two-pointers', 'binary-search'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 93,
        title: 'LRU Cache',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/lru-cache/',
        tags: ['linked-list', 'hash-map', 'design'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple', 'Netflix'],
      },
      {
        id: 94,
        title: 'Merge K Sorted Lists',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        tags: ['linked-list', 'heap', 'divide-and-conquer'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 95,
        title: 'Reverse Nodes in k-Group',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
        tags: ['linked-list', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Meta', 'Google'],
      },
      {
        id: 96,
        title: 'Middle of the Linked List',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/middle-of-the-linked-list/',
        tags: ['linked-list', 'two-pointers'],
        companies: ['Amazon', 'Microsoft', 'Google'],
      },
      {
        id: 97,
        title: 'Intersection of Two Linked Lists',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
        tags: ['linked-list', 'two-pointers', 'hash-set'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 98,
        title: 'Sort List',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/sort-list/',
        tags: ['linked-list', 'two-pointers', 'divide-and-conquer', 'sorting', 'merge-sort'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 99,
        title: 'Flatten a Multilevel Doubly Linked List',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/',
        tags: ['linked-list', 'dfs', 'stack'],
        companies: ['Meta', 'Microsoft', 'Amazon'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 7. TREES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'trees',
    title: 'Trees',
    description:
      'Hierarchical data structures — binary trees, BSTs, and traversal techniques are interview staples.',
    icon: 'git-branch',
    problems: [
      {
        id: 100,
        title: 'Invert Binary Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/invert-binary-tree/',
        tags: ['tree', 'bfs', 'dfs', 'recursion'],
        companies: ['Google', 'Amazon', 'Meta'],
      },
      {
        id: 101,
        title: 'Maximum Depth of Binary Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        tags: ['tree', 'dfs', 'bfs', 'recursion'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 102,
        title: 'Diameter of Binary Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/diameter-of-binary-tree/',
        tags: ['tree', 'dfs', 'recursion'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 103,
        title: 'Balanced Binary Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/balanced-binary-tree/',
        tags: ['tree', 'dfs', 'recursion'],
        companies: ['Amazon', 'Google', 'Bloomberg'],
      },
      {
        id: 104,
        title: 'Same Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/same-tree/',
        tags: ['tree', 'dfs', 'bfs', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google'],
      },
      {
        id: 105,
        title: 'Subtree of Another Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/subtree-of-another-tree/',
        tags: ['tree', 'dfs', 'string-matching', 'hash'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 106,
        title: 'Lowest Common Ancestor of a Binary Search Tree',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
        tags: ['tree', 'bst', 'dfs'],
        companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
      },
      {
        id: 107,
        title: 'Binary Tree Level Order Traversal',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        tags: ['tree', 'bfs'],
        companies: ['Amazon', 'Meta', 'Microsoft', 'Google', 'Apple'],
      },
      {
        id: 108,
        title: 'Binary Tree Right Side View',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/binary-tree-right-side-view/',
        tags: ['tree', 'bfs', 'dfs'],
        companies: ['Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 109,
        title: 'Count Good Nodes in Binary Tree',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/',
        tags: ['tree', 'dfs', 'bfs'],
        companies: ['Amazon', 'Microsoft'],
      },
      {
        id: 110,
        title: 'Validate Binary Search Tree',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/validate-binary-search-tree/',
        tags: ['tree', 'bst', 'dfs', 'recursion'],
        companies: ['Amazon', 'Meta', 'Microsoft', 'Google', 'Apple'],
      },
      {
        id: 111,
        title: 'Kth Smallest Element in a BST',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        tags: ['tree', 'bst', 'dfs', 'inorder'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 112,
        title: 'Construct Binary Tree from Preorder and Inorder Traversal',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
        tags: ['tree', 'divide-and-conquer', 'hash-map', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
      },
      {
        id: 113,
        title: 'Binary Tree Maximum Path Sum',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
        tags: ['tree', 'dfs', 'dynamic-programming'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 114,
        title: 'Serialize and Deserialize Binary Tree',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
        tags: ['tree', 'bfs', 'dfs', 'design'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 115,
        title: 'Lowest Common Ancestor of a Binary Tree',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
        tags: ['tree', 'dfs', 'recursion'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 116,
        title: 'Binary Tree Zigzag Level Order Traversal',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/',
        tags: ['tree', 'bfs'],
        companies: ['Amazon', 'Meta', 'Microsoft', 'Google'],
      },
      {
        id: 117,
        title: 'Path Sum II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/path-sum-ii/',
        tags: ['tree', 'dfs', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 118,
        title: 'Flatten Binary Tree to Linked List',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/',
        tags: ['tree', 'dfs', 'stack', 'linked-list'],
        companies: ['Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 119,
        title: 'Symmetric Tree',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/symmetric-tree/',
        tags: ['tree', 'dfs', 'bfs', 'recursion'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Apple'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8. TRIES
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'tries',
    title: 'Tries',
    description:
      'Prefix tree data structure — optimized for string searching, autocomplete, and word games.',
    icon: 'text-search',
    problems: [
      {
        id: 120,
        title: 'Implement Trie (Prefix Tree)',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
        tags: ['trie', 'string', 'design'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 121,
        title: 'Design Add and Search Words Data Structure',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
        tags: ['trie', 'string', 'dfs', 'design'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 122,
        title: 'Word Search II',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/word-search-ii/',
        tags: ['trie', 'backtracking', 'matrix'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta', 'Apple'],
      },
      {
        id: 123,
        title: 'Replace Words',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/replace-words/',
        tags: ['trie', 'string', 'hash-set'],
        companies: ['Uber', 'Amazon'],
      },
      {
        id: 124,
        title: 'Search Suggestions System',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/search-suggestions-system/',
        tags: ['trie', 'string', 'sorting', 'binary-search'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 9. HEAP / PRIORITY QUEUE
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'heap-priority-queue',
    title: 'Heap / Priority Queue',
    description:
      'Efficiently find min/max elements — critical for scheduling, streaming data, and top-K problems.',
    icon: 'bar-chart-3',
    problems: [
      {
        id: 125,
        title: 'Kth Largest Element in a Stream',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/',
        tags: ['heap', 'design', 'bst'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 126,
        title: 'Last Stone Weight',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/last-stone-weight/',
        tags: ['array', 'heap'],
        companies: ['Amazon', 'Google'],
      },
      {
        id: 127,
        title: 'K Closest Points to Origin',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/k-closest-points-to-origin/',
        tags: ['array', 'heap', 'sorting', 'divide-and-conquer'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 128,
        title: 'Kth Largest Element in an Array',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        tags: ['array', 'heap', 'divide-and-conquer', 'sorting', 'quickselect'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 129,
        title: 'Task Scheduler',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/task-scheduler/',
        tags: ['array', 'heap', 'greedy', 'hash-map'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 130,
        title: 'Design Twitter',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/design-twitter/',
        tags: ['heap', 'hash-map', 'linked-list', 'design'],
        companies: ['Amazon', 'Twitter'],
      },
      {
        id: 131,
        title: 'Find Median from Data Stream',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/find-median-from-data-stream/',
        tags: ['heap', 'design', 'sorting'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple'],
      },
      {
        id: 132,
        title: 'Merge K Sorted Lists',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        tags: ['linked-list', 'heap', 'divide-and-conquer'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 133,
        title: 'Top K Frequent Words',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/top-k-frequent-words/',
        tags: ['string', 'heap', 'hash-map', 'sorting', 'trie'],
        companies: ['Amazon', 'Google', 'Meta', 'Bloomberg'],
      },
      {
        id: 134,
        title: 'Reorganize String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/reorganize-string/',
        tags: ['string', 'heap', 'greedy', 'hash-map'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 10. BACKTRACKING
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'backtracking',
    title: 'Backtracking',
    description:
      'Explore all possibilities through recursive choice-making — fundamental for combinatorial problems.',
    icon: 'undo-2',
    problems: [
      {
        id: 135,
        title: 'Subsets',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/subsets/',
        tags: ['array', 'backtracking', 'bit-manipulation'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 136,
        title: 'Combination Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/combination-sum/',
        tags: ['array', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 137,
        title: 'Permutations',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/permutations/',
        tags: ['array', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 138,
        title: 'Subsets II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/subsets-ii/',
        tags: ['array', 'backtracking', 'bit-manipulation'],
        companies: ['Amazon', 'Meta', 'Google'],
      },
      {
        id: 139,
        title: 'Combination Sum II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/combination-sum-ii/',
        tags: ['array', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Google'],
      },
      {
        id: 140,
        title: 'Word Search',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/word-search/',
        tags: ['array', 'backtracking', 'matrix'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 141,
        title: 'Palindrome Partitioning',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/palindrome-partitioning/',
        tags: ['string', 'backtracking', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 142,
        title: 'Letter Combinations of a Phone Number',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
        tags: ['string', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 143,
        title: 'N-Queens',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/n-queens/',
        tags: ['array', 'backtracking'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 144,
        title: 'Sudoku Solver',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/sudoku-solver/',
        tags: ['array', 'backtracking', 'matrix'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 145,
        title: 'Permutations II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/permutations-ii/',
        tags: ['array', 'backtracking'],
        companies: ['Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 146,
        title: 'Restore IP Addresses',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/restore-ip-addresses/',
        tags: ['string', 'backtracking'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 11. GRAPHS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'graphs',
    title: 'Graphs',
    description:
      'Model relationships between entities — master BFS, DFS, topological sort, shortest path, and union-find.',
    icon: 'share-2',
    problems: [
      {
        id: 147,
        title: 'Number of Islands',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/number-of-islands/',
        tags: ['graph', 'bfs', 'dfs', 'matrix', 'union-find'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 148,
        title: 'Clone Graph',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/clone-graph/',
        tags: ['graph', 'bfs', 'dfs', 'hash-map'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 149,
        title: 'Max Area of Island',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/max-area-of-island/',
        tags: ['graph', 'bfs', 'dfs', 'matrix', 'union-find'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 150,
        title: 'Pacific Atlantic Water Flow',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
        tags: ['graph', 'bfs', 'dfs', 'matrix'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 151,
        title: 'Surrounded Regions',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/surrounded-regions/',
        tags: ['graph', 'bfs', 'dfs', 'matrix', 'union-find'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 152,
        title: 'Rotting Oranges',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/rotting-oranges/',
        tags: ['graph', 'bfs', 'matrix'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 153,
        title: 'Course Schedule',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/course-schedule/',
        tags: ['graph', 'dfs', 'bfs', 'topological-sort'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 154,
        title: 'Course Schedule II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/course-schedule-ii/',
        tags: ['graph', 'dfs', 'bfs', 'topological-sort'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 155,
        title: 'Graph Valid Tree',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/graph-valid-tree/',
        tags: ['graph', 'dfs', 'bfs', 'union-find'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 156,
        title: 'Number of Connected Components in an Undirected Graph',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
        tags: ['graph', 'dfs', 'bfs', 'union-find'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 157,
        title: 'Redundant Connection',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/redundant-connection/',
        tags: ['graph', 'union-find', 'dfs'],
        companies: ['Amazon', 'Google'],
      },
      {
        id: 158,
        title: 'Word Ladder',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/word-ladder/',
        tags: ['graph', 'bfs', 'string', 'hash-set'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft'],
      },
      {
        id: 159,
        title: 'Cheapest Flights Within K Stops',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
        tags: ['graph', 'bfs', 'dynamic-programming', 'dijkstra', 'bellman-ford'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 160,
        title: 'Network Delay Time',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/network-delay-time/',
        tags: ['graph', 'dijkstra', 'bfs', 'heap'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 161,
        title: 'Swim in Rising Water',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/swim-in-rising-water/',
        tags: ['graph', 'binary-search', 'heap', 'matrix', 'union-find'],
        companies: ['Amazon', 'Google'],
      },
      {
        id: 162,
        title: 'Alien Dictionary',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/alien-dictionary/',
        tags: ['graph', 'topological-sort', 'string'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 163,
        title: 'Accounts Merge',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/accounts-merge/',
        tags: ['graph', 'dfs', 'bfs', 'union-find', 'string'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 164,
        title: 'Is Graph Bipartite?',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/is-graph-bipartite/',
        tags: ['graph', 'dfs', 'bfs', 'union-find'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 165,
        title: 'Minimum Height Trees',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/minimum-height-trees/',
        tags: ['graph', 'bfs', 'topological-sort'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 166,
        title: 'Shortest Path in Binary Matrix',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/',
        tags: ['graph', 'bfs', 'matrix'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 12. DYNAMIC PROGRAMMING
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    description:
      'Break complex problems into overlapping subproblems — the most frequently tested advanced topic.',
    icon: 'brain',
    problems: [
      {
        id: 167,
        title: 'Climbing Stairs',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/climbing-stairs/',
        tags: ['dynamic-programming', 'math', 'memoization'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 168,
        title: 'Min Cost Climbing Stairs',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/min-cost-climbing-stairs/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 169,
        title: 'House Robber',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/house-robber/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 170,
        title: 'House Robber II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/house-robber-ii/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 171,
        title: 'Longest Palindromic Substring',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-palindromic-substring/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
      },
      {
        id: 172,
        title: 'Palindromic Substrings',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/palindromic-substrings/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 173,
        title: 'Decode Ways',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/decode-ways/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 174,
        title: 'Coin Change',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/coin-change/',
        tags: ['array', 'dynamic-programming', 'bfs'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple', 'Goldman Sachs'],
      },
      {
        id: 175,
        title: 'Maximum Product Subarray',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/maximum-product-subarray/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'LinkedIn'],
      },
      {
        id: 176,
        title: 'Word Break',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/word-break/',
        tags: ['string', 'dynamic-programming', 'hash-set', 'trie'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 177,
        title: 'Longest Increasing Subsequence',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-increasing-subsequence/',
        tags: ['array', 'dynamic-programming', 'binary-search'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 178,
        title: 'Partition Equal Subset Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/partition-equal-subset-sum/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Meta', 'Google'],
      },
      {
        id: 179,
        title: 'Unique Paths',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/unique-paths/',
        tags: ['math', 'dynamic-programming', 'combinatorics'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 180,
        title: 'Longest Common Subsequence',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/longest-common-subsequence/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 181,
        title: 'Target Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/target-sum/',
        tags: ['array', 'dynamic-programming', 'backtracking'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 182,
        title: 'Interleaving String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/interleaving-string/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 183,
        title: '0/1 Knapsack Problem',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/ones-and-zeroes/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 184,
        title: 'Edit Distance',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/edit-distance/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 185,
        title: 'Distinct Subsequences',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/distinct-subsequences/',
        tags: ['string', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 186,
        title: 'Burst Balloons',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/burst-balloons/',
        tags: ['array', 'dynamic-programming', 'divide-and-conquer'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 187,
        title: 'Regular Expression Matching',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/regular-expression-matching/',
        tags: ['string', 'dynamic-programming', 'recursion'],
        companies: ['Google', 'Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 188,
        title: 'Longest Increasing Path in a Matrix',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',
        tags: ['dynamic-programming', 'dfs', 'memoization', 'matrix', 'topological-sort'],
        companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
      },
      {
        id: 189,
        title: 'Minimum Path Sum',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/minimum-path-sum/',
        tags: ['array', 'dynamic-programming', 'matrix'],
        companies: ['Amazon', 'Google', 'Goldman Sachs'],
      },
      {
        id: 190,
        title: 'Coin Change II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/coin-change-ii/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 191,
        title: 'Best Time to Buy and Sell Stock with Cooldown',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
        tags: ['array', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Goldman Sachs'],
      },
      {
        id: 192,
        title: 'Maximal Square',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/maximal-square/',
        tags: ['array', 'dynamic-programming', 'matrix'],
        companies: ['Amazon', 'Google', 'Apple', 'Microsoft'],
      },
      {
        id: 193,
        title: 'Jump Game',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/jump-game/',
        tags: ['array', 'dynamic-programming', 'greedy'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 194,
        title: 'Jump Game II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/jump-game-ii/',
        tags: ['array', 'dynamic-programming', 'greedy'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 195,
        title: 'Word Break II',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/word-break-ii/',
        tags: ['string', 'dynamic-programming', 'backtracking', 'memoization'],
        companies: ['Amazon', 'Meta', 'Google', 'Apple'],
      },
      {
        id: 196,
        title: 'Matrix Chain Multiplication',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/',
        tags: ['array', 'dynamic-programming', 'stack'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 13. GREEDY
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'greedy',
    title: 'Greedy',
    description:
      'Make locally optimal choices to find global optima — requires proving greedy choice property.',
    icon: 'zap',
    problems: [
      {
        id: 197,
        title: 'Maximum Subarray',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/maximum-subarray/',
        tags: ['array', 'greedy', 'dynamic-programming', 'divide-and-conquer'],
        companies: ['Amazon', 'Microsoft', 'Google', 'Apple', 'Meta'],
      },
      {
        id: 198,
        title: 'Jump Game',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/jump-game/',
        tags: ['array', 'greedy', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Apple'],
      },
      {
        id: 199,
        title: 'Jump Game II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/jump-game-ii/',
        tags: ['array', 'greedy', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
      },
      {
        id: 200,
        title: 'Gas Station',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/gas-station/',
        tags: ['array', 'greedy'],
        companies: ['Amazon', 'Google', 'Microsoft', 'Bloomberg'],
      },
      {
        id: 201,
        title: 'Hand of Straights',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/hand-of-straights/',
        tags: ['array', 'greedy', 'hash-map', 'sorting'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 202,
        title: 'Merge Triplets to Form Target Triplet',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
        tags: ['array', 'greedy'],
        companies: ['Google'],
      },
      {
        id: 203,
        title: 'Partition Labels',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/partition-labels/',
        tags: ['string', 'greedy', 'hash-map', 'two-pointers'],
        companies: ['Amazon', 'Google', 'Meta'],
      },
      {
        id: 204,
        title: 'Valid Parenthesis String',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/valid-parenthesis-string/',
        tags: ['string', 'greedy', 'stack', 'dynamic-programming'],
        companies: ['Amazon', 'Meta', 'Google'],
      },
      {
        id: 205,
        title: 'Activity Selection / Non-overlapping Intervals',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/non-overlapping-intervals/',
        tags: ['array', 'greedy', 'sorting', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 206,
        title: 'Minimum Number of Arrows to Burst Balloons',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',
        tags: ['array', 'greedy', 'sorting'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 14. INTERVALS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'intervals',
    title: 'Intervals',
    description:
      'Merge, insert, and manage overlapping ranges — common in scheduling and calendar problems.',
    icon: 'git-merge',
    problems: [
      {
        id: 207,
        title: 'Insert Interval',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/insert-interval/',
        tags: ['array', 'intervals'],
        companies: ['Google', 'Meta', 'Amazon', 'Microsoft'],
      },
      {
        id: 208,
        title: 'Merge Intervals',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/merge-intervals/',
        tags: ['array', 'intervals', 'sorting'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple', 'Bloomberg'],
      },
      {
        id: 209,
        title: 'Non-overlapping Intervals',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/non-overlapping-intervals/',
        tags: ['array', 'intervals', 'greedy', 'sorting', 'dynamic-programming'],
        companies: ['Amazon', 'Google', 'Meta', 'Microsoft'],
      },
      {
        id: 210,
        title: 'Meeting Rooms',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/meeting-rooms/',
        tags: ['array', 'intervals', 'sorting'],
        companies: ['Amazon', 'Meta', 'Bloomberg'],
      },
      {
        id: 211,
        title: 'Meeting Rooms II',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/meeting-rooms-ii/',
        tags: ['array', 'intervals', 'sorting', 'heap', 'two-pointers'],
        companies: ['Amazon', 'Meta', 'Google', 'Microsoft', 'Bloomberg'],
      },
      {
        id: 212,
        title: 'Minimum Interval to Include Each Query',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/',
        tags: ['array', 'intervals', 'sorting', 'heap', 'binary-search'],
        companies: ['Google', 'Amazon'],
      },
      {
        id: 213,
        title: 'Interval List Intersections',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/interval-list-intersections/',
        tags: ['array', 'intervals', 'two-pointers'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 214,
        title: 'Employee Free Time',
        difficulty: 'hard',
        link: 'https://leetcode.com/problems/employee-free-time/',
        tags: ['array', 'intervals', 'sorting', 'heap'],
        companies: ['Amazon', 'Google', 'Meta', 'Uber'],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 15. MATH & BIT MANIPULATION
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'math-bit-manipulation',
    title: 'Math & Bit Manipulation',
    description:
      'Low-level operations and mathematical tricks — XOR, bit shifting, and number theory fundamentals.',
    icon: 'calculator',
    problems: [
      {
        id: 215,
        title: 'Single Number',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/single-number/',
        tags: ['array', 'bit-manipulation'],
        companies: ['Amazon', 'Google', 'Apple', 'Microsoft'],
      },
      {
        id: 216,
        title: 'Number of 1 Bits',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/number-of-1-bits/',
        tags: ['bit-manipulation'],
        companies: ['Microsoft', 'Apple', 'Amazon'],
      },
      {
        id: 217,
        title: 'Counting Bits',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/counting-bits/',
        tags: ['dynamic-programming', 'bit-manipulation'],
        companies: ['Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 218,
        title: 'Reverse Bits',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/reverse-bits/',
        tags: ['bit-manipulation', 'divide-and-conquer'],
        companies: ['Apple', 'Amazon'],
      },
      {
        id: 219,
        title: 'Missing Number',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/missing-number/',
        tags: ['array', 'bit-manipulation', 'math', 'hash-set', 'sorting'],
        companies: ['Amazon', 'Microsoft', 'Apple', 'Google'],
      },
      {
        id: 220,
        title: 'Sum of Two Integers',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/sum-of-two-integers/',
        tags: ['math', 'bit-manipulation'],
        companies: ['Meta', 'Amazon', 'Google'],
      },
      {
        id: 221,
        title: 'Reverse Integer',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/reverse-integer/',
        tags: ['math'],
        companies: ['Amazon', 'Microsoft', 'Apple', 'Bloomberg'],
      },
      {
        id: 222,
        title: 'Pow(x, n)',
        difficulty: 'medium',
        link: 'https://leetcode.com/problems/powx-n/',
        tags: ['math', 'recursion', 'binary-search'],
        companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
      },
      {
        id: 223,
        title: 'Happy Number',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/happy-number/',
        tags: ['math', 'hash-set', 'two-pointers'],
        companies: ['Amazon', 'Apple', 'Google'],
      },
      {
        id: 224,
        title: 'Plus One',
        difficulty: 'easy',
        link: 'https://leetcode.com/problems/plus-one/',
        tags: ['array', 'math'],
        companies: ['Google', 'Amazon', 'Microsoft'],
      },
    ],
  },
];
