import { Roadmap } from '@/types/roadmap';

export const aiEngineerRoadmap: Roadmap = {
  slug: 'ai-engineer',
  title: 'AI / ML Engineer',
  description: 'Master machine learning, deep learning, NLP, and AI applications — from Python fundamentals to deploying production ML models.',
  icon: 'Brain',
  accent: '#C7FF3D',
  totalTime: '8-10 months',
  languages: ['Python'],
  relatedRoadmaps: [
    { slug: 'backend-developer', relation: 'shared-topics', description: 'API skills needed for model deployment' },
    { slug: 'devops-engineer', relation: 'shared-topics', description: 'MLOps shares Docker, CI/CD, and cloud concepts' },
    { slug: 'full-stack-developer', relation: 'shared-topics', description: 'Build AI-powered full-stack applications' },
  ],
  stages: [
    {
      id: 'foundations',
      title: 'Python & Math Foundations',
      description: 'Build a strong base in Python programming and the mathematics behind ML.',
      timeEstimate: '5-6 weeks',
      color: 'green',
      topics: [
        {
          id: 'python-for-ml',
          title: 'Python for Data Science',
          description: 'Master Python programming with a focus on data manipulation and scientific computing.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Python fundamentals (variables, loops, functions, OOP)',
            'NumPy for numerical computing',
            'Pandas for data manipulation',
            'Matplotlib and Seaborn for visualization',
            'Jupyter Notebooks workflow',
            'File I/O and working with CSV/JSON',
            'List comprehensions and generators',
            'Virtual environments and pip',
          ],
          resources: [
            { title: 'Python for Data Science - freeCodeCamp', url: 'https://www.youtube.com/watch?v=LHBE6Q9XlzI', type: 'video' },
            { title: 'NumPy & Pandas Tutorial - Keith Galli', url: 'https://www.youtube.com/watch?v=vmEHCJofslg', type: 'video' },
            { title: 'Python Official Tutorial', url: 'https://docs.python.org/3/tutorial/', type: 'docs' },
            { title: 'Kaggle Learn Python', url: 'https://www.kaggle.com/learn/python', type: 'course' },
          ],
          project: {
            title: 'Data Analysis Dashboard',
            description: 'Analyze a real dataset (Kaggle) using Pandas. Clean data, compute statistics, create visualizations, and present findings in a Jupyter notebook.',
          },
        },
        {
          id: 'math-for-ml',
          title: 'Mathematics for ML',
          description: 'Learn the essential math — linear algebra, calculus, probability, and statistics.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Linear algebra: vectors, matrices, dot products, eigenvalues',
            'Calculus: derivatives, partial derivatives, chain rule, gradients',
            'Probability: Bayes theorem, distributions, expected value',
            'Statistics: mean, variance, hypothesis testing, correlation',
            'Optimization: gradient descent intuition',
            'Information theory basics (entropy, cross-entropy)',
          ],
          resources: [
            { title: '3Blue1Brown - Essence of Linear Algebra', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', type: 'video' },
            { title: 'Khan Academy - Statistics & Probability', url: 'https://www.khanacademy.org/math/statistics-probability', type: 'course' },
            { title: 'Mathematics for Machine Learning (Book)', url: 'https://mml-book.github.io/', type: 'article' },
            { title: 'StatQuest - Statistics Fundamentals', url: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9', type: 'video' },
          ],
          project: {
            title: 'Implement Gradient Descent from Scratch',
            description: 'Implement linear regression using gradient descent from scratch in NumPy. Visualize the cost function and optimization path.',
          },
        },
        {
          id: 'data-preprocessing',
          title: 'Data Preprocessing & EDA',
          description: 'Learn to clean, transform, and explore data before feeding it to models.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Handling missing values (imputation strategies)',
            'Feature scaling (normalization, standardization)',
            'Encoding categorical variables (one-hot, label)',
            'Outlier detection and treatment',
            'Feature engineering techniques',
            'Exploratory Data Analysis (EDA) workflow',
            'Train/test/validation splits',
          ],
          resources: [
            { title: 'Data Preprocessing - Krish Naik', url: 'https://www.youtube.com/watch?v=sbbsJRWqhPM', type: 'video' },
            { title: 'Kaggle Learn Data Cleaning', url: 'https://www.kaggle.com/learn/data-cleaning', type: 'course' },
            { title: 'Feature Engineering - Kaggle', url: 'https://www.kaggle.com/learn/feature-engineering', type: 'course' },
          ],
          project: {
            title: 'Titanic Dataset EDA',
            description: 'Perform complete EDA on the Titanic dataset: handle missing values, engineer features, visualize patterns, and prepare data for modeling.',
          },
        },
      ],
    },
    {
      id: 'classical-ml',
      title: 'Classical Machine Learning',
      description: 'Master supervised and unsupervised learning algorithms with scikit-learn.',
      timeEstimate: '5-6 weeks',
      color: 'lime',
      topics: [
        {
          id: 'supervised-learning',
          title: 'Supervised Learning',
          description: 'Learn classification and regression algorithms for labeled data.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Linear Regression and Polynomial Regression',
            'Logistic Regression for classification',
            'Decision Trees and Random Forests',
            'Support Vector Machines (SVM)',
            'K-Nearest Neighbors (KNN)',
            'Gradient Boosting (XGBoost, LightGBM)',
            'Model evaluation metrics (accuracy, precision, recall, F1, AUC)',
            'Cross-validation and hyperparameter tuning',
          ],
          resources: [
            { title: 'Machine Learning Course - Andrew Ng (Stanford)', url: 'https://www.youtube.com/playlist?list=PLkDaE6sCZn6FNC6YRfRQc_FbeQrF8BwGI', type: 'video' },
            { title: 'Scikit-learn Tutorial - freeCodeCamp', url: 'https://www.youtube.com/watch?v=pqNCD_5r0IU', type: 'video' },
            { title: 'Scikit-learn Documentation', url: 'https://scikit-learn.org/stable/user_guide.html', type: 'docs' },
            { title: 'StatQuest - Machine Learning', url: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF', type: 'video' },
          ],
          project: {
            title: 'House Price Prediction',
            description: 'Build a regression model to predict house prices. Compare multiple algorithms, tune hyperparameters, and evaluate using cross-validation.',
          },
        },
        {
          id: 'unsupervised-learning',
          title: 'Unsupervised Learning',
          description: 'Discover patterns in data without labels using clustering and dimensionality reduction.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'K-Means clustering and elbow method',
            'Hierarchical clustering (dendrograms)',
            'DBSCAN for density-based clustering',
            'Principal Component Analysis (PCA)',
            't-SNE and UMAP for visualization',
            'Anomaly detection techniques',
            'Association rules (Apriori)',
          ],
          resources: [
            { title: 'Unsupervised Learning - Andrew Ng', url: 'https://www.youtube.com/watch?v=jAA2g9ItoAc', type: 'video' },
            { title: 'StatQuest - PCA Explained', url: 'https://www.youtube.com/watch?v=FgakZw6K1QQ', type: 'video' },
            { title: 'Kaggle Learn Clustering', url: 'https://www.kaggle.com/learn/intro-to-machine-learning', type: 'course' },
          ],
          project: {
            title: 'Customer Segmentation',
            description: 'Segment customers using K-Means and hierarchical clustering on purchasing data. Visualize clusters with PCA and create actionable profiles.',
          },
        },
        {
          id: 'ml-pipelines',
          title: 'ML Pipelines & Model Selection',
          description: 'Build production-ready ML workflows with proper evaluation and selection.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Scikit-learn pipelines (preprocessing + model)',
            'GridSearchCV and RandomizedSearchCV',
            'Bias-variance tradeoff',
            'Overfitting prevention (regularization, early stopping)',
            'Ensemble methods (bagging, boosting, stacking)',
            'Model serialization (pickle, joblib)',
            'Feature importance and model interpretability',
          ],
          resources: [
            { title: 'ML Pipelines - Scikit-learn', url: 'https://scikit-learn.org/stable/modules/compose.html', type: 'docs' },
            { title: 'XGBoost Tutorial - StatQuest', url: 'https://www.youtube.com/watch?v=OtD8wVaFm6E', type: 'video' },
            { title: 'Model Selection - Krish Naik', url: 'https://www.youtube.com/watch?v=UrOmIhp7Cjg', type: 'video' },
          ],
          project: {
            title: 'Kaggle Competition Entry',
            description: 'Enter a Kaggle competition: build a full pipeline with preprocessing, model selection, hyperparameter tuning, and ensemble techniques.',
          },
        },
      ],
    },
    {
      id: 'deep-learning',
      title: 'Deep Learning',
      description: 'Build neural networks for image recognition, sequence modeling, and more.',
      timeEstimate: '6-7 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'neural-networks',
          title: 'Neural Networks & PyTorch',
          description: 'Understand neural networks from scratch and implement them with PyTorch.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Perceptrons and activation functions',
            'Forward propagation and backpropagation',
            'Loss functions and optimizers (SGD, Adam)',
            'PyTorch tensors and autograd',
            'Building models with nn.Module',
            'Training loops and validation',
            'GPU acceleration with CUDA',
            'Batch normalization and dropout',
          ],
          resources: [
            { title: 'Deep Learning with PyTorch - freeCodeCamp', url: 'https://www.youtube.com/watch?v=V_xro1bcAuA', type: 'video' },
            { title: 'PyTorch Official Tutorials', url: 'https://pytorch.org/tutorials/', type: 'docs' },
            { title: '3Blue1Brown - Neural Networks', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi', type: 'video' },
            { title: 'Fast.ai Practical Deep Learning', url: 'https://course.fast.ai/', type: 'course' },
          ],
          project: {
            title: 'MNIST Digit Classifier',
            description: 'Build a neural network from scratch to classify handwritten digits. Achieve 98%+ accuracy with proper architecture and training techniques.',
          },
        },
        {
          id: 'cnn-computer-vision',
          title: 'CNNs & Computer Vision',
          description: 'Build convolutional neural networks for image classification, detection, and segmentation.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Convolution operations and filters',
            'Pooling layers and feature maps',
            'CNN architectures (LeNet, VGG, ResNet)',
            'Transfer learning and fine-tuning',
            'Data augmentation strategies',
            'Object detection (YOLO overview)',
            'Image segmentation basics',
            'Pre-trained models (torchvision)',
          ],
          resources: [
            { title: 'CNN Explained - deeplizard', url: 'https://www.youtube.com/playlist?list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG', type: 'video' },
            { title: 'CS231n - Stanford CNN Course', url: 'https://www.youtube.com/playlist?list=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv', type: 'video' },
            { title: 'Transfer Learning - PyTorch', url: 'https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html', type: 'docs' },
            { title: 'Kaggle Computer Vision Course', url: 'https://www.kaggle.com/learn/computer-vision', type: 'course' },
          ],
          project: {
            title: 'Image Classification App',
            description: 'Build a CNN to classify images (e.g., dog breeds or plant diseases). Use transfer learning with ResNet, achieve high accuracy, and create a simple web interface.',
          },
        },
        {
          id: 'rnn-sequences',
          title: 'RNNs & Sequence Models',
          description: 'Process sequential data with recurrent networks, LSTMs, and attention.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Recurrent Neural Networks (RNN) basics',
            'Vanishing gradient problem',
            'LSTM and GRU architectures',
            'Sequence-to-sequence models',
            'Attention mechanism intuition',
            'Time series forecasting',
            'Text generation with RNNs',
          ],
          resources: [
            { title: 'RNN/LSTM Explained - StatQuest', url: 'https://www.youtube.com/watch?v=AsNTP8Kwu80', type: 'video' },
            { title: 'Sequence Models - Andrew Ng', url: 'https://www.youtube.com/playlist?list=PLkDaE6sCZn6F6wUI9t8UXIyI_V2a-c4VE', type: 'video' },
            { title: 'PyTorch RNN Tutorial', url: 'https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html', type: 'docs' },
          ],
          project: {
            title: 'Stock Price Predictor',
            description: 'Build an LSTM model to forecast stock prices. Handle time series data, implement windowing, and visualize predictions vs actuals.',
          },
        },
      ],
    },
    {
      id: 'nlp-llms',
      title: 'NLP & Large Language Models',
      description: 'Process and generate text with transformers, fine-tuning, and LLM applications.',
      timeEstimate: '5-6 weeks',
      color: 'orange',
      topics: [
        {
          id: 'nlp-fundamentals',
          title: 'NLP Fundamentals',
          description: 'Learn text preprocessing, embeddings, and classical NLP techniques.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Text preprocessing (tokenization, stemming, lemmatization)',
            'Bag of Words and TF-IDF',
            'Word embeddings (Word2Vec, GloVe)',
            'Sentiment analysis',
            'Named Entity Recognition (NER)',
            'Text classification techniques',
            'Regular expressions for text processing',
          ],
          resources: [
            { title: 'NLP with Python - freeCodeCamp', url: 'https://www.youtube.com/watch?v=fOvTtapxa9c', type: 'video' },
            { title: 'Hugging Face NLP Course', url: 'https://huggingface.co/learn/nlp-course', type: 'course' },
            { title: 'spaCy 101', url: 'https://spacy.io/usage/spacy-101', type: 'docs' },
          ],
          project: {
            title: 'Sentiment Analyzer',
            description: 'Build a sentiment analysis system for product reviews. Compare classical (TF-IDF + SVM) vs embedding-based approaches.',
          },
        },
        {
          id: 'transformers',
          title: 'Transformers & Hugging Face',
          description: 'Master the transformer architecture and use pre-trained models.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Transformer architecture (self-attention, multi-head)',
            'BERT, GPT, T5 model families',
            'Hugging Face Transformers library',
            'Tokenizers and model pipelines',
            'Fine-tuning pre-trained models',
            'Text generation and summarization',
            'Question answering systems',
            'Embedding models and semantic search',
          ],
          resources: [
            { title: 'Transformers Explained - 3Blue1Brown', url: 'https://www.youtube.com/watch?v=wjZofJX0v4M', type: 'video' },
            { title: 'Hugging Face Course', url: 'https://huggingface.co/learn/nlp-course', type: 'course' },
            { title: 'Attention Is All You Need (Paper Walkthrough)', url: 'https://www.youtube.com/watch?v=iDulhoQ2pro', type: 'video' },
            { title: 'Hugging Face Docs', url: 'https://huggingface.co/docs/transformers/', type: 'docs' },
          ],
          project: {
            title: 'Fine-tuned Text Classifier',
            description: 'Fine-tune a BERT model for domain-specific text classification (e.g., medical, legal, or financial text). Evaluate and compare with baselines.',
          },
        },
        {
          id: 'llm-applications',
          title: 'LLM Applications & RAG',
          description: 'Build applications powered by large language models and retrieval-augmented generation.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Prompt engineering techniques',
            'OpenAI / Anthropic API usage',
            'LangChain / LlamaIndex for LLM apps',
            'Retrieval-Augmented Generation (RAG)',
            'Vector databases (Pinecone, Chroma, Weaviate)',
            'Document parsing and chunking',
            'Evaluation of LLM outputs',
            'Guardrails and safety',
          ],
          resources: [
            { title: 'LangChain Crash Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=lG7Uxts9SXs', type: 'video' },
            { title: 'RAG from Scratch - LangChain', url: 'https://www.youtube.com/watch?v=sVcwVQRHIc8', type: 'video' },
            { title: 'OpenAI API Docs', url: 'https://platform.openai.com/docs/', type: 'docs' },
            { title: 'Pinecone Learning Center', url: 'https://www.pinecone.io/learn/', type: 'article' },
          ],
          project: {
            title: 'RAG Chatbot',
            description: 'Build a chatbot that answers questions about uploaded documents using RAG. Implement document chunking, vector storage, and contextual retrieval.',
          },
        },
      ],
    },
    {
      id: 'mlops-deployment',
      title: 'MLOps & Deployment',
      description: 'Deploy, monitor, and maintain ML models in production.',
      timeEstimate: '4-5 weeks',
      color: 'purple',
      topics: [
        {
          id: 'model-deployment',
          title: 'Model Deployment',
          description: 'Serve ML models as APIs and deploy them to production.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'FastAPI for ML model serving',
            'Model serialization (ONNX, TorchScript)',
            'REST APIs for inference',
            'Batch vs real-time prediction',
            'Docker for ML applications',
            'Cloud deployment (AWS SageMaker, GCP Vertex AI)',
            'Serverless deployment options',
            'Model versioning',
          ],
          resources: [
            { title: 'Deploy ML Models with FastAPI', url: 'https://www.youtube.com/watch?v=h5wLuVDr0oc', type: 'video' },
            { title: 'FastAPI Documentation', url: 'https://fastapi.tiangolo.com/', type: 'docs' },
            { title: 'MLflow Docs', url: 'https://mlflow.org/docs/latest/index.html', type: 'docs' },
            { title: 'Docker for Data Science - Krish Naik', url: 'https://www.youtube.com/watch?v=bi0cKgmRuiA', type: 'video' },
          ],
          project: {
            title: 'ML Model API',
            description: 'Deploy your best model as a FastAPI service with Docker. Include input validation, model versioning, health checks, and a simple frontend.',
          },
        },
        {
          id: 'experiment-tracking',
          title: 'Experiment Tracking & MLOps',
          description: 'Track experiments, manage datasets, and automate ML workflows.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'MLflow for experiment tracking',
            'Weights & Biases (W&B) for visualization',
            'DVC for data versioning',
            'Reproducible experiments',
            'Hyperparameter sweep automation',
            'Model registry and promotion',
            'CI/CD for ML (GitHub Actions + tests)',
          ],
          resources: [
            { title: 'MLflow Tutorial - Krish Naik', url: 'https://www.youtube.com/watch?v=qdcHHrsXA48', type: 'video' },
            { title: 'Weights & Biases Intro', url: 'https://www.youtube.com/watch?v=9zrmUIlScdY', type: 'video' },
            { title: 'DVC Documentation', url: 'https://dvc.org/doc', type: 'docs' },
          ],
          project: {
            title: 'Tracked ML Pipeline',
            description: 'Build a complete ML pipeline with MLflow tracking, DVC for data, automated hyperparameter sweeps, and a model registry.',
          },
        },
        {
          id: 'ml-system-design',
          title: 'ML System Design',
          description: 'Design end-to-end ML systems for real-world applications.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'ML system design framework',
            'Data pipelines and feature stores',
            'Model monitoring and drift detection',
            'A/B testing for ML models',
            'Feedback loops and retraining',
            'Scaling ML systems',
            'Responsible AI and fairness',
            'Cost optimization for inference',
          ],
          resources: [
            { title: 'ML System Design - Chip Huyen', url: 'https://www.youtube.com/watch?v=nLW-BPHkf4s', type: 'video' },
            { title: 'Designing ML Systems (Book Summary)', url: 'https://www.youtube.com/watch?v=tJiPU6-sVQM', type: 'video' },
            { title: 'Made With ML - MLOps Course', url: 'https://madewithml.com/', type: 'course' },
            { title: 'Google ML Engineering Best Practices', url: 'https://developers.google.com/machine-learning/guides/rules-of-ml', type: 'docs' },
          ],
          project: {
            title: 'End-to-End ML System',
            description: 'Design and implement a complete ML system: data pipeline, training, deployment, monitoring, and automated retraining when performance drops.',
          },
        },
      ],
    },
  ],
};
