import { Roadmap } from '@/types/roadmap';

export const backendDeveloperRoadmap: Roadmap = {
  slug: 'backend-developer',
  title: 'Backend Developer',
  description: 'Learn server-side programming, databases, APIs, authentication, and deployment to build scalable, secure backend systems.',
  icon: 'Server',
  accent: '#A8F0E6',
  totalTime: '6-8 months',
  stages: [
    {
      id: 'foundations',
      title: 'Foundations',
      description: 'Learn a server-side language, how the internet works, and version control.',
      timeEstimate: '3-4 weeks',
      color: 'green',
      topics: [
        {
          id: 'how-internet-works',
          title: 'How the Internet Works',
          description: 'Understand HTTP, DNS, client-server model, and how requests travel across the internet.',
          timeEstimate: '2-3 days',
          whatToLearn: [
            'HTTP/HTTPS protocol and request/response cycle',
            'DNS resolution and domain names',
            'Client-server architecture',
            'TCP/IP basics and ports',
            'Status codes (2xx, 3xx, 4xx, 5xx)',
            'Headers, cookies, and caching',
          ],
          resources: [
            { title: 'How the Internet Works - CS50', url: 'https://www.youtube.com/watch?v=kBXQZMmiA4s', type: 'video' },
            { title: 'HTTP Overview - MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview', type: 'docs' },
            { title: 'How DNS Works (Comic)', url: 'https://howdns.works/', type: 'article' },
          ],
          project: {
            title: 'HTTP Request Logger',
            description: 'Build a simple script that makes HTTP requests to various APIs and logs the status codes, headers, and response times.',
          },
        },
        {
          id: 'javascript-nodejs',
          title: 'JavaScript & Node.js',
          description: 'Master JavaScript fundamentals and Node.js runtime for server-side development.',
          timeEstimate: '10-14 days',
          whatToLearn: [
            'Variables, data types, and operators',
            'Functions, closures, and scope',
            'Async programming: callbacks, Promises, async/await',
            'ES6+ features (destructuring, spread, modules)',
            'Node.js runtime and event loop',
            'npm/pnpm package management',
            'File system and path modules',
            'Environment variables and process management',
          ],
          resources: [
            { title: 'JavaScript.info - The Modern JavaScript Tutorial', url: 'https://javascript.info/', type: 'course' },
            { title: 'Node.js Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=fBNz5xF-Kx4', type: 'video' },
            { title: 'Node.js Official Docs - Getting Started', url: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs', type: 'docs' },
            { title: 'The Odin Project - Node.js Path', url: 'https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs', type: 'course' },
          ],
          project: {
            title: 'CLI Task Manager',
            description: 'Build a command-line task manager that stores tasks in a JSON file. Support add, list, complete, and delete operations.',
          },
        },
        {
          id: 'git-terminal',
          title: 'Git & Terminal',
          description: 'Master version control and command-line operations essential for backend development.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Terminal navigation and file operations',
            'Git basics (init, add, commit, branch, merge)',
            'Remote repos, pull requests, code review',
            'Git workflow (feature branches, rebasing)',
            'SSH keys and authentication',
            'Shell scripting basics',
          ],
          resources: [
            { title: 'Git & GitHub for Beginners - freeCodeCamp', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', type: 'video' },
            { title: 'Learn Git Branching (Interactive)', url: 'https://learngitbranching.js.org/', type: 'course' },
            { title: 'The Linux Command Line - William Shotts', url: 'https://linuxcommand.org/tlcl.php', type: 'article' },
          ],
          project: {
            title: 'Dotfiles Repository',
            description: 'Create a Git repo with your terminal config, aliases, and a setup script that automates your dev environment setup.',
          },
        },
      ],
    },
    {
      id: 'apis-servers',
      title: 'APIs & Servers',
      description: 'Build RESTful APIs, handle routing, middleware, and learn Express.js.',
      timeEstimate: '4-5 weeks',
      color: 'lime',
      topics: [
        {
          id: 'express-fundamentals',
          title: 'Express.js Fundamentals',
          description: 'Build web servers and APIs using Express.js, the most popular Node.js framework.',
          timeEstimate: '7-10 days',
          whatToLearn: [
            'Setting up an Express server',
            'Routing (GET, POST, PUT, DELETE)',
            'Request and response objects',
            'Middleware (built-in, third-party, custom)',
            'Error handling middleware',
            'Serving static files',
            'Template engines (EJS/Pug basics)',
            'Express Router for modular routes',
          ],
          resources: [
            { title: 'Express.js Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=CnH3kAXSrmU', type: 'video' },
            { title: 'Express.js Official Guide', url: 'https://expressjs.com/en/guide/routing.html', type: 'docs' },
            { title: 'MDN Express/Node Introduction', url: 'https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs', type: 'course' },
            { title: 'Build a REST API with Node.js - freeCodeCamp', url: 'https://www.youtube.com/watch?v=l8WPEL6YDPg', type: 'video' },
          ],
          project: {
            title: 'Bookstore REST API',
            description: 'Build a CRUD API for a bookstore with routes for books, authors, and categories. Use Express Router for modularity.',
          },
        },
        {
          id: 'rest-api-design',
          title: 'REST API Design',
          description: 'Learn principles of designing clean, consistent, and scalable REST APIs.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'REST constraints and principles',
            'Resource naming conventions',
            'HTTP methods and their semantics',
            'Status codes and error responses',
            'Pagination, filtering, and sorting',
            'API versioning strategies',
            'Request validation and sanitization',
            'CORS and preflight requests',
          ],
          resources: [
            { title: 'RESTful API Design - Best Practices', url: 'https://www.youtube.com/watch?v=-MTSQjw5DrM', type: 'video' },
            { title: 'REST API Tutorial', url: 'https://restfulapi.net/', type: 'article' },
            { title: 'Microsoft REST API Guidelines', url: 'https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md', type: 'docs' },
          ],
          project: {
            title: 'Blog API with Pagination',
            description: 'Design and build a blog API with posts, comments, and tags. Implement pagination, filtering by tag, and proper error responses.',
          },
        },
        {
          id: 'api-testing',
          title: 'API Testing & Documentation',
          description: 'Test your APIs thoroughly and create developer-friendly documentation.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Postman/Insomnia for manual testing',
            'Writing automated tests with Jest/Vitest + Supertest',
            'Unit tests vs integration tests',
            'OpenAPI/Swagger specification',
            'Auto-generating API docs',
            'Environment variables and test configurations',
          ],
          resources: [
            { title: 'Postman Beginner Tutorial - freeCodeCamp', url: 'https://www.youtube.com/watch?v=VywxIQ2ZXw4', type: 'video' },
            { title: 'Testing Express APIs with Jest & Supertest', url: 'https://www.youtube.com/watch?v=r5L1XRZaCR0', type: 'video' },
            { title: 'Swagger/OpenAPI Docs', url: 'https://swagger.io/docs/specification/about/', type: 'docs' },
          ],
          project: {
            title: 'Test Suite for Bookstore API',
            description: 'Write comprehensive tests for your Bookstore API using Jest and Supertest. Cover all CRUD operations and edge cases. Generate Swagger docs.',
          },
        },
      ],
    },
    {
      id: 'databases',
      title: 'Databases',
      description: 'Master SQL and NoSQL databases, ORMs, and data modeling.',
      timeEstimate: '5-6 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'sql-postgresql',
          title: 'SQL & PostgreSQL',
          description: 'Learn relational database design, SQL queries, and PostgreSQL.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Relational database concepts and normalization',
            'CREATE, INSERT, UPDATE, DELETE',
            'SELECT with WHERE, JOIN, GROUP BY, ORDER BY',
            'Indexes and query performance',
            'Transactions and ACID properties',
            'Database schemas and migrations',
            'PostgreSQL-specific features (JSONB, arrays, CTEs)',
            'Connection pooling',
          ],
          resources: [
            { title: 'SQL Tutorial - freeCodeCamp (Full Course)', url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY', type: 'video' },
            { title: 'PostgreSQL Tutorial', url: 'https://www.postgresqltutorial.com/', type: 'course' },
            { title: 'SQLBolt - Interactive SQL Lessons', url: 'https://sqlbolt.com/', type: 'course' },
            { title: 'PostgreSQL Official Docs', url: 'https://www.postgresql.org/docs/current/tutorial.html', type: 'docs' },
          ],
          project: {
            title: 'E-commerce Database Schema',
            description: 'Design and implement a normalized database for an e-commerce store with users, products, orders, and reviews. Write complex queries for reporting.',
          },
        },
        {
          id: 'mongodb',
          title: 'MongoDB & NoSQL',
          description: 'Learn document-based databases and when to use NoSQL over SQL.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Document model vs relational model',
            'CRUD operations in MongoDB',
            'Schema design patterns (embedding vs referencing)',
            'Indexing and aggregation pipeline',
            'Mongoose ODM for Node.js',
            'When to use SQL vs NoSQL',
            'MongoDB Atlas (cloud setup)',
          ],
          resources: [
            { title: 'MongoDB Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=-56x56UppqQ', type: 'video' },
            { title: 'MongoDB University (Free Courses)', url: 'https://learn.mongodb.com/', type: 'course' },
            { title: 'Mongoose Guide', url: 'https://mongoosejs.com/docs/guide.html', type: 'docs' },
            { title: 'SQL vs NoSQL - Fireship', url: 'https://www.youtube.com/watch?v=W2Z7fbCLSTw', type: 'video' },
          ],
          project: {
            title: 'Social Media Data Layer',
            description: 'Build the data layer for a social media app with MongoDB. Model users, posts, comments, likes, and followers with proper indexing.',
          },
        },
        {
          id: 'orm-prisma',
          title: 'Prisma ORM',
          description: 'Use Prisma for type-safe database access, migrations, and schema management.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Prisma schema language',
            'Data modeling with relations',
            'Migrations (create, apply, rollback)',
            'Prisma Client for type-safe queries',
            'Filtering, pagination, and transactions',
            'Seeding databases',
            'Prisma Studio for visual editing',
          ],
          resources: [
            { title: 'Prisma Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=RebA5J-rlwg', type: 'video' },
            { title: 'Prisma Docs - Getting Started', url: 'https://www.prisma.io/docs/getting-started', type: 'docs' },
            { title: 'Full Stack App with Prisma - Fireship', url: 'https://www.youtube.com/watch?v=rLQjQ4aFbfI', type: 'video' },
          ],
          project: {
            title: 'Task Management API with Prisma',
            description: 'Rebuild your task API using Prisma + PostgreSQL. Implement user-owned task lists, priorities, due dates, and database migrations.',
          },
        },
        {
          id: 'redis-caching',
          title: 'Redis & Caching',
          description: 'Learn caching strategies and Redis for high-performance data access.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Why caching matters (latency, throughput)',
            'Redis data structures (strings, hashes, lists, sets)',
            'Cache-aside, write-through, write-behind patterns',
            'TTL and cache invalidation strategies',
            'Session storage with Redis',
            'Rate limiting with Redis',
            'Pub/Sub messaging basics',
          ],
          resources: [
            { title: 'Redis Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=jgpVdJB2sKQ', type: 'video' },
            { title: 'Redis Official Tutorial', url: 'https://redis.io/docs/get-started/', type: 'docs' },
            { title: 'Caching Strategies - ByteByteGo', url: 'https://www.youtube.com/watch?v=U3RkDLtS7uY', type: 'video' },
          ],
          project: {
            title: 'Cached API with Rate Limiting',
            description: 'Add Redis caching to your existing API. Cache expensive queries, implement rate limiting (100 req/min), and add session-based auth.',
          },
        },
      ],
    },
    {
      id: 'auth-security',
      title: 'Authentication & Security',
      description: 'Implement secure authentication, authorization, and protect against common vulnerabilities.',
      timeEstimate: '4-5 weeks',
      color: 'orange',
      topics: [
        {
          id: 'authentication',
          title: 'Authentication (JWT & Sessions)',
          description: 'Implement secure user authentication with JSON Web Tokens and session-based auth.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Password hashing with bcrypt',
            'JWT structure (header, payload, signature)',
            'Access tokens vs refresh tokens',
            'Session-based auth with cookies',
            'JWT vs sessions — tradeoffs',
            'Token storage and rotation',
            'Logout and token invalidation',
            'Multi-factor authentication concepts',
          ],
          resources: [
            { title: 'JWT Authentication - Net Ninja', url: 'https://www.youtube.com/watch?v=SoAbXuwl_CQ', type: 'video' },
            { title: 'Session vs JWT Auth - Fireship', url: 'https://www.youtube.com/watch?v=UBUNrFtufWo', type: 'video' },
            { title: 'OWASP Authentication Cheatsheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', type: 'docs' },
            { title: 'Passport.js Docs', url: 'https://www.passportjs.org/docs/', type: 'docs' },
          ],
          project: {
            title: 'Auth System with JWT',
            description: 'Build a complete auth system: signup, login, logout, refresh tokens, password reset via email, and protected routes.',
          },
        },
        {
          id: 'oauth-social',
          title: 'OAuth 2.0 & Social Login',
          description: 'Implement third-party authentication with Google, GitHub, and other providers.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'OAuth 2.0 flow (authorization code grant)',
            'OpenID Connect basics',
            'Google OAuth integration',
            'GitHub OAuth integration',
            'Managing user accounts linked to providers',
            'Scopes and permissions',
          ],
          resources: [
            { title: 'OAuth 2.0 Explained - ByteByteGo', url: 'https://www.youtube.com/watch?v=ZV5yTm4pT8g', type: 'video' },
            { title: 'Google OAuth2 with Node.js', url: 'https://www.youtube.com/watch?v=Qt3KJZ2kQk0', type: 'video' },
            { title: 'OAuth 2.0 Simplified - Aaron Parecki', url: 'https://aaronparecki.com/oauth-2-simplified/', type: 'article' },
          ],
          project: {
            title: 'Social Login Integration',
            description: 'Add Google and GitHub login to your auth system. Link social accounts to existing users and handle edge cases.',
          },
        },
        {
          id: 'authorization-rbac',
          title: 'Authorization & RBAC',
          description: 'Implement role-based access control and fine-grained permissions.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Authentication vs Authorization',
            'Role-based access control (RBAC)',
            'Permission-based access control',
            'Middleware for route protection',
            'Resource ownership checks',
            'Admin panels and user management',
            'API key management',
          ],
          resources: [
            { title: 'RBAC in Node.js - Web Dev Simplified', url: 'https://www.youtube.com/watch?v=jI4K7L-LI58', type: 'video' },
            { title: 'Authorization Patterns - Auth0 Blog', url: 'https://auth0.com/blog/node-js-and-express-tutorial-building-and-securing-restful-apis/', type: 'article' },
            { title: 'OWASP Authorization Cheatsheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html', type: 'docs' },
          ],
          project: {
            title: 'Multi-Role CMS Backend',
            description: 'Build a CMS backend with Admin, Editor, and Viewer roles. Admins manage users, Editors create/edit content, Viewers can only read.',
          },
        },
        {
          id: 'security-best-practices',
          title: 'Security Best Practices',
          description: 'Protect your application against OWASP Top 10 vulnerabilities.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'SQL injection and prevention',
            'XSS (Cross-Site Scripting) protection',
            'CSRF protection',
            'Input validation and sanitization',
            'Rate limiting and brute force protection',
            'HTTPS and TLS certificates',
            'Security headers (Helmet.js)',
            'Dependency vulnerability scanning',
            'Environment variable management',
          ],
          resources: [
            { title: 'OWASP Top 10 - Explained', url: 'https://www.youtube.com/watch?v=avFR_Af0KGk', type: 'video' },
            { title: 'Node.js Security Best Practices', url: 'https://nodejs.org/en/learn/getting-started/security-best-practices', type: 'docs' },
            { title: 'Helmet.js Docs', url: 'https://helmetjs.github.io/', type: 'docs' },
            { title: 'Web Security - MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/Security', type: 'article' },
          ],
          project: {
            title: 'Security Audit & Hardening',
            description: 'Take your existing API and harden it: add Helmet, rate limiting, input validation with Zod, CORS config, and fix any SQL injection vectors.',
          },
        },
      ],
    },
    {
      id: 'advanced-deployment',
      title: 'Advanced & Deployment',
      description: 'Learn advanced patterns, real-time features, and deploy to production.',
      timeEstimate: '5-6 weeks',
      color: 'purple',
      topics: [
        {
          id: 'websockets-realtime',
          title: 'WebSockets & Real-time',
          description: 'Build real-time features with WebSockets and Server-Sent Events.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'WebSocket protocol vs HTTP',
            'Socket.io for real-time communication',
            'Rooms and namespaces',
            'Broadcasting events',
            'Server-Sent Events (SSE) for one-way streams',
            'Handling disconnections and reconnection',
            'Scaling WebSockets (sticky sessions, Redis adapter)',
          ],
          resources: [
            { title: 'WebSockets in 100 Seconds - Fireship', url: 'https://www.youtube.com/watch?v=1BfCnjr_Vjg', type: 'video' },
            { title: 'Socket.io Chat App Tutorial', url: 'https://socket.io/get-started/chat', type: 'docs' },
            { title: 'Real-time App with Socket.io - Traversy Media', url: 'https://www.youtube.com/watch?v=jD7FnbI76Hg', type: 'video' },
          ],
          project: {
            title: 'Real-time Chat Application',
            description: 'Build a chat app with Socket.io featuring rooms, typing indicators, online status, message history, and user notifications.',
          },
        },
        {
          id: 'message-queues',
          title: 'Message Queues & Background Jobs',
          description: 'Handle async processing with message queues and job schedulers.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Why async processing (email, image resize, reports)',
            'Bull/BullMQ for job queues with Redis',
            'Job scheduling and retries',
            'Dead letter queues',
            'RabbitMQ/Kafka concepts',
            'Worker processes and scaling',
            'Monitoring queue health',
          ],
          resources: [
            { title: 'Message Queues Explained - ByteByteGo', url: 'https://www.youtube.com/watch?v=5-Rq4-PZlew', type: 'video' },
            { title: 'BullMQ Documentation', url: 'https://docs.bullmq.io/', type: 'docs' },
            { title: 'Background Jobs in Node.js - Fireship', url: 'https://www.youtube.com/watch?v=nPmJvGkMKCo', type: 'video' },
          ],
          project: {
            title: 'Email Queue System',
            description: 'Build an email sending service with BullMQ. Queue welcome emails on signup, password resets, and weekly digest emails with retry logic.',
          },
        },
        {
          id: 'docker-containers',
          title: 'Docker & Containers',
          description: 'Containerize your applications for consistent development and deployment.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Container concepts and why Docker',
            'Dockerfile syntax and best practices',
            'Building and running containers',
            'Docker Compose for multi-service apps',
            'Volumes and networking',
            'Multi-stage builds for production',
            'Container registries (Docker Hub, GHCR)',
            'Health checks and restart policies',
          ],
          resources: [
            { title: 'Docker in 100 Seconds - Fireship', url: 'https://www.youtube.com/watch?v=Gjnup-PuquQ', type: 'video' },
            { title: 'Docker Crash Course - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=pg19Z8LL06w', type: 'video' },
            { title: 'Docker Official Getting Started', url: 'https://docs.docker.com/get-started/', type: 'docs' },
            { title: 'Docker Compose Tutorial', url: 'https://docs.docker.com/compose/gettingstarted/', type: 'docs' },
          ],
          project: {
            title: 'Containerized Full API',
            description: 'Dockerize your complete API with PostgreSQL, Redis, and the Node.js app. Use Docker Compose for local dev with hot reload.',
          },
        },
        {
          id: 'ci-cd-deployment',
          title: 'CI/CD & Cloud Deployment',
          description: 'Automate testing, build pipelines, and deploy to production.',
          timeEstimate: '5-7 days',
          whatToLearn: [
            'CI/CD concepts and benefits',
            'GitHub Actions for automated testing',
            'Build and deploy pipelines',
            'Cloud platforms (Railway, Render, AWS, Vercel)',
            'Environment management (dev, staging, prod)',
            'Database hosting and backups',
            'Domain setup and SSL certificates',
            'Monitoring and logging (PM2, health checks)',
            'Zero-downtime deployments',
          ],
          resources: [
            { title: 'GitHub Actions Tutorial - Fireship', url: 'https://www.youtube.com/watch?v=eB0nUzAI7M8', type: 'video' },
            { title: 'Deploy Node.js to Railway', url: 'https://docs.railway.app/guides/nodejs', type: 'docs' },
            { title: 'CI/CD Explained - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=scEDHsr3APg', type: 'video' },
            { title: 'AWS Free Tier - Getting Started', url: 'https://aws.amazon.com/free/', type: 'docs' },
          ],
          project: {
            title: 'Production-Ready API Deployment',
            description: 'Deploy your full API with CI/CD: GitHub Actions for tests, auto-deploy to Railway/Render, PostgreSQL on Supabase, Redis on Upstash, custom domain with SSL.',
          },
        },
        {
          id: 'system-design-basics',
          title: 'System Design Basics',
          description: 'Understand how to design scalable backend architectures.',
          timeEstimate: '5-7 days',
          whatToLearn: [
            'Monolith vs microservices',
            'Load balancing strategies',
            'Horizontal vs vertical scaling',
            'Database sharding and replication',
            'CDN and edge computing',
            'API Gateway pattern',
            'Event-driven architecture',
            'CAP theorem and consistency models',
          ],
          resources: [
            { title: 'System Design Primer - GitHub', url: 'https://github.com/donnemartin/system-design-primer', type: 'article' },
            { title: 'System Design for Beginners - ByteByteGo', url: 'https://www.youtube.com/watch?v=m8Icp_Cid5o', type: 'video' },
            { title: 'Designing Data-Intensive Applications (Summary)', url: 'https://www.youtube.com/watch?v=PdtlXdse7pw', type: 'video' },
            { title: 'ByteByteGo Newsletter', url: 'https://blog.bytebytego.com/', type: 'article' },
          ],
          project: {
            title: 'URL Shortener (Full System)',
            description: 'Design and build a URL shortener with analytics: short link generation, redirect tracking, click analytics dashboard, rate limiting, and horizontal scaling considerations.',
          },
        },
      ],
    },
  ],
};
