import { Roadmap } from '@/types/roadmap';

export const cybersecurityRoadmap: Roadmap = {
  slug: 'cybersecurity',
  title: 'Cybersecurity',
  description: 'Learn network security, ethical hacking, threat analysis, and defense strategies to protect systems and data from cyber threats.',
  icon: 'Shield',
  accent: '#D8CCFF',
  totalTime: '8-10 months',
  languages: ['Python', 'Bash', 'C (for exploit dev)'],
  relatedRoadmaps: [
    { slug: 'devops-engineer', relation: 'shared-topics', description: 'Shares Linux, networking, and cloud infrastructure knowledge' },
    { slug: 'backend-developer', relation: 'shared-topics', description: 'Understanding backend helps with web application security testing' },
    { slug: 'full-stack-developer', relation: 'shared-topics', description: 'AppSec requires understanding how full-stack apps are built' },
  ],
  stages: [
    {
      id: 'foundations',
      title: 'Security Foundations',
      description: 'Build a strong base in networking, operating systems, and security principles.',
      timeEstimate: '5-6 weeks',
      color: 'green',
      topics: [
        {
          id: 'networking-security',
          title: 'Networking for Security',
          description: 'Deep understanding of networks — the foundation of all cybersecurity.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'OSI and TCP/IP models in depth',
            'Common protocols (HTTP, DNS, SMTP, FTP, SSH)',
            'IP addressing, subnetting, and routing',
            'Packet analysis with Wireshark',
            'Firewalls and packet filtering',
            'VPNs and tunneling protocols',
            'Wireless network security (WPA2/WPA3)',
            'Network scanning (Nmap)',
          ],
          resources: [
            { title: 'Networking for Hackers - NetworkChuck', url: 'https://www.youtube.com/playlist?list=PLIhvC56v63IJVXv0GJcl9vO5Z6znCVb1P', type: 'video' },
            { title: 'Wireshark Tutorial - Chris Greer', url: 'https://www.youtube.com/watch?v=lb1Dw0elj0Q', type: 'video' },
            { title: 'CompTIA Network+ Study Guide', url: 'https://www.youtube.com/watch?v=qiQR5rTSshw', type: 'video' },
            { title: 'Nmap Documentation', url: 'https://nmap.org/book/man.html', type: 'docs' },
          ],
          project: {
            title: 'Network Analysis Lab',
            description: 'Set up a virtual lab, capture network traffic with Wireshark, identify protocols, scan a network with Nmap, and document findings.',
          },
        },
        {
          id: 'linux-security',
          title: 'Linux & OS Security',
          description: 'Master Linux administration with a security focus.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Linux file permissions and ownership',
            'User management and sudo',
            'SSH hardening and key-based auth',
            'Firewall configuration (iptables/ufw)',
            'Log analysis (/var/log, journalctl)',
            'Process monitoring and management',
            'SELinux/AppArmor basics',
            'System hardening (CIS benchmarks)',
          ],
          resources: [
            { title: 'Linux for Ethical Hackers - TCM Security', url: 'https://www.youtube.com/watch?v=U1w4T03B30I', type: 'video' },
            { title: 'OverTheWire: Bandit (Linux Challenges)', url: 'https://overthewire.org/wargames/bandit/', type: 'course' },
            { title: 'Linux Hardening Guide - NIST', url: 'https://www.cisecurity.org/cis-benchmarks', type: 'docs' },
          ],
          project: {
            title: 'Hardened Linux Server',
            description: 'Set up a Linux server and harden it: disable root SSH, configure firewall, set up fail2ban, enable audit logging, and run a CIS benchmark scan.',
          },
        },
        {
          id: 'security-fundamentals',
          title: 'Security Concepts & CIA Triad',
          description: 'Learn core security principles, threat modeling, and the security mindset.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'CIA Triad (Confidentiality, Integrity, Availability)',
            'Authentication, Authorization, Accounting (AAA)',
            'Threat modeling (STRIDE, DREAD)',
            'Risk assessment and management',
            'Security policies and compliance',
            'Defense in depth strategy',
            'Common vulnerability types (OWASP Top 10)',
            'Security frameworks (NIST, ISO 27001)',
          ],
          resources: [
            { title: 'CompTIA Security+ Full Course - Professor Messer', url: 'https://www.youtube.com/playlist?list=PLG49S3nxzAnkL2full7Y0125nt1riKlGz0', type: 'video' },
            { title: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/', type: 'docs' },
            { title: 'NIST Cybersecurity Framework', url: 'https://www.nist.gov/cyberframework', type: 'docs' },
          ],
          project: {
            title: 'Threat Model Document',
            description: 'Perform threat modeling on a sample web application using STRIDE. Document threats, assess risks, and propose mitigations.',
          },
        },
      ],
    },
    {
      id: 'ethical-hacking',
      title: 'Ethical Hacking & Pentesting',
      description: 'Learn offensive security techniques used by ethical hackers and penetration testers.',
      timeEstimate: '6-7 weeks',
      color: 'lime',
      topics: [
        {
          id: 'reconnaissance',
          title: 'Reconnaissance & OSINT',
          description: 'Gather intelligence about targets using open-source information.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Passive vs active reconnaissance',
            'OSINT tools and techniques',
            'DNS enumeration and subdomain discovery',
            'Google dorking and search operators',
            'Social engineering basics',
            'Metadata analysis',
            'Shodan and Censys for device discovery',
            'Footprinting and information gathering',
          ],
          resources: [
            { title: 'OSINT Fundamentals - TCM Security', url: 'https://www.youtube.com/watch?v=qwA6MmbeGNo', type: 'video' },
            { title: 'OSINT Framework', url: 'https://osintframework.com/', type: 'docs' },
            { title: 'Google Hacking Database', url: 'https://www.exploit-db.com/google-hacking-database', type: 'article' },
          ],
          project: {
            title: 'OSINT Report',
            description: 'Perform OSINT on a target domain (with permission). Enumerate subdomains, find exposed services, discover email formats, and compile a report.',
          },
        },
        {
          id: 'web-exploitation',
          title: 'Web Application Exploitation',
          description: 'Find and exploit vulnerabilities in web applications.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'SQL Injection (Union, Blind, Error-based)',
            'Cross-Site Scripting (Reflected, Stored, DOM)',
            'Cross-Site Request Forgery (CSRF)',
            'Server-Side Request Forgery (SSRF)',
            'Insecure Direct Object References (IDOR)',
            'Authentication and session attacks',
            'File upload vulnerabilities',
            'Command injection',
            'Burp Suite for web testing',
          ],
          resources: [
            { title: 'Web Hacking 101 - TCM Security', url: 'https://www.youtube.com/watch?v=2_lswM1S264', type: 'video' },
            { title: 'PortSwigger Web Security Academy', url: 'https://portswigger.net/web-security', type: 'course' },
            { title: 'OWASP Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/', type: 'docs' },
            { title: 'TryHackMe Web Fundamentals', url: 'https://tryhackme.com/paths', type: 'course' },
          ],
          project: {
            title: 'Web App Pentest Report',
            description: 'Exploit vulnerabilities in DVWA or Juice Shop. Document each finding with proof-of-concept, severity rating, and remediation advice.',
          },
        },
        {
          id: 'network-exploitation',
          title: 'Network Exploitation',
          description: 'Exploit network services and escalate privileges on compromised systems.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Service enumeration and vulnerability scanning',
            'Metasploit framework',
            'Password attacks (brute force, spraying, cracking)',
            'Privilege escalation (Linux and Windows)',
            'Lateral movement techniques',
            'Active Directory attacks basics',
            'Post-exploitation and persistence',
            'Pivoting and tunneling',
          ],
          resources: [
            { title: 'Ethical Hacking Full Course - TCM Security', url: 'https://www.youtube.com/watch?v=3FNYvj2U0HM', type: 'video' },
            { title: 'HackTheBox Academy', url: 'https://academy.hackthebox.com/', type: 'course' },
            { title: 'TryHackMe - Complete Beginner Path', url: 'https://tryhackme.com/path/outline/beginner', type: 'course' },
            { title: 'GTFOBins (Linux Privesc)', url: 'https://gtfobins.github.io/', type: 'docs' },
          ],
          project: {
            title: 'CTF Challenge Completion',
            description: 'Complete 10+ machines on TryHackMe or HackTheBox. Document your methodology: recon, exploitation, privilege escalation, and flags captured.',
          },
        },
      ],
    },
    {
      id: 'defensive-security',
      title: 'Defensive Security',
      description: 'Learn to detect, analyze, and respond to security threats.',
      timeEstimate: '5-6 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'soc-operations',
          title: 'SOC Operations & SIEM',
          description: 'Work as a security analyst — monitor alerts, investigate incidents, and use SIEM tools.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Security Operations Center (SOC) workflow',
            'SIEM concepts (Splunk, Elastic SIEM)',
            'Log analysis and correlation',
            'Alert triage and investigation',
            'Indicator of Compromise (IoC)',
            'MITRE ATT&CK framework',
            'Sigma rules for detection',
            'Incident classification and escalation',
          ],
          resources: [
            { title: 'SOC Analyst Course - TCM Security', url: 'https://www.youtube.com/watch?v=uHy3oM7NNoE', type: 'video' },
            { title: 'Splunk Free Training', url: 'https://www.splunk.com/en_us/training/free-courses.html', type: 'course' },
            { title: 'MITRE ATT&CK', url: 'https://attack.mitre.org/', type: 'docs' },
            { title: 'LetsDefend SOC Training', url: 'https://letsdefend.io/', type: 'course' },
          ],
          project: {
            title: 'SIEM Lab Setup',
            description: 'Set up Elastic SIEM, ingest logs from multiple sources, create detection rules, investigate simulated attacks, and write incident reports.',
          },
        },
        {
          id: 'malware-analysis',
          title: 'Malware Analysis Basics',
          description: 'Analyze malicious software to understand how it works and how to detect it.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Types of malware (viruses, trojans, ransomware, RATs)',
            'Static analysis (strings, hashes, PE headers)',
            'Dynamic analysis (sandboxing, behavior monitoring)',
            'Setting up analysis environments safely',
            'YARA rules for detection',
            'Reverse engineering basics',
            'Malware persistence mechanisms',
            'Indicators of Compromise extraction',
          ],
          resources: [
            { title: 'Malware Analysis - TCM Security', url: 'https://www.youtube.com/watch?v=qA0YcYMRWyI', type: 'video' },
            { title: 'ANY.RUN Malware Sandbox', url: 'https://any.run/', type: 'docs' },
            { title: 'Malware Unicorn Workshops', url: 'https://malwareunicorn.org/', type: 'course' },
          ],
          project: {
            title: 'Malware Analysis Report',
            description: 'Analyze malware samples in a sandbox. Perform static and dynamic analysis, extract IoCs, write YARA rules, and produce a detailed report.',
          },
        },
        {
          id: 'incident-response',
          title: 'Incident Response & Forensics',
          description: 'Respond to security breaches and perform digital forensics.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Incident response lifecycle (NIST/SANS)',
            'Evidence preservation and chain of custody',
            'Memory forensics (Volatility)',
            'Disk forensics basics',
            'Network forensics (packet captures)',
            'Timeline analysis',
            'Root cause analysis',
            'Incident documentation and reporting',
          ],
          resources: [
            { title: 'Digital Forensics - 13Cubed', url: 'https://www.youtube.com/c/13Cubed', type: 'video' },
            { title: 'SANS Incident Response', url: 'https://www.sans.org/white-papers/33901/', type: 'article' },
            { title: 'Volatility Documentation', url: 'https://volatility3.readthedocs.io/', type: 'docs' },
            { title: 'DFIR Training Resources', url: 'https://www.dfir.training/', type: 'course' },
          ],
          project: {
            title: 'Incident Response Exercise',
            description: 'Respond to a simulated breach: collect evidence, analyze memory dumps, build a timeline, identify the attack vector, and write a post-incident report.',
          },
        },
      ],
    },
    {
      id: 'specialized',
      title: 'Specialized Security',
      description: 'Deep dive into cloud security, application security, or red teaming.',
      timeEstimate: '4-5 weeks',
      color: 'orange',
      topics: [
        {
          id: 'cloud-security',
          title: 'Cloud Security',
          description: 'Secure cloud infrastructure and detect misconfigurations.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'AWS/Azure/GCP security services',
            'IAM misconfigurations and attacks',
            'S3 bucket security and enumeration',
            'Cloud-native security tools',
            'Container security (Docker, K8s)',
            'Serverless security considerations',
            'Cloud compliance (CIS Benchmarks)',
            'Cloud pentesting methodology',
          ],
          resources: [
            { title: 'Cloud Security - freeCodeCamp', url: 'https://www.youtube.com/watch?v=_cxr5VSYvbs', type: 'video' },
            { title: 'AWS Security Specialty Resources', url: 'https://www.youtube.com/watch?v=Ia-UEYYR44s', type: 'video' },
            { title: 'Cloud Security Alliance', url: 'https://cloudsecurityalliance.org/', type: 'docs' },
            { title: 'flaws.cloud (AWS CTF)', url: 'http://flaws.cloud/', type: 'course' },
          ],
          project: {
            title: 'Cloud Security Audit',
            description: 'Audit an AWS account for misconfigurations: check IAM policies, S3 permissions, security groups, encryption, and logging. Use ScoutSuite or Prowler.',
          },
        },
        {
          id: 'appsec',
          title: 'Application Security (AppSec)',
          description: 'Integrate security into the software development lifecycle.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Secure SDLC (DevSecOps)',
            'SAST and DAST tools',
            'Dependency vulnerability scanning (SCA)',
            'Code review for security',
            'Threat modeling for developers',
            'API security testing',
            'Security in CI/CD pipelines',
            'Bug bounty program basics',
          ],
          resources: [
            { title: 'DevSecOps Tutorial - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=nrhxNNH5lt0', type: 'video' },
            { title: 'OWASP DevSecOps Guide', url: 'https://owasp.org/www-project-devsecops-guideline/', type: 'docs' },
            { title: 'Snyk Learn', url: 'https://learn.snyk.io/', type: 'course' },
          ],
          project: {
            title: 'Secure CI/CD Pipeline',
            description: 'Integrate security into a CI/CD pipeline: SAST scanning, dependency checks, container scanning, DAST testing, and automated security gates.',
          },
        },
        {
          id: 'cryptography',
          title: 'Cryptography Essentials',
          description: 'Understand encryption, hashing, and PKI used to protect data.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Symmetric encryption (AES, ChaCha20)',
            'Asymmetric encryption (RSA, ECC)',
            'Hashing algorithms (SHA-256, bcrypt)',
            'Digital signatures and certificates',
            'PKI and certificate authorities',
            'TLS/SSL handshake',
            'Key exchange (Diffie-Hellman)',
            'Common crypto pitfalls and attacks',
          ],
          resources: [
            { title: 'Cryptography Explained - Computerphile', url: 'https://www.youtube.com/watch?v=GSIDS_lvRv4', type: 'video' },
            { title: 'Crypto101 (Free Book)', url: 'https://www.crypto101.io/', type: 'article' },
            { title: 'CryptoHack (Interactive Challenges)', url: 'https://cryptohack.org/', type: 'course' },
          ],
          project: {
            title: 'Encryption Implementation',
            description: 'Implement a secure messaging system: generate key pairs, encrypt/decrypt messages, sign and verify, and set up mutual TLS between services.',
          },
        },
      ],
    },
    {
      id: 'career-certs',
      title: 'Career & Certifications',
      description: 'Prepare for industry certifications and build your security career.',
      timeEstimate: '4-5 weeks',
      color: 'purple',
      topics: [
        {
          id: 'certifications',
          title: 'Security Certifications Path',
          description: 'Prepare for industry-recognized certifications that validate your skills.',
          timeEstimate: '14-21 days',
          whatToLearn: [
            'CompTIA Security+ (entry-level, highly valued)',
            'CEH (Certified Ethical Hacker) overview',
            'OSCP (Offensive Security Certified Professional)',
            'AWS Security Specialty',
            'CISSP (for experienced professionals)',
            'Study strategies and resources',
            'Practice exams and labs',
            'Continuing education requirements',
          ],
          resources: [
            { title: 'CompTIA Security+ Full Course - Professor Messer', url: 'https://www.youtube.com/playlist?list=PLG49S3nxzAnkL2full7Y0125nt1riKlGz0', type: 'video' },
            { title: 'TryHackMe OSCP Prep', url: 'https://tryhackme.com/path/outline/pentesting', type: 'course' },
            { title: 'CompTIA Security+ Objectives', url: 'https://www.comptia.org/certifications/security', type: 'docs' },
            { title: 'OSCP Prep - TCM Security', url: 'https://www.youtube.com/watch?v=qlK174d_uu8', type: 'video' },
          ],
          project: {
            title: 'Certification Study Plan',
            description: 'Create a 90-day study plan for Security+: cover all domains, complete practice exams (80%+ score), and set up home labs for hands-on practice.',
          },
        },
        {
          id: 'portfolio-ctf',
          title: 'Portfolio & CTF Practice',
          description: 'Build a security portfolio and sharpen skills through CTF competitions.',
          timeEstimate: '10-14 days',
          whatToLearn: [
            'CTF competition types (Jeopardy, Attack/Defense)',
            'Popular platforms (HTB, THM, PicoCTF, CTFtime)',
            'Writing quality write-ups',
            'Building a security blog',
            'Contributing to open-source security tools',
            'Bug bounty hunting (HackerOne, Bugcrowd)',
            'Networking in the security community',
            'Resume and LinkedIn for security roles',
          ],
          resources: [
            { title: 'CTF for Beginners - John Hammond', url: 'https://www.youtube.com/watch?v=ca_Bkwb9QpY', type: 'video' },
            { title: 'Bug Bounty Hunting Tutorial - InsiderPhD', url: 'https://www.youtube.com/watch?v=yCUQBc2rY9Y', type: 'video' },
            { title: 'PicoCTF (Beginner CTF)', url: 'https://picoctf.org/', type: 'course' },
            { title: 'HackTheBox Starting Point', url: 'https://www.hackthebox.com/starting-point', type: 'course' },
            { title: 'Bug Bounty Hunter - HackerOne', url: 'https://www.hackerone.com/hackers', type: 'docs' },
            { title: 'CTF Field Guide', url: 'https://trailofbits.github.io/ctf/', type: 'article' },
          ],
          project: {
            title: 'Security Portfolio',
            description: 'Complete 20+ CTF challenges, write detailed write-ups for 5, submit a bug bounty report, and create a portfolio site showcasing your security work.',
          },
        },
      ],
    },
  ],
};
