import { Roadmap } from '@/types/roadmap';

export const devopsEngineerRoadmap: Roadmap = {
  slug: 'devops-engineer',
  title: 'DevOps Engineer',
  description: 'Master CI/CD, containers, cloud infrastructure, monitoring, and infrastructure as code to bridge development and operations.',
  icon: 'Cloud',
  accent: '#A8F0E6',
  totalTime: '7-9 months',
  languages: ['Bash', 'Python', 'Go', 'HCL (Terraform)'],
  variants: [
    { id: 'aws', label: 'AWS' },
    { id: 'azure', label: 'Azure' },
    { id: 'gcp', label: 'GCP' },
  ],
  relatedRoadmaps: [
    { slug: 'backend-developer', relation: 'prerequisite', description: 'Backend knowledge helps understand what you are deploying' },
    { slug: 'cybersecurity', relation: 'shared-topics', description: 'Shares networking, Linux, and cloud security concepts' },
    { slug: 'full-stack-developer', relation: 'shared-topics', description: 'CI/CD and Docker topics overlap with full-stack deployment' },
  ],
  stages: [
    {
      id: 'foundations',
      title: 'Linux & Networking',
      description: 'Master Linux system administration and networking fundamentals.',
      timeEstimate: '4-5 weeks',
      color: 'green',
      topics: [
        {
          id: 'linux-fundamentals',
          title: 'Linux Fundamentals',
          description: 'Master Linux command line, file systems, and system administration.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'File system hierarchy and navigation',
            'File permissions (chmod, chown, ACLs)',
            'Process management (ps, top, kill, systemd)',
            'Package managers (apt, yum, dnf)',
            'Text processing (grep, sed, awk, cut)',
            'Shell scripting (bash)',
            'Cron jobs and scheduling',
            'User and group management',
            'Disk management and mounting',
          ],
          resources: [
            { title: 'Linux Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=sWbUDq4S6Y8', type: 'video' },
            { title: 'Linux Journey (Interactive)', url: 'https://linuxjourney.com/', type: 'course' },
            { title: 'The Linux Command Line (Free Book)', url: 'https://linuxcommand.org/tlcl.php', type: 'article' },
            { title: 'Linux Man Pages', url: 'https://man7.org/linux/man-pages/', type: 'docs' },
          ],
          project: {
            title: 'Server Setup Script',
            description: 'Write a bash script that automates setting up a new Linux server: install packages, configure users, set up firewall, and harden SSH.',
          },
        },
        {
          id: 'networking',
          title: 'Networking & Protocols',
          description: 'Understand networking concepts essential for DevOps and cloud.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'OSI model and TCP/IP stack',
            'DNS, DHCP, and HTTP/HTTPS',
            'IP addressing, subnets, and CIDR',
            'Load balancers and reverse proxies',
            'Firewalls and security groups',
            'SSL/TLS and certificates',
            'VPNs and network tunneling',
            'Network troubleshooting tools (ping, traceroute, netstat, tcpdump)',
          ],
          resources: [
            { title: 'Networking Fundamentals - NetworkChuck', url: 'https://www.youtube.com/playlist?list=PLIhvC56v63IJVXv0GJcl9vO5Z6znCVb1P', type: 'video' },
            { title: 'Computer Networking - Kurose & Ross (Lectures)', url: 'https://www.youtube.com/playlist?list=PLm556dMNleHc1MWN5BX9B2XkwkNE2Djiu', type: 'video' },
            { title: 'Cloudflare Learning Center', url: 'https://www.cloudflare.com/learning/', type: 'article' },
          ],
          project: {
            title: 'Network Monitoring Dashboard',
            description: 'Set up a monitoring script that checks server health, port availability, DNS resolution, and SSL certificate expiry. Send alerts on failure.',
          },
        },
        {
          id: 'git-advanced',
          title: 'Git Advanced & Branching Strategies',
          description: 'Master advanced Git workflows used in production teams.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Git flow vs trunk-based development',
            'Rebasing, cherry-picking, and bisect',
            'Git hooks for automation',
            'Monorepo management',
            'Conventional commits',
            'Tagging and releases',
            'Git LFS for large files',
          ],
          resources: [
            { title: 'Advanced Git Tutorial - Atlassian', url: 'https://www.atlassian.com/git/tutorials/advanced-overview', type: 'article' },
            { title: 'Git Branching Strategies - DevOps Toolkit', url: 'https://www.youtube.com/watch?v=U_IFGpJDbeU', type: 'video' },
            { title: 'Conventional Commits', url: 'https://www.conventionalcommits.org/', type: 'docs' },
          ],
          project: {
            title: 'Git Workflow for a Team',
            description: 'Set up a repo with branch protection, PR templates, automated linting on commit, conventional commits, and automated changelog generation.',
          },
        },
      ],
    },
    {
      id: 'containers',
      title: 'Containers & Orchestration',
      description: 'Master Docker and Kubernetes for containerized deployments.',
      timeEstimate: '5-6 weeks',
      color: 'lime',
      topics: [
        {
          id: 'docker-mastery',
          title: 'Docker Mastery',
          description: 'Build, ship, and run applications in Docker containers.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Container concepts (namespaces, cgroups)',
            'Dockerfile best practices',
            'Multi-stage builds for production',
            'Docker Compose for multi-service apps',
            'Networking (bridge, host, overlay)',
            'Volumes and persistent storage',
            'Docker security scanning',
            'Private registries (ECR, GHCR)',
            'BuildKit and caching optimization',
          ],
          resources: [
            { title: 'Docker Deep Dive - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=pg19Z8LL06w', type: 'video' },
            { title: 'Docker Official Getting Started', url: 'https://docs.docker.com/get-started/', type: 'docs' },
            { title: 'Dockerfile Best Practices', url: 'https://docs.docker.com/build/building/best-practices/', type: 'docs' },
            { title: 'Docker Security - Snyk', url: 'https://snyk.io/learn/docker-security/', type: 'article' },
          ],
          project: {
            title: 'Dockerized Microservices',
            description: 'Containerize a multi-service application (API + database + cache + worker) with Docker Compose. Implement health checks and proper networking.',
          },
        },
        {
          id: 'kubernetes-fundamentals',
          title: 'Kubernetes Fundamentals',
          description: 'Deploy and manage containerized applications with Kubernetes.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Kubernetes architecture (control plane, nodes)',
            'Pods, Deployments, Services',
            'ConfigMaps and Secrets',
            'Ingress controllers and routing',
            'Persistent Volumes and Storage Classes',
            'Namespaces and RBAC',
            'Horizontal Pod Autoscaling',
            'Helm charts for templating',
            'kubectl mastery',
          ],
          resources: [
            { title: 'Kubernetes Course - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=X48VuDVv0do', type: 'video' },
            { title: 'Kubernetes Official Tutorials', url: 'https://kubernetes.io/docs/tutorials/', type: 'docs' },
            { title: 'KillerCoda Interactive Labs', url: 'https://killercoda.com/playgrounds/scenario/kubernetes', type: 'course' },
            { title: 'Helm Official Docs', url: 'https://helm.sh/docs/', type: 'docs' },
          ],
          project: {
            title: 'K8s Cluster Deployment',
            description: 'Deploy your microservices to a Kubernetes cluster (Minikube/Kind). Configure services, ingress, secrets, health checks, and auto-scaling.',
          },
        },
        {
          id: 'kubernetes-advanced',
          title: 'Kubernetes Advanced',
          description: 'Advanced Kubernetes patterns for production workloads.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'StatefulSets for databases',
            'DaemonSets and Jobs/CronJobs',
            'Network policies',
            'Service mesh concepts (Istio/Linkerd)',
            'Custom Resource Definitions (CRDs)',
            'GitOps with ArgoCD/Flux',
            'Cluster monitoring (Prometheus + Grafana)',
            'Disaster recovery and backup',
          ],
          resources: [
            { title: 'ArgoCD Tutorial - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=MeU5_k9ssrs', type: 'video' },
            { title: 'Kubernetes Patterns (Book)', url: 'https://www.youtube.com/watch?v=GhZi4DxaxxE', type: 'video' },
            { title: 'ArgoCD Documentation', url: 'https://argo-cd.readthedocs.io/en/stable/', type: 'docs' },
          ],
          project: {
            title: 'GitOps Pipeline',
            description: 'Set up GitOps with ArgoCD: auto-deploy from Git, handle rollbacks, implement canary deployments, and monitor cluster health.',
          },
        },
      ],
    },
    {
      id: 'ci-cd',
      title: 'CI/CD & Automation',
      description: 'Build automated pipelines for testing, building, and deploying applications.',
      timeEstimate: '4-5 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'ci-cd-pipelines',
          title: 'CI/CD Pipelines',
          description: 'Design and implement continuous integration and deployment pipelines.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'CI/CD concepts and benefits',
            'GitHub Actions (workflows, jobs, steps)',
            'Jenkins pipeline scripting',
            'GitLab CI/CD configuration',
            'Pipeline stages (build, test, deploy)',
            'Artifact management',
            'Environment promotion (dev → staging → prod)',
            'Secrets management in CI',
            'Parallel and matrix builds',
          ],
          resources: [
            { title: 'GitHub Actions Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=R8_veQiYBjI', type: 'video' },
            { title: 'GitHub Actions Documentation', url: 'https://docs.github.com/en/actions', type: 'docs' },
            { title: 'Jenkins Tutorial - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=7KCS70sCoK0', type: 'video' },
            { title: 'CI/CD Best Practices - GitLab', url: 'https://docs.gitlab.com/ee/ci/', type: 'docs' },
          ],
          project: {
            title: 'Production CI/CD Pipeline',
            description: 'Build a complete pipeline: lint, test, build Docker image, push to registry, deploy to staging automatically, and promote to production on approval.',
          },
        },
        {
          id: 'infrastructure-as-code',
          title: 'Infrastructure as Code (Terraform)',
          description: 'Provision and manage cloud infrastructure with code.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'IaC concepts and benefits',
            'Terraform HCL syntax',
            'Providers, resources, and data sources',
            'State management (remote backends)',
            'Modules for reusability',
            'Terraform workspaces',
            'Import existing infrastructure',
            'Terragrunt for DRY configs',
            'Policy as code (Sentinel/OPA)',
          ],
          resources: [
            { title: 'Terraform Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=SLB_c_ayRMo', type: 'video' },
            { title: 'Terraform Official Tutorials', url: 'https://developer.hashicorp.com/terraform/tutorials', type: 'course' },
            { title: 'Terraform Documentation', url: 'https://developer.hashicorp.com/terraform/docs', type: 'docs' },
            { title: 'Terraform Best Practices', url: 'https://www.youtube.com/watch?v=gxPykhPxRW0', type: 'video' },
          ],
          project: {
            title: 'Cloud Infrastructure with Terraform',
            description: 'Provision a complete cloud environment: VPC, subnets, security groups, EC2/EKS, RDS, S3, and load balancer — all defined in Terraform.',
          },
        },
        {
          id: 'configuration-management',
          title: 'Configuration Management (Ansible)',
          description: 'Automate server configuration and application deployment.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Ansible architecture (control node, inventory)',
            'Playbooks and tasks',
            'Roles for reusability',
            'Ansible Galaxy',
            'Variables, templates (Jinja2), and handlers',
            'Ansible Vault for secrets',
            'Idempotency principles',
          ],
          resources: [
            { title: 'Ansible Tutorial - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=1id6ERvfozo', type: 'video' },
            { title: 'Ansible Documentation', url: 'https://docs.ansible.com/', type: 'docs' },
            { title: 'Ansible for DevOps (Free Book)', url: 'https://www.ansiblefordevops.com/', type: 'article' },
          ],
          project: {
            title: 'Automated Server Provisioning',
            description: 'Write Ansible playbooks to provision and configure web servers: install packages, configure Nginx, deploy applications, and manage SSL certs.',
          },
        },
      ],
    },
    {
      id: 'cloud-platforms',
      title: 'Cloud Platforms',
      description: 'Master major cloud services and architect scalable solutions.',
      timeEstimate: '5-6 weeks',
      color: 'orange',
      topics: [
        {
          id: 'aws-core',
          title: 'AWS Core Services',
          description: 'Learn the most-used AWS services for compute, storage, and networking.',
          variant: 'aws',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'EC2 (instances, AMIs, security groups)',
            'S3 (storage, static hosting, lifecycle policies)',
            'VPC (subnets, route tables, NAT, peering)',
            'IAM (users, roles, policies)',
            'RDS and DynamoDB',
            'Lambda (serverless compute)',
            'ECS/EKS for containers',
            'CloudFront CDN',
            'Route 53 DNS',
          ],
          resources: [
            { title: 'AWS Certified Cloud Practitioner - freeCodeCamp', url: 'https://www.youtube.com/watch?v=SOTamWNgDKc', type: 'video' },
            { title: 'AWS Documentation', url: 'https://docs.aws.amazon.com/', type: 'docs' },
            { title: 'AWS Free Tier', url: 'https://aws.amazon.com/free/', type: 'docs' },
            { title: 'AWS Solutions Architect Path - Adrian Cantrill', url: 'https://www.youtube.com/c/AdrianCantrill', type: 'video' },
          ],
          project: {
            title: 'AWS 3-Tier Architecture',
            description: 'Deploy a 3-tier app on AWS: VPC with public/private subnets, ALB, EC2 Auto Scaling Group, RDS, and S3 for static assets.',
          },
        },
        {
          id: 'azure-core',
          title: 'Azure Core Services',
          description: 'Learn Microsoft Azure services for compute, storage, and enterprise cloud.',
          variant: 'azure',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Azure VMs and App Service',
            'Azure Storage (Blob, Files, Queues)',
            'Virtual Networks and NSGs',
            'Azure AD and RBAC',
            'Azure SQL and Cosmos DB',
            'Azure Functions (serverless)',
            'AKS (Azure Kubernetes Service)',
            'Azure DevOps integration',
          ],
          resources: [
            { title: 'Azure Fundamentals - freeCodeCamp', url: 'https://www.youtube.com/watch?v=NKEFWyqJ5XA', type: 'video' },
            { title: 'Azure Documentation', url: 'https://learn.microsoft.com/en-us/azure/', type: 'docs' },
            { title: 'Azure Free Account', url: 'https://azure.microsoft.com/en-us/free/', type: 'docs' },
            { title: 'Microsoft Learn - Azure Path', url: 'https://learn.microsoft.com/en-us/training/azure/', type: 'course' },
          ],
          project: {
            title: 'Azure 3-Tier Architecture',
            description: 'Deploy a 3-tier app on Azure: VNet, App Service, Azure SQL, and Blob Storage with proper RBAC and monitoring.',
          },
        },
        {
          id: 'gcp-core',
          title: 'GCP Core Services',
          description: 'Learn Google Cloud Platform services for compute, data, and AI/ML workloads.',
          variant: 'gcp',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Compute Engine and Cloud Run',
            'Cloud Storage and Cloud SQL',
            'VPC and firewall rules',
            'IAM and service accounts',
            'BigQuery for analytics',
            'Cloud Functions (serverless)',
            'GKE (Google Kubernetes Engine)',
            'Pub/Sub messaging',
          ],
          resources: [
            { title: 'Google Cloud Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=UGRDM86MBIQ', type: 'video' },
            { title: 'GCP Documentation', url: 'https://cloud.google.com/docs', type: 'docs' },
            { title: 'GCP Free Tier', url: 'https://cloud.google.com/free', type: 'docs' },
            { title: 'Google Cloud Skills Boost', url: 'https://www.cloudskillsboost.google/', type: 'course' },
          ],
          project: {
            title: 'GCP 3-Tier Architecture',
            description: 'Deploy a 3-tier app on GCP: VPC, Cloud Run or GKE, Cloud SQL, and Cloud Storage with proper IAM and monitoring.',
          },
        },
        {
          id: 'cloud-architecture',
          title: 'Cloud Architecture Patterns',
          description: 'Design scalable, fault-tolerant cloud architectures.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'High availability and fault tolerance',
            'Auto-scaling strategies',
            'Microservices on cloud',
            'Serverless architecture patterns',
            'Event-driven architecture (SQS, SNS, EventBridge)',
            'Multi-region deployments',
            'Cost optimization',
            'Well-Architected Framework',
          ],
          resources: [
            { title: 'AWS Well-Architected', url: 'https://aws.amazon.com/architecture/well-architected/', type: 'docs' },
            { title: 'Cloud Design Patterns - Azure', url: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/', type: 'docs' },
            { title: 'Serverless Architecture - Fireship', url: 'https://www.youtube.com/watch?v=W_VV2Fx32_Y', type: 'video' },
          ],
          project: {
            title: 'Serverless API',
            description: 'Build a serverless REST API with AWS Lambda, API Gateway, DynamoDB, and S3. Implement auth, rate limiting, and monitoring.',
          },
        },
        {
          id: 'cloud-security',
          title: 'Cloud Security & Compliance',
          description: 'Secure cloud infrastructure and implement compliance controls.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Shared responsibility model',
            'IAM best practices (least privilege)',
            'Network security (security groups, NACLs, WAF)',
            'Encryption at rest and in transit',
            'Secrets management (AWS Secrets Manager, Vault)',
            'Compliance frameworks (SOC2, HIPAA basics)',
            'Security auditing and CloudTrail',
            'Vulnerability scanning',
          ],
          resources: [
            { title: 'AWS Security Best Practices', url: 'https://docs.aws.amazon.com/security/', type: 'docs' },
            { title: 'HashiCorp Vault Tutorial', url: 'https://developer.hashicorp.com/vault/tutorials', type: 'course' },
            { title: 'Cloud Security - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=Ryo9wifnYb0', type: 'video' },
          ],
          project: {
            title: 'Security Hardened Infrastructure',
            description: 'Audit and harden your cloud setup: implement least-privilege IAM, encrypt all data, set up CloudTrail, configure WAF, and run vulnerability scans.',
          },
        },
      ],
    },
    {
      id: 'monitoring-sre',
      title: 'Monitoring & SRE',
      description: 'Implement observability, incident response, and reliability engineering.',
      timeEstimate: '4-5 weeks',
      color: 'purple',
      topics: [
        {
          id: 'monitoring-observability',
          title: 'Monitoring & Observability',
          description: 'Set up comprehensive monitoring with metrics, logs, and traces.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Three pillars: metrics, logs, traces',
            'Prometheus for metrics collection',
            'Grafana for dashboards and alerting',
            'ELK Stack / Loki for log aggregation',
            'Distributed tracing (Jaeger/Zipkin)',
            'Application Performance Monitoring (APM)',
            'SLIs, SLOs, and error budgets',
            'Alert design and on-call best practices',
          ],
          resources: [
            { title: 'Prometheus & Grafana - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=QoDqxm7ybLc', type: 'video' },
            { title: 'Prometheus Documentation', url: 'https://prometheus.io/docs/', type: 'docs' },
            { title: 'Grafana Tutorials', url: 'https://grafana.com/tutorials/', type: 'course' },
            { title: 'Google SRE Book (Free)', url: 'https://sre.google/sre-book/table-of-contents/', type: 'article' },
          ],
          project: {
            title: 'Full Observability Stack',
            description: 'Set up Prometheus + Grafana for metrics, Loki for logs, and Jaeger for traces. Create dashboards, configure alerts, and define SLOs.',
          },
        },
        {
          id: 'incident-management',
          title: 'Incident Management & SRE',
          description: 'Handle incidents effectively and build reliable systems.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Incident response process',
            'Runbooks and playbooks',
            'Postmortem culture (blameless)',
            'Chaos engineering (Chaos Monkey)',
            'Capacity planning',
            'Toil reduction automation',
            'On-call rotation best practices',
            'Communication during incidents',
          ],
          resources: [
            { title: 'Google SRE Book - Chapters on Incidents', url: 'https://sre.google/sre-book/managing-incidents/', type: 'article' },
            { title: 'Chaos Engineering - Principles', url: 'https://principlesofchaos.org/', type: 'article' },
            { title: 'PagerDuty Incident Response', url: 'https://response.pagerduty.com/', type: 'docs' },
          ],
          project: {
            title: 'Incident Response System',
            description: 'Create runbooks for common failures, implement health checks, set up PagerDuty/OpsGenie alerting, and run a chaos engineering experiment.',
          },
        },
        {
          id: 'capstone-devops',
          title: 'Capstone: Production Platform',
          description: 'Build a complete production-grade platform combining everything learned.',
          timeEstimate: '14-21 days',
          whatToLearn: [
            'Platform engineering concepts',
            'Developer experience (internal tools)',
            'End-to-end automation',
            'Multi-environment management',
            'Cost monitoring and optimization',
            'Documentation and knowledge sharing',
            'Team workflows and processes',
          ],
          resources: [
            { title: 'Platform Engineering - CNCF', url: 'https://www.youtube.com/watch?v=ghzsBm8vOms', type: 'video' },
            { title: 'DevOps Roadmap - roadmap.sh', url: 'https://roadmap.sh/devops', type: 'article' },
            { title: 'CNCF Landscape', url: 'https://landscape.cncf.io/', type: 'docs' },
          ],
          project: {
            title: 'Internal Developer Platform',
            description: 'Build a complete platform: Terraform for infra, K8s for orchestration, ArgoCD for GitOps, Prometheus/Grafana monitoring, and automated CI/CD pipelines.',
          },
        },
      ],
    },
  ],
};
