import { Roadmap } from '@/types/roadmap';

export const frontendDeveloperRoadmap: Roadmap = {
  slug: 'frontend-developer',
  title: 'Frontend Developer',
  description: 'Master HTML, CSS, JavaScript, React, and modern frontend tools to build beautiful, responsive web applications.',
  icon: 'Code',
  accent: '#D8CCFF',
  totalTime: '5-6 months',
  relatedRoadmaps: [
    { slug: 'full-stack-developer', relation: 'builds-on', description: 'Continue to full-stack by adding backend skills' },
    { slug: 'backend-developer', relation: 'shared-topics', description: 'Shares Git, deployment, and API concepts' },
    { slug: 'mobile-developer', relation: 'shared-topics', description: 'React Native reuses your React knowledge' },
  ],
  stages: [
    {
      id: 'foundations',
      title: 'Foundations',
      description: 'Build a solid base with HTML, CSS, and version control.',
      timeEstimate: '2-3 weeks',
      color: 'green',
      topics: [
        {
          id: 'html',
          title: 'HTML5',
          description: 'Structure web pages with semantic HTML elements.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Document structure (doctype, head, body)',
            'Semantic elements (header, nav, main, section, article, footer)',
            'Forms and input types',
            'Tables, lists, and media elements',
            'Accessibility basics (alt text, ARIA roles, landmarks)',
          ],
          resources: [
            { title: 'MDN HTML Guide', url: 'https://developer.mozilla.org/en-US/docs/Learn/HTML', type: 'docs' },
            { title: 'HTML Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=UB1O30fR-EE', type: 'video' },
            { title: 'web.dev Learn HTML', url: 'https://web.dev/learn/html', type: 'course' },
          ],
          project: {
            title: 'Personal Portfolio (HTML only)',
            description: 'Build a multi-page portfolio site using only semantic HTML. Include an about page, projects page, and contact form.',
          },
        },
        {
          id: 'css',
          title: 'CSS3 & Layouts',
          description: 'Style and lay out web pages with modern CSS.',
          timeEstimate: '7-10 days',
          whatToLearn: [
            'Selectors, specificity, and the cascade',
            'Box model, margin, padding, borders',
            'Flexbox for one-dimensional layouts',
            'CSS Grid for two-dimensional layouts',
            'Responsive design with media queries',
            'CSS variables (custom properties)',
            'Transitions and basic animations',
          ],
          resources: [
            { title: 'CSS Complete Guide - MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn/CSS', type: 'docs' },
            { title: 'Flexbox Froggy', url: 'https://flexboxfroggy.com/', type: 'course' },
            { title: 'Grid Garden', url: 'https://cssgridgarden.com/', type: 'course' },
          ],
          project: {
            title: 'Responsive Landing Page',
            description: 'Build a fully responsive landing page with a hero section, feature cards grid, testimonials, and footer using Flexbox and Grid.',
          },
        },
        {
          id: 'git',
          title: 'Git & GitHub',
          description: 'Track changes and collaborate with version control.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Git basics (init, add, commit, status, log)',
            'Branching and merging',
            'Remote repositories (push, pull, clone)',
            'Pull requests and code review workflow',
            'Resolving merge conflicts',
            '.gitignore and repository best practices',
          ],
          resources: [
            { title: 'Git Handbook - GitHub', url: 'https://guides.github.com/introduction/git-handbook/', type: 'docs' },
            { title: 'Git & GitHub for Beginners - freeCodeCamp', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', type: 'video' },
            { title: 'Learn Git Branching (Interactive)', url: 'https://learngitbranching.js.org/', type: 'course' },
          ],
          project: {
            title: 'Contribute to Open Source',
            description: 'Fork a beginner-friendly repo, create a branch, make a meaningful contribution, and submit a pull request.',
          },
        },
      ],
    },
    {
      id: 'javascript',
      title: 'Core JavaScript',
      description: 'Master the programming language of the web.',
      timeEstimate: '4-5 weeks',
      color: 'lime',
      topics: [
        {
          id: 'js-basics',
          title: 'JavaScript Fundamentals',
          description: 'Learn variables, data types, operators, and control flow.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Variables (let, const) and data types',
            'Operators and expressions',
            'Conditionals (if/else, switch, ternary)',
            'Loops (for, while, for...of, for...in)',
            'Functions (declarations, expressions, arrow)',
            'Scope and closures',
            'Template literals and destructuring',
          ],
          resources: [
            { title: 'JavaScript.info - Modern Tutorial', url: 'https://javascript.info/', type: 'docs' },
            { title: 'JavaScript Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg', type: 'video' },
            { title: 'Eloquent JavaScript (free book)', url: 'https://eloquentjavascript.net/', type: 'article' },
          ],
          project: {
            title: 'Quiz App',
            description: 'Build a multi-question quiz with score tracking, timer, and local high score storage.',
          },
        },
        {
          id: 'dom',
          title: 'DOM Manipulation',
          description: 'Interact with and modify web pages dynamically.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Selecting elements (querySelector, getElementById)',
            'Modifying content, attributes, and styles',
            'Event listeners and event delegation',
            'Creating and removing elements dynamically',
            'Traversing the DOM tree',
            'Forms and user input handling',
          ],
          resources: [
            { title: 'DOM Manipulation - MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents', type: 'docs' },
            { title: 'JavaScript DOM Course - Traversy', url: 'https://www.youtube.com/watch?v=0ik6X4DJKCc', type: 'video' },
            { title: 'DOM Enlightenment (free book)', url: 'http://domenlightenment.com/', type: 'article' },
          ],
          project: {
            title: 'Task Manager',
            description: 'Build a to-do app with add/edit/delete, drag-and-drop reorder, filters (all/active/completed), and localStorage persistence.',
          },
        },
        {
          id: 'async',
          title: 'Async JavaScript & APIs',
          description: 'Handle asynchronous operations and fetch external data.',
          timeEstimate: '6-7 days',
          whatToLearn: [
            'Callbacks and callback hell',
            'Promises (.then, .catch, .finally)',
            'async/await syntax',
            'Fetch API and HTTP methods',
            'Working with JSON data',
            'Error handling in async code',
            'Promise.all and Promise.race',
          ],
          resources: [
            { title: 'Async JavaScript - javascript.info', url: 'https://javascript.info/async', type: 'docs' },
            { title: 'Async JS Crash Course - Traversy', url: 'https://www.youtube.com/watch?v=PoRJizFvM7s', type: 'video' },
            { title: 'Public APIs List', url: 'https://github.com/public-apis/public-apis', type: 'article' },
          ],
          project: {
            title: 'Weather Dashboard',
            description: 'Build a weather app that fetches data from a public API, shows current conditions and 5-day forecast, with city search and geolocation.',
          },
        },
        {
          id: 'es6-plus',
          title: 'Modern ES6+ Features',
          description: 'Master modern JavaScript syntax and patterns.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Array methods (map, filter, reduce, find, some, every)',
            'Spread/rest operators',
            'Object shorthand and computed properties',
            'Modules (import/export)',
            'Optional chaining and nullish coalescing',
            'Sets and Maps',
            'Generators and iterators (basics)',
          ],
          resources: [
            { title: 'ES6 Features Overview', url: 'https://es6-features.org/', type: 'docs' },
            { title: 'JavaScript ES6 Tutorial - Net Ninja', url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gKfw25slm4CUDUcM_sXdml', type: 'video' },
            { title: 'Exploring JS (free book)', url: 'https://exploringjs.com/es6/', type: 'article' },
          ],
          project: {
            title: 'E-commerce Product Filter',
            description: 'Build a product listing page with search, multi-category filter, price range slider, and sort — using array methods exclusively.',
          },
        },
      ],
    },
    {
      id: 'react',
      title: 'React Ecosystem',
      description: 'Build modern UIs with the most popular frontend library.',
      timeEstimate: '5-6 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'react-basics',
          title: 'React Fundamentals',
          description: 'Components, JSX, props, and state management basics.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'JSX syntax and expressions',
            'Functional components',
            'Props and prop drilling',
            'useState for local state',
            'Conditional rendering',
            'Lists and keys',
            'Event handling in React',
          ],
          resources: [
            { title: 'React Official Docs (new)', url: 'https://react.dev/learn', type: 'docs' },
            { title: 'React Tutorial for Beginners - Codevolution', url: 'https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3', type: 'video' },
            { title: 'React Handbook - freeCodeCamp', url: 'https://www.freecodecamp.org/news/the-react-handbook-b71c27b0a795/', type: 'article' },
          ],
          project: {
            title: 'Expense Tracker',
            description: 'Build an expense tracker with add/delete transactions, category breakdown chart, monthly totals, and local state management.',
          },
        },
        {
          id: 'react-hooks',
          title: 'React Hooks Deep Dive',
          description: 'Master useEffect, useRef, useMemo, and custom hooks.',
          timeEstimate: '6-7 days',
          whatToLearn: [
            'useEffect for side effects and cleanup',
            'useRef for DOM access and persisted values',
            'useMemo and useCallback for optimization',
            'useReducer for complex state logic',
            'useContext for prop drilling avoidance',
            'Custom hooks (extraction and reuse patterns)',
            'Rules of hooks',
          ],
          resources: [
            { title: 'React Hooks - Official Docs', url: 'https://react.dev/reference/react/hooks', type: 'docs' },
            { title: 'React Hooks Tutorial - Codevolution', url: 'https://www.youtube.com/playlist?list=PLC3y8-rFHvwisvxhZ135pogtX7_Oe3Q3A', type: 'video' },
            { title: 'useHooks.com (recipes)', url: 'https://usehooks.com/', type: 'article' },
          ],
          project: {
            title: 'Movie Search App',
            description: 'Build a movie search app using OMDB API with debounced search (custom hook), favorites list (useReducer), and theme toggle (useContext).',
          },
        },
        {
          id: 'state-routing',
          title: 'State Management & Routing',
          description: 'Manage global state and handle navigation.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'React Router (routes, params, nested routes)',
            'Navigation guards and redirects',
            'Context API for global state',
            'Zustand or Redux Toolkit (pick one)',
            'When to use local vs global state',
            'URL state and search params',
          ],
          resources: [
            { title: 'React Router Docs', url: 'https://reactrouter.com/en/main/start/tutorial', type: 'docs' },
            { title: 'Zustand - Lightweight State', url: 'https://docs.pmnd.rs/zustand/getting-started/introduction', type: 'docs' },
            { title: 'Redux Toolkit Quick Start', url: 'https://redux-toolkit.js.org/tutorials/quick-start', type: 'docs' },
          ],
          project: {
            title: 'Blog Platform (Frontend)',
            description: 'Build a multi-page blog with React Router (home, post detail, category filter), global auth state, and dark mode toggle.',
          },
        },
        {
          id: 'styling-react',
          title: 'Styling in React',
          description: 'Modern approaches to styling React applications.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'CSS Modules for scoped styles',
            'Tailwind CSS utility-first approach',
            'Styled-components or Emotion (CSS-in-JS)',
            'Component libraries (shadcn/ui, Radix)',
            'Responsive design patterns in React',
            'Animation libraries (Framer Motion basics)',
          ],
          resources: [
            { title: 'Tailwind CSS Docs', url: 'https://tailwindcss.com/docs', type: 'docs' },
            { title: 'Tailwind in 100 Seconds - Fireship', url: 'https://www.youtube.com/watch?v=mr15Xzb1Ook', type: 'video' },
            { title: 'Framer Motion Docs', url: 'https://www.framer.com/motion/', type: 'docs' },
          ],
          project: {
            title: 'Component Library',
            description: 'Build a mini UI library with Button, Input, Modal, Toast, Card components — fully styled with Tailwind, with variants and dark mode.',
          },
        },
      ],
    },
    {
      id: 'advanced',
      title: 'Advanced Frontend',
      description: 'Level up with TypeScript, testing, and performance.',
      timeEstimate: '4-5 weeks',
      color: 'orange',
      topics: [
        {
          id: 'typescript',
          title: 'TypeScript',
          description: 'Add type safety to your JavaScript projects.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Basic types (string, number, boolean, arrays)',
            'Interfaces and type aliases',
            'Union types, intersection types, literals',
            'Generics (functions, components, hooks)',
            'Type narrowing and guards',
            'Utility types (Partial, Pick, Omit, Record)',
            'TypeScript with React (props, events, refs)',
          ],
          resources: [
            { title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/', type: 'docs' },
            { title: 'React TypeScript Cheatsheet', url: 'https://react-typescript-cheatsheet.netlify.app/', type: 'article' },
            { title: 'No BS TS - Jack Herrington', url: 'https://www.youtube.com/playlist?list=PLNqp92_EXZBJYFrpEzdO2EapvU0GOJ09n', type: 'video' },
          ],
          project: {
            title: 'Migrate a Project to TypeScript',
            description: 'Take your earlier React project and convert it to TypeScript. Add strict types to all components, hooks, and API calls.',
          },
        },
        {
          id: 'testing',
          title: 'Testing',
          description: 'Write reliable tests for your frontend code.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Unit testing with Vitest/Jest',
            'Component testing with React Testing Library',
            'Mocking APIs and modules',
            'Integration testing patterns',
            'End-to-end testing with Playwright (basics)',
            'Test-driven development workflow',
          ],
          resources: [
            { title: 'Testing Library Docs', url: 'https://testing-library.com/docs/react-testing-library/intro/', type: 'docs' },
            { title: 'Vitest Docs', url: 'https://vitest.dev/guide/', type: 'docs' },
            { title: 'Testing React Apps - Kent C. Dodds', url: 'https://kentcdodds.com/blog/common-mistakes-with-react-testing-library', type: 'article' },
          ],
          project: {
            title: 'Test Suite for Expense Tracker',
            description: 'Write comprehensive tests for your expense tracker: unit tests for calculations, component tests for UI interactions, and integration tests for flows.',
          },
        },
        {
          id: 'performance',
          title: 'Performance Optimization',
          description: 'Make your apps fast and efficient.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'React.memo, useMemo, useCallback (when to use)',
            'Code splitting and lazy loading',
            'Image optimization (formats, lazy load, srcset)',
            'Lighthouse audits and Core Web Vitals',
            'Bundle analysis and tree shaking',
            'Virtualization for long lists',
          ],
          resources: [
            { title: 'web.dev Performance', url: 'https://web.dev/explore/fast', type: 'docs' },
            { title: 'React Performance - Kent C. Dodds', url: 'https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render', type: 'article' },
            { title: 'Chrome DevTools Performance', url: 'https://developer.chrome.com/docs/devtools/performance/', type: 'docs' },
          ],
          project: {
            title: 'Performance Audit & Fix',
            description: 'Audit one of your apps with Lighthouse, fix all performance issues, achieve 90+ score across all categories, and document before/after.',
          },
        },
      ],
    },
    {
      id: 'frameworks',
      title: 'Frameworks & Deployment',
      description: 'Ship production apps with Next.js and modern tooling.',
      timeEstimate: '4-5 weeks',
      color: 'red',
      topics: [
        {
          id: 'nextjs',
          title: 'Next.js',
          description: 'The React framework for production applications.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'App Router and file-based routing',
            'Server Components vs Client Components',
            'Data fetching (server-side)',
            'Dynamic routes and layouts',
            'Metadata and SEO',
            'API routes and server actions',
            'Static generation and ISR',
          ],
          resources: [
            { title: 'Next.js Official Docs', url: 'https://nextjs.org/docs', type: 'docs' },
            { title: 'Next.js 14 Course - Codevolution', url: 'https://www.youtube.com/playlist?list=PLC3y8-rFHvwjOKd6gdf4QtV1uYNiQnruI', type: 'video' },
            { title: 'Next.js Learn (Official)', url: 'https://nextjs.org/learn', type: 'course' },
          ],
          project: {
            title: 'Full Blog with Next.js',
            description: 'Build a complete blog with MDX content, categories, search, dark mode, SEO metadata, and deployed to Vercel.',
          },
        },
        {
          id: 'deployment',
          title: 'Build Tools & Deployment',
          description: 'Ship your apps to production with modern tooling.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Vite as build tool',
            'Environment variables and configs',
            'Deploying to Vercel/Netlify/Firebase',
            'Custom domains and DNS',
            'CI/CD with GitHub Actions',
            'Monitoring and error tracking basics',
          ],
          resources: [
            { title: 'Vite Docs', url: 'https://vitejs.dev/guide/', type: 'docs' },
            { title: 'Vercel Deployment Guide', url: 'https://vercel.com/docs/deployments/overview', type: 'docs' },
            { title: 'GitHub Actions Docs', url: 'https://docs.github.com/en/actions', type: 'docs' },
          ],
          project: {
            title: 'Deploy with CI/CD',
            description: 'Set up a GitHub Actions pipeline that runs linting, tests, and auto-deploys your Next.js app to Vercel on push to main.',
          },
        },
        {
          id: 'portfolio',
          title: 'Portfolio & Job Readiness',
          description: 'Build your professional presence and apply.',
          timeEstimate: '5-7 days',
          whatToLearn: [
            'Building a developer portfolio site',
            'Writing project case studies',
            'GitHub profile optimization',
            'Technical resume best practices',
            'Contributing to open source',
            'Frontend interview preparation (basics)',
          ],
          resources: [
            { title: 'Developer Portfolio Tips', url: 'https://www.joshwcomeau.com/effective-portfolio/', type: 'article' },
            { title: 'GitHub Profile README Guide', url: 'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile', type: 'docs' },
            { title: 'Frontend Interview Handbook', url: 'https://www.frontendinterviewhandbook.com/', type: 'article' },
          ],
          project: {
            title: 'Ship Your Portfolio',
            description: 'Build and deploy your final portfolio showcasing 4-6 best projects with live demos, source code, tech stack, and case study write-ups.',
          },
        },
      ],
    },
  ],
};
