import { Roadmap } from '@/types/roadmap';

export const fullStackDeveloperRoadmap: Roadmap = {
  slug: 'full-stack-developer',
  title: 'Full Stack Developer',
  description: 'End-to-end web development: build frontends, backends, databases, and deploy production applications from scratch.',
  icon: 'Database',
  accent: '#FFB36B',
  totalTime: '8-10 months',
  stages: [
    {
      id: 'frontend-core',
      title: 'Frontend Core',
      description: 'Build interactive user interfaces with HTML, CSS, JavaScript, and React.',
      timeEstimate: '5-6 weeks',
      color: 'green',
      topics: [
        {
          id: 'html-css-responsive',
          title: 'HTML, CSS & Responsive Design',
          description: 'Build semantic, accessible, and responsive web pages from scratch.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Semantic HTML5 elements and accessibility',
            'CSS Flexbox and Grid for layouts',
            'Responsive design with media queries',
            'CSS custom properties and modern techniques',
            'Mobile-first design approach',
            'CSS frameworks overview (Tailwind CSS)',
          ],
          resources: [
            { title: 'HTML & CSS Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=a_iQb1lnAEQ', type: 'video' },
            { title: 'web.dev Learn CSS', url: 'https://web.dev/learn/css', type: 'course' },
            { title: 'Tailwind CSS Docs', url: 'https://tailwindcss.com/docs', type: 'docs' },
            { title: 'Kevin Powell - CSS King (YouTube)', url: 'https://www.youtube.com/@KevinPowell', type: 'video' },
          ],
          project: {
            title: 'Responsive Portfolio Site',
            description: 'Build a fully responsive personal portfolio with hero, projects grid, skills section, and contact form using only HTML and CSS.',
          },
        },
        {
          id: 'javascript-deep',
          title: 'JavaScript (Deep Dive)',
          description: 'Master JavaScript including ES6+, DOM manipulation, and async programming.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Variables, types, operators, and coercion',
            'Functions, closures, and the this keyword',
            'Array methods (map, filter, reduce, find)',
            'Destructuring, spread/rest, template literals',
            'DOM manipulation and event handling',
            'Async: callbacks, Promises, async/await',
            'Fetch API and working with JSON',
            'Error handling and debugging',
            'ES Modules (import/export)',
          ],
          resources: [
            { title: 'JavaScript.info - Complete Tutorial', url: 'https://javascript.info/', type: 'course' },
            { title: 'JavaScript Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg', type: 'video' },
            { title: 'Eloquent JavaScript (Free Book)', url: 'https://eloquentjavascript.net/', type: 'article' },
            { title: 'JavaScript30 - Wes Bos', url: 'https://javascript30.com/', type: 'course' },
          ],
          project: {
            title: 'Interactive Weather App',
            description: 'Build a weather app that fetches real data from an API, shows forecasts, handles loading/error states, and saves favorite cities to localStorage.',
          },
        },
        {
          id: 'react-fundamentals',
          title: 'React Fundamentals',
          description: 'Build modern UIs with React, components, state management, and hooks.',
          timeEstimate: '12-14 days',
          whatToLearn: [
            'Components and JSX',
            'Props and state',
            'Event handling in React',
            'useState, useEffect, useRef hooks',
            'Conditional rendering and lists',
            'Forms (controlled components)',
            'Context API for global state',
            'Custom hooks',
            'React Router for navigation',
            'Fetching data (useEffect + fetch / React Query)',
          ],
          resources: [
            { title: 'React Official Tutorial', url: 'https://react.dev/learn', type: 'docs' },
            { title: 'React Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=bMknfKXIFA8', type: 'video' },
            { title: 'React Hooks Explained - Fireship', url: 'https://www.youtube.com/watch?v=TNhaISOUy6Q', type: 'video' },
            { title: 'Full React Course - Dave Gray', url: 'https://www.youtube.com/watch?v=RVFAyFWO4go', type: 'video' },
          ],
          project: {
            title: 'Task Management Dashboard',
            description: 'Build a Kanban-style task board with drag and drop, multiple boards, task details modal, and local storage persistence.',
          },
        },
      ],
    },
    {
      id: 'backend-core',
      title: 'Backend Core',
      description: 'Build APIs, connect databases, and handle server-side logic.',
      timeEstimate: '5-6 weeks',
      color: 'lime',
      topics: [
        {
          id: 'nodejs-express',
          title: 'Node.js & Express',
          description: 'Build RESTful APIs with Node.js and Express framework.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Node.js event loop and async model',
            'Express routing and middleware',
            'Request parsing (body, params, query)',
            'Error handling middleware',
            'File uploads with Multer',
            'CORS configuration',
            'Environment variables with dotenv',
            'Express Router for modularity',
          ],
          resources: [
            { title: 'Node.js & Express Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=Oe421EPjeBE', type: 'video' },
            { title: 'Express.js Official Guide', url: 'https://expressjs.com/en/guide/routing.html', type: 'docs' },
            { title: 'REST API with Express - Traversy Media', url: 'https://www.youtube.com/watch?v=CnH3kAXSrmU', type: 'video' },
            { title: 'The Odin Project - Node.js', url: 'https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs', type: 'course' },
          ],
          project: {
            title: 'Notes API',
            description: 'Build a complete REST API for a notes app: CRUD operations, validation, error handling, and organized route structure.',
          },
        },
        {
          id: 'databases-fullstack',
          title: 'Databases (SQL + MongoDB)',
          description: 'Learn both relational and document databases for full-stack applications.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'PostgreSQL: tables, relations, queries, joins',
            'Database schema design and normalization',
            'MongoDB: documents, collections, CRUD',
            'Prisma ORM for type-safe database access',
            'Database migrations and seeding',
            'Indexing for performance',
            'Choosing SQL vs NoSQL for your use case',
          ],
          resources: [
            { title: 'SQL Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY', type: 'video' },
            { title: 'Prisma Getting Started', url: 'https://www.prisma.io/docs/getting-started', type: 'docs' },
            { title: 'MongoDB Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=-56x56UppqQ', type: 'video' },
            { title: 'SQLBolt - Interactive Lessons', url: 'https://sqlbolt.com/', type: 'course' },
          ],
          project: {
            title: 'E-commerce Database',
            description: 'Design and implement a database for an e-commerce store. Users, products, categories, orders, and reviews with Prisma.',
          },
        },
        {
          id: 'auth-fullstack',
          title: 'Authentication & Authorization',
          description: 'Implement secure user authentication for full-stack applications.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Password hashing (bcrypt)',
            'JWT tokens (access + refresh)',
            'Cookie-based sessions',
            'OAuth 2.0 / social login',
            'Protected routes (frontend + backend)',
            'Role-based access control',
            'Security headers and CSRF protection',
          ],
          resources: [
            { title: 'Auth from Scratch - Web Dev Simplified', url: 'https://www.youtube.com/watch?v=mbsmsi7l3r4', type: 'video' },
            { title: 'NextAuth.js / Auth.js Docs', url: 'https://authjs.dev/getting-started', type: 'docs' },
            { title: 'JWT Explained - Fireship', url: 'https://www.youtube.com/watch?v=UBUNrFtufWo', type: 'video' },
            { title: 'OWASP Security Cheatsheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', type: 'docs' },
          ],
          project: {
            title: 'Auth System with Social Login',
            description: 'Build a complete auth system: email/password signup, Google OAuth, JWT with refresh tokens, forgot password flow, and protected routes.',
          },
        },
      ],
    },
    {
      id: 'fullstack-framework',
      title: 'Full-Stack Framework',
      description: 'Build production apps with Next.js — the leading full-stack React framework.',
      timeEstimate: '4-5 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'nextjs-fundamentals',
          title: 'Next.js Fundamentals',
          description: 'Learn Next.js App Router, server components, and full-stack features.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'App Router and file-based routing',
            'Server Components vs Client Components',
            'Layouts, loading, and error boundaries',
            'Data fetching patterns (Server Components, Route Handlers)',
            'Static generation vs server-side rendering',
            'Image optimization and fonts',
            'Metadata and SEO',
            'Middleware and redirects',
          ],
          resources: [
            { title: 'Next.js Official Tutorial', url: 'https://nextjs.org/learn', type: 'course' },
            { title: 'Next.js 14 Full Course - JavaScript Mastery', url: 'https://www.youtube.com/watch?v=wm5gMKuwSYk', type: 'video' },
            { title: 'Next.js Docs - Getting Started', url: 'https://nextjs.org/docs', type: 'docs' },
            { title: 'Server Components Explained - Fireship', url: 'https://www.youtube.com/watch?v=VIwWgV3Lc6s', type: 'video' },
          ],
          project: {
            title: 'Blog with CMS',
            description: 'Build a blog with Next.js: MDX content, dynamic routes, categories, search, SEO metadata, and an admin panel for creating posts.',
          },
        },
        {
          id: 'nextjs-fullstack',
          title: 'Next.js Full-Stack Patterns',
          description: 'Build complete applications with Server Actions, API routes, and database integration.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Server Actions for form handling',
            'Route Handlers (API endpoints)',
            'Database integration (Prisma + Next.js)',
            'Authentication with Auth.js',
            'File uploads and storage',
            'Optimistic updates and revalidation',
            'Caching strategies',
            'Real-time features with streaming',
          ],
          resources: [
            { title: 'Full-Stack Next.js App - Vercel', url: 'https://nextjs.org/learn/dashboard-app', type: 'course' },
            { title: 'Next.js Server Actions - Lee Robinson', url: 'https://www.youtube.com/watch?v=dDpZfOQBMaU', type: 'video' },
            { title: 'Build a SaaS with Next.js - Code with Antonio', url: 'https://www.youtube.com/watch?v=pRybm9fI-Gs', type: 'video' },
          ],
          project: {
            title: 'Project Management App',
            description: 'Build a full-stack project management tool with workspaces, tasks, team members, real-time updates, and file attachments.',
          },
        },
        {
          id: 'state-data-fetching',
          title: 'State Management & Data Fetching',
          description: 'Manage complex application state and data fetching at scale.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'React Query / TanStack Query for server state',
            'Zustand for client state',
            'Optimistic updates',
            'Infinite scrolling and pagination',
            'Prefetching and background refetching',
            'Cache invalidation strategies',
            'Loading and error states',
          ],
          resources: [
            { title: 'React Query Crash Course - Codevolution', url: 'https://www.youtube.com/watch?v=VtWkSCZX0Ec', type: 'video' },
            { title: 'TanStack Query Docs', url: 'https://tanstack.com/query/latest/docs/react/overview', type: 'docs' },
            { title: 'Zustand Tutorial - Jack Herrington', url: 'https://www.youtube.com/watch?v=KEc0LLQjyfQ', type: 'video' },
          ],
          project: {
            title: 'Social Feed with Infinite Scroll',
            description: 'Build a social media feed with infinite scrolling, optimistic likes, real-time comment updates, and offline support.',
          },
        },
      ],
    },
    {
      id: 'testing-quality',
      title: 'Testing & Quality',
      description: 'Write reliable code with testing, TypeScript, and code quality tools.',
      timeEstimate: '3-4 weeks',
      color: 'orange',
      topics: [
        {
          id: 'typescript',
          title: 'TypeScript',
          description: 'Add type safety to your full-stack applications with TypeScript.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Types, interfaces, and type aliases',
            'Generics and utility types',
            'Union types, intersections, and narrowing',
            'Type inference and type guards',
            'Typing React components and hooks',
            'Typing Express routes and middleware',
            'Shared types between frontend and backend',
            'Zod for runtime validation with TypeScript',
          ],
          resources: [
            { title: 'TypeScript Full Course - freeCodeCamp', url: 'https://www.youtube.com/watch?v=30LWjhZzg50', type: 'video' },
            { title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/', type: 'docs' },
            { title: 'Total TypeScript Beginners Course (Free)', url: 'https://www.totaltypescript.com/tutorials/beginners-typescript', type: 'course' },
            { title: 'Zod Docs', url: 'https://zod.dev/', type: 'docs' },
          ],
          project: {
            title: 'Type-Safe API Layer',
            description: 'Refactor an existing project to TypeScript. Add shared types between frontend and backend, Zod validation on API inputs, and strict mode.',
          },
        },
        {
          id: 'testing-fullstack',
          title: 'Testing (Unit, Integration, E2E)',
          description: 'Write comprehensive tests for both frontend and backend code.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Testing pyramid (unit, integration, e2e)',
            'Jest/Vitest for unit testing',
            'React Testing Library for component tests',
            'Supertest for API testing',
            'Playwright/Cypress for end-to-end tests',
            'Mocking and test doubles',
            'Test coverage and CI integration',
            'Testing async code and APIs',
          ],
          resources: [
            { title: 'Testing JavaScript - Kent C. Dodds', url: 'https://www.youtube.com/watch?v=04BBgg8zgWo', type: 'video' },
            { title: 'React Testing Library Docs', url: 'https://testing-library.com/docs/react-testing-library/intro/', type: 'docs' },
            { title: 'Playwright Getting Started', url: 'https://playwright.dev/docs/intro', type: 'docs' },
            { title: 'Vitest Docs', url: 'https://vitest.dev/guide/', type: 'docs' },
          ],
          project: {
            title: 'Full Test Suite',
            description: 'Add comprehensive tests to your project management app: unit tests for utils, component tests for UI, API integration tests, and E2E flows.',
          },
        },
        {
          id: 'code-quality',
          title: 'Code Quality & DevTools',
          description: 'Maintain code quality with linting, formatting, and developer tooling.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'ESLint configuration and rules',
            'Prettier for consistent formatting',
            'Husky and lint-staged (pre-commit hooks)',
            'Conventional commits',
            'Monorepo basics (Turborepo)',
            'Performance profiling (Lighthouse, React DevTools)',
            'Bundle analysis and optimization',
          ],
          resources: [
            { title: 'ESLint + Prettier Setup - Traversy Media', url: 'https://www.youtube.com/watch?v=SydnKbGc7W8', type: 'video' },
            { title: 'Turborepo Docs', url: 'https://turbo.build/repo/docs', type: 'docs' },
            { title: 'Lighthouse Performance Audit', url: 'https://developer.chrome.com/docs/lighthouse/overview', type: 'docs' },
          ],
          project: {
            title: 'Development Workflow Setup',
            description: 'Set up a complete dev workflow: ESLint + Prettier, Husky pre-commit hooks, CI pipeline with tests, and automated deployments.',
          },
        },
      ],
    },
    {
      id: 'deployment-production',
      title: 'Deployment & Production',
      description: 'Ship your applications to production with CI/CD, monitoring, and best practices.',
      timeEstimate: '4-5 weeks',
      color: 'purple',
      topics: [
        {
          id: 'docker-fullstack',
          title: 'Docker & Containerization',
          description: 'Containerize full-stack applications for consistent environments.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Dockerfile for Node.js/Next.js apps',
            'Multi-stage builds for production',
            'Docker Compose for full-stack dev',
            'Networking between containers',
            'Volume mounts for development',
            'Environment variable management',
            'Container registries',
          ],
          resources: [
            { title: 'Docker for Developers - TechWorld with Nana', url: 'https://www.youtube.com/watch?v=pg19Z8LL06w', type: 'video' },
            { title: 'Dockerize Next.js', url: 'https://nextjs.org/docs/app/building-your-application/deploying#docker-image', type: 'docs' },
            { title: 'Docker Compose Docs', url: 'https://docs.docker.com/compose/', type: 'docs' },
          ],
          project: {
            title: 'Dockerized Full-Stack App',
            description: 'Containerize your Next.js app with PostgreSQL and Redis. Create separate dev and prod Docker Compose configs.',
          },
        },
        {
          id: 'cloud-deployment',
          title: 'Cloud Deployment & DevOps',
          description: 'Deploy and manage applications on cloud platforms.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Vercel for Next.js deployment',
            'Railway/Render for backend services',
            'Supabase/PlanetScale for managed databases',
            'Cloudflare for CDN and DNS',
            'GitHub Actions for CI/CD',
            'Environment management (dev/staging/prod)',
            'Database migrations in production',
            'Monitoring and alerting',
            'Cost optimization strategies',
          ],
          resources: [
            { title: 'Deploy Full-Stack App - Vercel Docs', url: 'https://vercel.com/docs/frameworks/nextjs', type: 'docs' },
            { title: 'Railway Deployment Guide', url: 'https://docs.railway.app/', type: 'docs' },
            { title: 'Supabase Quick Start', url: 'https://supabase.com/docs/guides/getting-started', type: 'docs' },
            { title: 'GitHub Actions for Next.js - Fireship', url: 'https://www.youtube.com/watch?v=eB0nUzAI7M8', type: 'video' },
          ],
          project: {
            title: 'Production Deployment Pipeline',
            description: 'Deploy your full-stack app: Next.js on Vercel, database on Supabase, CI/CD with GitHub Actions, custom domain, and uptime monitoring.',
          },
        },
        {
          id: 'performance-monitoring',
          title: 'Performance & Monitoring',
          description: 'Optimize application performance and set up production monitoring.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Core Web Vitals (LCP, FID, CLS)',
            'Image and font optimization',
            'Code splitting and lazy loading',
            'Database query optimization',
            'Caching strategies (Redis, CDN, ISR)',
            'Error tracking (Sentry)',
            'Application performance monitoring',
            'Logging best practices',
          ],
          resources: [
            { title: 'Web Performance - Google', url: 'https://web.dev/performance', type: 'docs' },
            { title: 'Next.js Performance Optimization', url: 'https://nextjs.org/docs/app/building-your-application/optimizing', type: 'docs' },
            { title: 'Sentry for Next.js', url: 'https://docs.sentry.io/platforms/javascript/guides/nextjs/', type: 'docs' },
            { title: 'Performance Tips - Theo', url: 'https://www.youtube.com/watch?v=SqVLqvsiAYQ', type: 'video' },
          ],
          project: {
            title: 'Performance Optimization Sprint',
            description: 'Audit your app with Lighthouse, optimize images/fonts/bundles, add Redis caching, set up Sentry error tracking, and achieve 90+ Lighthouse scores.',
          },
        },
        {
          id: 'capstone-saas',
          title: 'Capstone: SaaS Application',
          description: 'Build a complete SaaS product combining everything you\'ve learned.',
          timeEstimate: '14-21 days',
          whatToLearn: [
            'Product planning and feature scoping',
            'Database schema for multi-tenant SaaS',
            'Stripe integration for payments',
            'Email notifications (Resend/SendGrid)',
            'File storage (S3/Cloudflare R2)',
            'Admin dashboard and analytics',
            'Landing page and marketing site',
            'Launch checklist and go-live',
          ],
          resources: [
            { title: 'Build a SaaS - Code with Antonio', url: 'https://www.youtube.com/watch?v=pRybm9fI-Gs', type: 'video' },
            { title: 'Stripe Docs - Accept Payments', url: 'https://stripe.com/docs/payments/quickstart', type: 'docs' },
            { title: 'Resend Email API', url: 'https://resend.com/docs/introduction', type: 'docs' },
            { title: 'SaaS Starter Kit - Steven Tey', url: 'https://github.com/steven-tey/dub', type: 'article' },
          ],
          project: {
            title: 'SaaS MVP Launch',
            description: 'Build and launch a SaaS product: multi-tenant architecture, Stripe subscriptions, email onboarding, file uploads, admin dashboard, and a marketing landing page.',
          },
        },
      ],
    },
  ],
};
