import { Roadmap } from '@/types/roadmap';

export const mobileDeveloperRoadmap: Roadmap = {
  slug: 'mobile-developer',
  title: 'Mobile Developer',
  description: 'Build cross-platform mobile apps with React Native and Flutter — from UI design to app store deployment.',
  icon: 'Smartphone',
  accent: '#FFE066',
  totalTime: '6-8 months',
  languages: ['Dart (Flutter)', 'JavaScript (React Native)', 'Swift (iOS)', 'Kotlin (Android)'],
  variants: [
    { id: 'flutter', label: 'Flutter' },
    { id: 'react-native', label: 'React Native' },
  ],
  relatedRoadmaps: [
    { slug: 'frontend-developer', relation: 'prerequisite', description: 'React Native path requires JavaScript and React knowledge' },
    { slug: 'backend-developer', relation: 'shared-topics', description: 'API integration skills from backend are used heavily' },
    { slug: 'full-stack-developer', relation: 'shared-topics', description: 'Full-stack skills help build complete mobile + backend systems' },
  ],
  stages: [
    {
      id: 'foundations',
      title: 'Mobile Foundations',
      description: 'Understand mobile development landscape and set up your environment.',
      timeEstimate: '2-3 weeks',
      color: 'green',
      topics: [
        {
          id: 'mobile-landscape',
          title: 'Mobile Development Landscape',
          description: 'Understand native vs cross-platform, ecosystem choices, and development workflows.',
          timeEstimate: '2-3 days',
          whatToLearn: [
            'Native (Swift/Kotlin) vs Cross-platform (React Native/Flutter)',
            'iOS vs Android platform differences',
            'App architecture patterns (MVVM, Clean Architecture)',
            'Mobile development lifecycle',
            'App store guidelines (Apple & Google)',
            'Development environment setup',
          ],
          resources: [
            { title: 'Native vs Cross-Platform - Fireship', url: 'https://www.youtube.com/watch?v=bnYJRYFsrSw', type: 'video' },
            { title: 'React Native vs Flutter 2024', url: 'https://www.youtube.com/watch?v=X8ipUgXH6jw', type: 'video' },
            { title: 'Mobile App Architecture Guide', url: 'https://developer.android.com/topic/architecture', type: 'docs' },
          ],
          project: {
            title: 'Development Environment Setup',
            description: 'Set up React Native and Flutter dev environments. Run "Hello World" on both iOS simulator and Android emulator for each framework.',
          },
        },
        {
          id: 'dart-flutter-basics',
          title: 'Dart & Flutter Basics',
          description: 'Learn Dart programming language and Flutter widget system fundamentals.',
          variant: 'flutter',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Dart language basics (types, functions, classes)',
            'Null safety and async/await in Dart',
            'Flutter widget tree concept',
            'StatelessWidget vs StatefulWidget',
            'Material Design and Cupertino widgets',
            'Layout widgets (Column, Row, Stack, Container)',
            'Navigation and routing',
            'Hot reload development workflow',
          ],
          resources: [
            { title: 'Flutter Course for Beginners - freeCodeCamp', url: 'https://www.youtube.com/watch?v=VPvVD8t02U8', type: 'video' },
            { title: 'Flutter Official Codelabs', url: 'https://docs.flutter.dev/get-started/codelab', type: 'course' },
            { title: 'Dart Official Tour', url: 'https://dart.dev/language', type: 'docs' },
            { title: 'Flutter Widget Catalog', url: 'https://docs.flutter.dev/ui/widgets', type: 'docs' },
          ],
          project: {
            title: 'Profile Card App',
            description: 'Build a beautiful profile card app with Flutter using various layout widgets, custom themes, and navigation between screens.',
          },
        },
        {
          id: 'react-native-basics',
          title: 'React Native Basics',
          description: 'Build mobile UIs with React Native using your JavaScript/React knowledge.',
          variant: 'react-native',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'React Native CLI vs Expo',
            'Core components (View, Text, Image, ScrollView)',
            'Styling with StyleSheet (Flexbox)',
            'Navigation (React Navigation)',
            'Platform-specific code',
            'Handling touch events and gestures',
            'FlatList for performant lists',
            'Expo SDK features (camera, location)',
          ],
          resources: [
            { title: 'React Native Tutorial - Net Ninja', url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9ixPU-QkScoRBVxtPPzVjrQ', type: 'video' },
            { title: 'React Native Official Docs', url: 'https://reactnative.dev/docs/getting-started', type: 'docs' },
            { title: 'Expo Documentation', url: 'https://docs.expo.dev/', type: 'docs' },
            { title: 'React Native Full Course - JavaScript Mastery', url: 'https://www.youtube.com/watch?v=ZBCUegTZF7M', type: 'video' },
          ],
          project: {
            title: 'Todo App with Navigation',
            description: 'Build a multi-screen todo app with React Native: home screen, add task screen, categories, and swipe-to-delete functionality.',
          },
        },
      ],
    },
    {
      id: 'ui-ux-mobile',
      title: 'UI/UX & Advanced Components',
      description: 'Build beautiful, performant mobile interfaces with animations and complex layouts.',
      timeEstimate: '4-5 weeks',
      color: 'lime',
      topics: [
        {
          id: 'advanced-ui',
          title: 'Advanced UI Components',
          description: 'Build complex, production-quality UI components and screens.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Custom widgets/components',
            'Bottom sheets and modals',
            'Tab bars and drawer navigation',
            'Pull-to-refresh and infinite scroll',
            'Form handling and validation',
            'Responsive design for tablets',
            'Dark mode and theming',
            'Accessibility (VoiceOver, TalkBack)',
          ],
          resources: [
            { title: 'Flutter UI Challenge Playlist', url: 'https://www.youtube.com/playlist?list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG', type: 'video' },
            { title: 'React Native Paper (Material UI)', url: 'https://callstack.github.io/react-native-paper/', type: 'docs' },
            { title: 'Flutter Animations Guide', url: 'https://docs.flutter.dev/ui/animations', type: 'docs' },
          ],
          project: {
            title: 'E-commerce Product Screen',
            description: 'Build a polished e-commerce product detail screen with image carousel, size selector, add-to-cart animation, and reviews section.',
          },
        },
        {
          id: 'animations-gestures',
          title: 'Animations & Gestures',
          description: 'Create fluid animations and handle complex gestures for delightful UX.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Implicit vs explicit animations',
            'Animation controllers and curves',
            'Hero animations and page transitions',
            'Gesture detection (pan, pinch, swipe)',
            'React Native Reanimated library',
            'Shared element transitions',
            'Lottie animations',
            'Performance optimization for animations',
          ],
          resources: [
            { title: 'React Native Reanimated - William Candillon', url: 'https://www.youtube.com/c/wcandillon', type: 'video' },
            { title: 'Flutter Animation Tutorial - Reso Coder', url: 'https://www.youtube.com/watch?v=txLvvlooT20', type: 'video' },
            { title: 'Reanimated Documentation', url: 'https://docs.swmansion.com/react-native-reanimated/', type: 'docs' },
          ],
          project: {
            title: 'Animated Onboarding Flow',
            description: 'Build a stunning onboarding screen with page transitions, Lottie animations, parallax effects, and gesture-driven interactions.',
          },
        },
        {
          id: 'state-management-mobile',
          title: 'State Management',
          description: 'Manage complex app state effectively in mobile applications.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Local state vs global state',
            'Flutter: Provider, Riverpod, BLoC pattern',
            'React Native: Context, Zustand, Redux Toolkit',
            'Reactive programming concepts',
            'State persistence (local storage)',
            'Handling loading/error/success states',
            'Optimistic updates',
          ],
          resources: [
            { title: 'Riverpod Tutorial - Reso Coder', url: 'https://www.youtube.com/watch?v=vtGctcO3Rao', type: 'video' },
            { title: 'Zustand in React Native', url: 'https://www.youtube.com/watch?v=KEc0LLQjyfQ', type: 'video' },
            { title: 'Riverpod Documentation', url: 'https://riverpod.dev/', type: 'docs' },
          ],
          project: {
            title: 'Shopping Cart with State',
            description: 'Build a shopping cart with proper state management: add/remove items, quantity updates, total calculation, and persistence across app restarts.',
          },
        },
      ],
    },
    {
      id: 'data-backend',
      title: 'Data & Backend Integration',
      description: 'Connect your app to APIs, databases, and handle offline-first capabilities.',
      timeEstimate: '4-5 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'api-integration',
          title: 'API Integration & Networking',
          description: 'Connect your mobile app to backend APIs and handle network states.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'HTTP requests (GET, POST, PUT, DELETE)',
            'REST API consumption',
            'JSON parsing and serialization',
            'Error handling and retry logic',
            'Authentication (JWT, OAuth)',
            'Image caching and lazy loading',
            'GraphQL basics for mobile',
            'WebSockets for real-time features',
          ],
          resources: [
            { title: 'API Integration in Flutter - Reso Coder', url: 'https://www.youtube.com/watch?v=cJOAr6GeFuw', type: 'video' },
            { title: 'React Native + REST API', url: 'https://www.youtube.com/watch?v=ObwYOCkjGTI', type: 'video' },
            { title: 'Dio Package (Flutter HTTP)', url: 'https://pub.dev/packages/dio', type: 'docs' },
          ],
          project: {
            title: 'News Reader App',
            description: 'Build a news app that fetches from a real API, shows articles with images, handles offline state, and supports pull-to-refresh.',
          },
        },
        {
          id: 'local-storage',
          title: 'Local Storage & Offline',
          description: 'Store data locally and build offline-first mobile applications.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'SharedPreferences / AsyncStorage for key-value',
            'SQLite for structured local data',
            'Hive/Isar (Flutter) for NoSQL local storage',
            'Offline-first architecture',
            'Data syncing strategies',
            'Caching API responses',
            'Secure storage for tokens/secrets',
          ],
          resources: [
            { title: 'SQLite in Flutter - Reso Coder', url: 'https://www.youtube.com/watch?v=mBrB_eRsIoE', type: 'video' },
            { title: 'AsyncStorage in React Native', url: 'https://react-native-async-storage.github.io/async-storage/', type: 'docs' },
            { title: 'Hive Database for Flutter', url: 'https://docs.hivedb.dev/', type: 'docs' },
          ],
          project: {
            title: 'Offline Notes App',
            description: 'Build a notes app that works fully offline with local database, syncs when online, handles conflict resolution, and supports rich text.',
          },
        },
        {
          id: 'firebase-mobile',
          title: 'Firebase for Mobile',
          description: 'Use Firebase for authentication, database, storage, and push notifications.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Firebase Authentication (email, Google, Apple)',
            'Cloud Firestore for real-time data',
            'Firebase Storage for files/images',
            'Push notifications (FCM)',
            'Firebase Analytics',
            'Crashlytics for error reporting',
            'Remote Config for feature flags',
          ],
          resources: [
            { title: 'Flutter + Firebase - Net Ninja', url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9j--TKIdkb3ISfRbJeJYQwC', type: 'video' },
            { title: 'React Native Firebase', url: 'https://rnfirebase.io/', type: 'docs' },
            { title: 'FlutterFire Documentation', url: 'https://firebase.flutter.dev/', type: 'docs' },
          ],
          project: {
            title: 'Real-time Chat App',
            description: 'Build a chat app with Firebase: auth, real-time messaging with Firestore, image sharing via Storage, and push notifications.',
          },
        },
      ],
    },
    {
      id: 'native-features',
      title: 'Native Features & Testing',
      description: 'Access device hardware, handle permissions, and test your apps thoroughly.',
      timeEstimate: '3-4 weeks',
      color: 'orange',
      topics: [
        {
          id: 'device-features',
          title: 'Device Features & Permissions',
          description: 'Access camera, location, sensors, and handle runtime permissions.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Camera and photo gallery access',
            'Geolocation and maps integration',
            'Biometric authentication (fingerprint, Face ID)',
            'Push notifications (local & remote)',
            'Deep linking and universal links',
            'Background tasks and services',
            'Permission handling best practices',
            'App lifecycle management',
          ],
          resources: [
            { title: 'Flutter Maps & Location', url: 'https://www.youtube.com/watch?v=Zz5hMvgiWmY', type: 'video' },
            { title: 'React Native Permissions', url: 'https://www.youtube.com/watch?v=N50VMhzgGQ4', type: 'video' },
            { title: 'Expo Location API', url: 'https://docs.expo.dev/versions/latest/sdk/location/', type: 'docs' },
          ],
          project: {
            title: 'Location-Based Reminder App',
            description: 'Build an app that triggers reminders based on location. Use geofencing, maps, local notifications, and background location tracking.',
          },
        },
        {
          id: 'testing-mobile',
          title: 'Testing & Debugging',
          description: 'Write tests and debug mobile applications effectively.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Unit testing in Flutter/React Native',
            'Widget/component testing',
            'Integration testing',
            'Debugging tools (Flipper, DevTools)',
            'Performance profiling',
            'Network inspector',
            'Crash reporting setup',
            'Beta testing (TestFlight, Firebase Distribution)',
          ],
          resources: [
            { title: 'Flutter Testing Full Guide - Reso Coder', url: 'https://www.youtube.com/watch?v=RDY6UYh-4bE', type: 'video' },
            { title: 'React Native Testing - Academind', url: 'https://www.youtube.com/watch?v=jSvo-KXDpnM', type: 'video' },
            { title: 'Flutter Testing Guide', url: 'https://docs.flutter.dev/testing', type: 'docs' },
            { title: 'React Native Testing Library', url: 'https://callstack.github.io/react-native-testing-library/', type: 'docs' },
            { title: 'Detox E2E Testing', url: 'https://wix.github.io/Detox/', type: 'docs' },
          ],
          project: {
            title: 'Tested & Debugged App',
            description: 'Add comprehensive tests to your chat app: unit tests for logic, widget tests for UI, and integration tests for critical flows.',
          },
        },
      ],
    },
    {
      id: 'deployment-publishing',
      title: 'Deployment & Publishing',
      description: 'Prepare, build, and publish your app to the App Store and Google Play.',
      timeEstimate: '3-4 weeks',
      color: 'purple',
      topics: [
        {
          id: 'app-store-prep',
          title: 'App Store Preparation',
          description: 'Prepare your app for store submission with proper assets and optimization.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'App icons and splash screens',
            'App Store screenshots and preview videos',
            'App Store Optimization (ASO)',
            'Privacy policy and terms',
            'App signing and certificates',
            'Build variants (debug, release, staging)',
            'Code push and OTA updates',
            'App size optimization',
          ],
          resources: [
            { title: 'Publishing Flutter App - Official Guide', url: 'https://docs.flutter.dev/deployment', type: 'docs' },
            { title: 'React Native Publishing Guide', url: 'https://reactnative.dev/docs/publishing-to-app-store', type: 'docs' },
            { title: 'ASO Guide - App Radar', url: 'https://www.youtube.com/watch?v=fUy5-IIlNjE', type: 'video' },
          ],
          project: {
            title: 'Store-Ready App Package',
            description: 'Prepare your app for publishing: create icons, splash screens, screenshots, write store listing copy, configure signing, and build release APK/IPA.',
          },
        },
        {
          id: 'ci-cd-mobile',
          title: 'CI/CD for Mobile',
          description: 'Automate building, testing, and deploying mobile applications.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Fastlane for automated builds',
            'GitHub Actions for mobile CI',
            'EAS Build (Expo)',
            'Codemagic / Bitrise',
            'Automated testing in CI',
            'Beta distribution',
            'Version management and changelogs',
            'Automated store submissions',
          ],
          resources: [
            { title: 'Fastlane Tutorial', url: 'https://www.youtube.com/watch?v=ssVavLfWQkU', type: 'video' },
            { title: 'EAS Build Documentation', url: 'https://docs.expo.dev/build/introduction/', type: 'docs' },
            { title: 'Codemagic Flutter CI/CD', url: 'https://docs.codemagic.io/', type: 'docs' },
          ],
          project: {
            title: 'Automated Build Pipeline',
            description: 'Set up CI/CD: auto-run tests on PR, build APK/IPA on merge, distribute beta via Firebase Distribution, and auto-submit to stores.',
          },
        },
        {
          id: 'capstone-mobile',
          title: 'Capstone: Full Mobile App',
          description: 'Build and publish a complete, polished mobile application.',
          timeEstimate: '14-21 days',
          whatToLearn: [
            'Project planning and feature prioritization',
            'UI/UX design implementation',
            'Full backend integration',
            'Offline support and data sync',
            'Performance optimization',
            'Analytics and crash reporting',
            'Beta testing and iteration',
            'Store submission and launch',
          ],
          resources: [
            { title: 'Build & Publish a Flutter App', url: 'https://www.youtube.com/watch?v=x0uinJvhNxI', type: 'video' },
            { title: 'React Native Production App - Expo', url: 'https://docs.expo.dev/workflow/overview/', type: 'docs' },
            { title: 'App Launch Checklist', url: 'https://developer.apple.com/app-store/review/guidelines/', type: 'docs' },
          ],
          project: {
            title: 'Publish Your App',
            description: 'Build a complete app from scratch (fitness tracker, recipe app, or habit tracker). Polish UI, add analytics, run beta tests, and publish to both stores.',
          },
        },
      ],
    },
  ],
};
