import { Roadmap } from '@/types/roadmap';

export const oopRoadmap: Roadmap = {
  slug: 'object-oriented-programming',
  title: 'Object Oriented Programming',
  description: 'Master OOP concepts from basics to advanced design patterns — with language-specific implementations in Java, Python, C++, and JavaScript.',
  icon: 'Blocks',
  accent: '#D8CCFF',
  totalTime: '4-6 weeks',
  languages: ['Java', 'Python', 'C++', 'JavaScript'],
  variants: [
    { id: 'java', label: 'Java' },
    { id: 'python', label: 'Python' },
    { id: 'cpp', label: 'C++' },
    { id: 'javascript', label: 'JavaScript' },
  ],
  relatedRoadmaps: [
    { slug: 'backend-developer', relation: 'builds-on', description: 'Backend development heavily relies on OOP patterns' },
    { slug: 'full-stack-developer', relation: 'shared-topics', description: 'Full-stack apps use OOP in both frontend and backend' },
    { slug: 'placement-preparation', relation: 'shared-topics', description: 'OOP is a core topic in placement interviews' },
    { slug: 'ai-engineer', relation: 'shared-topics', description: 'ML frameworks use OOP patterns extensively' },
  ],
  stages: [
    // ─── STAGE 1: FOUNDATIONS ──────────────────────────────────────────────────
    {
      id: 'foundations',
      title: 'OOP Foundations',
      description: 'Understand what OOP is, why it exists, and learn the basic building blocks — classes and objects.',
      timeEstimate: '1 week',
      color: 'green',
      topics: [
        {
          id: 'intro-to-oop',
          title: 'What is OOP & Why It Matters',
          description: 'Understand the paradigm shift from procedural to object-oriented thinking and when to use OOP.',
          timeEstimate: '1-2 days',
          whatToLearn: [
            'Procedural vs Object-Oriented programming',
            'Real-world analogy: objects, properties, behaviors',
            'Benefits: reusability, modularity, maintainability',
            'When OOP is the right choice vs functional programming',
            'History: Simula, Smalltalk, and modern OOP languages',
            'The four pillars overview: Encapsulation, Inheritance, Polymorphism, Abstraction',
          ],
          resources: [
            { title: 'Object-Oriented Programming in 7 minutes - Mosh', url: 'https://www.youtube.com/watch?v=pTB0EiLXUC8', type: 'video' },
            { title: 'OOP Concepts - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/', type: 'article' },
            { title: 'Introduction to OOP - MIT OpenCourseWare', url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/lecture-slides-and-code/', type: 'course' },
          ],
          project: {
            title: 'Compare Procedural vs OOP',
            description: 'Write a simple bank account program twice — once procedural (functions + dictionaries) and once with classes. Compare readability and extensibility.',
          },
        },
        {
          id: 'classes-objects-java',
          title: 'Classes & Objects in Java',
          description: 'Learn how Java defines classes, creates objects, and manages memory with constructors and the new keyword.',
          variant: 'java',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Class declaration and object instantiation',
            'Instance variables and methods',
            'Constructors (default, parameterized, copy)',
            'The `this` keyword and self-reference',
            'Static vs instance members',
            'Memory: stack vs heap, garbage collection',
            'Access modifiers: public, private, protected, default',
            'Object class and toString(), equals(), hashCode()',
          ],
          resources: [
            { title: 'Java OOP - Full Course (freeCodeCamp)', url: 'https://www.youtube.com/watch?v=Ae-r8hsbPUo', type: 'video' },
            { title: 'Java Classes and Objects - W3Schools', url: 'https://www.w3schools.com/java/java_classes.asp', type: 'article' },
            { title: 'Java OOP - Oracle Official Tutorial', url: 'https://docs.oracle.com/javase/tutorial/java/concepts/index.html', type: 'docs' },
            { title: 'Java OOP Concepts - Telusko', url: 'https://www.youtube.com/watch?v=BSVKUk58K6U', type: 'video' },
          ],
          project: {
            title: 'Student Management System',
            description: 'Create a Student class with name, roll number, and grades. Implement constructors, getters/setters, and a method to calculate GPA.',
          },
        },
        {
          id: 'classes-objects-python',
          title: 'Classes & Objects in Python',
          description: 'Learn Python\'s elegant class syntax, the self parameter, and how Python handles object creation.',
          variant: 'python',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Class definition with `class` keyword',
            'The __init__ constructor and `self` parameter',
            'Instance attributes vs class attributes',
            'Instance methods, class methods (@classmethod), static methods (@staticmethod)',
            'Magic/dunder methods (__str__, __repr__, __len__)',
            'Name mangling and private conventions (_single, __double)',
            'Python\'s dynamic nature: adding attributes at runtime',
            'Type hints in classes',
          ],
          resources: [
            { title: 'Python OOP Tutorial - Corey Schafer (6 parts)', url: 'https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc', type: 'video' },
            { title: 'Python Classes - Official Docs', url: 'https://docs.python.org/3/tutorial/classes.html', type: 'docs' },
            { title: 'OOP in Python - Real Python', url: 'https://realpython.com/python3-object-oriented-programming/', type: 'article' },
            { title: 'Python OOP - freeCodeCamp', url: 'https://www.youtube.com/watch?v=Ej_02ICOIgs', type: 'video' },
          ],
          project: {
            title: 'Library Book Tracker',
            description: 'Build a Book class with title, author, ISBN, and availability status. Use __str__ and __repr__ for display. Add a Library class that manages a collection of books.',
          },
        },
        {
          id: 'classes-objects-cpp',
          title: 'Classes & Objects in C++',
          description: 'Learn C++ class syntax, memory management with constructors/destructors, and the differences between stack and heap objects.',
          variant: 'cpp',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Class definition: header files (.h) vs implementation (.cpp)',
            'Constructors: default, parameterized, copy, move',
            'Destructors and RAII (Resource Acquisition Is Initialization)',
            'The `this` pointer',
            'Access specifiers: public, private, protected',
            'Static members and methods',
            'Stack vs heap allocation (new/delete)',
            'Const member functions and const objects',
            'Friend functions and friend classes',
          ],
          resources: [
            { title: 'C++ OOP - The Cherno (Playlist)', url: 'https://www.youtube.com/watch?v=SfGuIVzE_Os&list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb', type: 'video' },
            { title: 'C++ Classes and Objects - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/c-classes-and-objects/', type: 'article' },
            { title: 'C++ OOP - W3Schools', url: 'https://www.w3schools.com/cpp/cpp_oop.asp', type: 'article' },
            { title: 'LearnCpp.com - OOP Section', url: 'https://www.learncpp.com/cpp-tutorial/introduction-to-object-oriented-programming/', type: 'course' },
          ],
          project: {
            title: 'Matrix Calculator',
            description: 'Create a Matrix class with dynamic memory allocation. Implement constructors, destructor, copy constructor, and operator overloading for +, -, and *.',
          },
        },
        {
          id: 'classes-objects-js',
          title: 'Classes & Objects in JavaScript',
          description: 'Understand JavaScript\'s prototype-based OOP and the modern ES6 class syntax built on top of it.',
          variant: 'javascript',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Object literals and property shorthand',
            'Constructor functions and the `new` keyword',
            'Prototypes and the prototype chain',
            'ES6 class syntax (syntactic sugar over prototypes)',
            'Constructor method and `this` binding',
            'Getters and setters (get/set)',
            'Static methods and properties',
            'Private fields (#privateField) and methods',
            'Difference: class-based vs prototype-based OOP',
          ],
          resources: [
            { title: 'JavaScript OOP Crash Course - Traversy Media', url: 'https://www.youtube.com/watch?v=vDJpGenyHaA', type: 'video' },
            { title: 'Classes - MDN Web Docs', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes', type: 'docs' },
            { title: 'JavaScript.info - Classes', url: 'https://javascript.info/classes', type: 'article' },
            { title: 'Object Prototypes - MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes', type: 'docs' },
          ],
          project: {
            title: 'Shape Drawing App',
            description: 'Build Shape, Circle, Rectangle classes using ES6 syntax. Implement area/perimeter methods and demonstrate prototype chain with instanceof checks.',
          },
        },
      ],
    },

    // ─── STAGE 2: ENCAPSULATION ──────────────────────────────────────────────────
    {
      id: 'encapsulation',
      title: 'Encapsulation',
      description: 'Learn to hide internal state, expose controlled interfaces, and protect data integrity.',
      timeEstimate: '4-5 days',
      color: 'lime',
      topics: [
        {
          id: 'encapsulation-java',
          title: 'Encapsulation in Java',
          description: 'Master Java\'s strict access control, getters/setters, and immutable object patterns.',
          variant: 'java',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Access modifiers in depth: private, protected, public, package-private',
            'Getter and setter methods with validation',
            'Immutable objects (final fields, no setters)',
            'Builder pattern for complex object construction',
            'Encapsulation in packages and modules (Java 9+)',
            'Record classes (Java 16+) for data carriers',
            'JavaBeans convention',
          ],
          resources: [
            { title: 'Encapsulation in Java - Telusko', url: 'https://www.youtube.com/watch?v=cU94So54cr8', type: 'video' },
            { title: 'Java Encapsulation - Baeldung', url: 'https://www.baeldung.com/java-encapsulation', type: 'article' },
            { title: 'Effective Java - Minimize Access (Item 15)', url: 'https://www.oracle.com/java/technologies/javase/seccodeguide.html', type: 'docs' },
          ],
          project: {
            title: 'Bank Account with Validation',
            description: 'Build an immutable BankAccount class where balance can only change through validated deposit() and withdraw() methods. Use Builder pattern for construction.',
          },
        },
        {
          id: 'encapsulation-python',
          title: 'Encapsulation in Python',
          description: 'Understand Python\'s convention-based privacy, properties, and descriptor protocol.',
          variant: 'python',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Convention: _private and __name_mangling',
            '@property decorator for getters/setters',
            'Property with validation logic',
            'Slots (__slots__) for memory optimization',
            'Descriptors protocol (__get__, __set__, __delete__)',
            'dataclasses with frozen=True for immutability',
            'Why Python trusts developers (no true private)',
          ],
          resources: [
            { title: 'Python Properties - Corey Schafer', url: 'https://www.youtube.com/watch?v=jCzT9XFZ5bw', type: 'video' },
            { title: 'Python Encapsulation - Real Python', url: 'https://realpython.com/python-property/', type: 'article' },
            { title: 'Python Descriptors - Official Docs', url: 'https://docs.python.org/3/howto/descriptor.html', type: 'docs' },
          ],
          project: {
            title: 'Temperature Converter Class',
            description: 'Create a Temperature class using @property. Setting celsius auto-updates fahrenheit and vice versa. Add validation (no below absolute zero).',
          },
        },
        {
          id: 'encapsulation-cpp',
          title: 'Encapsulation in C++',
          description: 'Learn strict access control, friend functions, and modern C++ encapsulation patterns.',
          variant: 'cpp',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Access specifiers: public, private, protected',
            'Getter/setter methods with const correctness',
            'Friend functions and classes (controlled access)',
            'Pimpl idiom (Pointer to Implementation) for ABI stability',
            'Struct vs Class (default access difference)',
            'Encapsulation in header-only libraries',
            'Const member functions and mutable keyword',
          ],
          resources: [
            { title: 'Encapsulation in C++ - The Cherno', url: 'https://www.youtube.com/watch?v=Z_hPJ_EhceI', type: 'video' },
            { title: 'C++ Encapsulation - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/encapsulation-in-cpp/', type: 'article' },
            { title: 'LearnCpp - Access Specifiers', url: 'https://www.learncpp.com/cpp-tutorial/access-specifiers/', type: 'course' },
          ],
          project: {
            title: 'Secure Password Manager',
            description: 'Build a PasswordEntry class with private encrypted storage. Only expose validate() and getHint(). Use friend function for admin reset functionality.',
          },
        },
        {
          id: 'encapsulation-js',
          title: 'Encapsulation in JavaScript',
          description: 'Learn JavaScript\'s evolving privacy model — from closures to WeakMaps to native private fields.',
          variant: 'javascript',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Closure-based privacy (module pattern)',
            'Symbol keys for semi-private properties',
            'WeakMap for truly private data',
            'ES2022 private fields (#field) and methods (#method)',
            'Getters and setters with Object.defineProperty',
            'Proxy for controlled access',
            'TypeScript private/protected (compile-time only)',
          ],
          resources: [
            { title: 'Private Class Fields - JavaScript.info', url: 'https://javascript.info/private-protected-properties-methods', type: 'article' },
            { title: 'JS Encapsulation Patterns - Fireship', url: 'https://www.youtube.com/watch?v=vDJpGenyHaA', type: 'video' },
            { title: 'Private Fields - MDN Docs', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties', type: 'docs' },
          ],
          project: {
            title: 'Shopping Cart Module',
            description: 'Build a Cart class with #items as private. Expose addItem(), removeItem(), and total. Prevent direct array manipulation from outside.',
          },
        },
      ],
    },

    // ─── STAGE 3: INHERITANCE ──────────────────────────────────────────────────
    {
      id: 'inheritance',
      title: 'Inheritance',
      description: 'Learn code reuse through class hierarchies — single, multilevel, and the diamond problem.',
      timeEstimate: '5-6 days',
      color: 'yellow',
      topics: [
        {
          id: 'inheritance-java',
          title: 'Inheritance in Java',
          description: 'Master Java\'s single inheritance model, the extends keyword, method overriding, and the Object hierarchy.',
          variant: 'java',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'extends keyword and IS-A relationship',
            'Method overriding with @Override annotation',
            'super keyword (parent constructor and methods)',
            'Constructor chaining in inheritance',
            'final classes and methods (preventing inheritance)',
            'Sealed classes (Java 17+)',
            'Upcasting and downcasting with instanceof',
            'Why Java doesn\'t allow multiple class inheritance',
            'Composition vs Inheritance principle',
          ],
          resources: [
            { title: 'Java Inheritance - Programming with Mosh', url: 'https://www.youtube.com/watch?v=Zs342ePFvRI', type: 'video' },
            { title: 'Inheritance - Oracle Docs', url: 'https://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html', type: 'docs' },
            { title: 'Java Inheritance - Baeldung', url: 'https://www.baeldung.com/java-inheritance', type: 'article' },
            { title: 'Composition vs Inheritance - Head First Design Patterns', url: 'https://www.youtube.com/watch?v=hxGOiiR9ZKg', type: 'video' },
          ],
          project: {
            title: 'Vehicle Hierarchy',
            description: 'Build Vehicle → Car, Truck, Motorcycle hierarchy. Add ElectricCar extending Car. Demonstrate method overriding, super calls, and instanceof checks.',
          },
        },
        {
          id: 'inheritance-python',
          title: 'Inheritance in Python',
          description: 'Learn Python\'s powerful multiple inheritance, MRO (Method Resolution Order), and mixin patterns.',
          variant: 'python',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Single inheritance syntax and super()',
            'Multiple inheritance and MRO (C3 linearization)',
            'The diamond problem and how Python resolves it',
            'Mixins: adding behavior without deep hierarchies',
            'super() with multiple inheritance (cooperative)',
            'Abstract base classes (abc module)',
            'isinstance() and issubclass()',
            '__mro__ attribute and Method Resolution Order',
            'Composition vs Inheritance in Python',
          ],
          resources: [
            { title: 'Python OOP: Inheritance - Corey Schafer', url: 'https://www.youtube.com/watch?v=RSl87lqOXDE', type: 'video' },
            { title: 'Python Multiple Inheritance - Real Python', url: 'https://realpython.com/inheritance-composition-python/', type: 'article' },
            { title: 'super() in Python - Raymond Hettinger (PyCon)', url: 'https://www.youtube.com/watch?v=EiOglTERPEo', type: 'video' },
            { title: 'ABC Module - Python Docs', url: 'https://docs.python.org/3/library/abc.html', type: 'docs' },
          ],
          project: {
            title: 'RPG Character System',
            description: 'Build Character base class. Create Warrior, Mage, Healer. Use mixins (SwimMixin, FlyMixin) for abilities. Demonstrate MRO with diamond inheritance.',
          },
        },
        {
          id: 'inheritance-cpp',
          title: 'Inheritance in C++',
          description: 'Master C++\'s flexible inheritance — single, multiple, virtual inheritance, and solving the diamond problem.',
          variant: 'cpp',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Single inheritance and access specifiers (public/private/protected inheritance)',
            'Constructor and destructor order in inheritance',
            'Method overriding and the override keyword',
            'Multiple inheritance and ambiguity resolution',
            'Virtual inheritance (solving the diamond problem)',
            'Virtual base classes',
            'Abstract classes with pure virtual functions (= 0)',
            'The final specifier',
            'Slicing problem with value semantics',
            'Virtual destructors (critical for polymorphism)',
          ],
          resources: [
            { title: 'C++ Inheritance - The Cherno', url: 'https://www.youtube.com/watch?v=X8nYM8wdNRE', type: 'video' },
            { title: 'C++ Multiple Inheritance - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/multiple-inheritance-in-c/', type: 'article' },
            { title: 'Virtual Inheritance - LearnCpp', url: 'https://www.learncpp.com/cpp-tutorial/virtual-base-classes/', type: 'course' },
            { title: 'C++ Diamond Problem Explained', url: 'https://www.youtube.com/watch?v=7APovvvftQs', type: 'video' },
          ],
          project: {
            title: 'GUI Widget Framework',
            description: 'Build Widget base → Button, TextBox, Checkbox. Create ComboBox using multiple inheritance from TextBox and DropDown. Solve diamond with virtual inheritance.',
          },
        },
        {
          id: 'inheritance-js',
          title: 'Inheritance in JavaScript',
          description: 'Understand prototypal inheritance, the class extends syntax, and why JS inheritance is fundamentally different.',
          variant: 'javascript',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Prototype chain: __proto__ and Object.getPrototypeOf()',
            'Object.create() for prototypal inheritance',
            'ES6 extends keyword and super()',
            'Method overriding in class syntax',
            'Mixins with Object.assign() (no multiple inheritance)',
            'Symbol.hasInstance for custom instanceof',
            'Why JS uses delegation, not classical inheritance',
            'Composition patterns (factory functions, object spread)',
            'instanceof vs duck typing',
          ],
          resources: [
            { title: 'Prototypal Inheritance - JavaScript.info', url: 'https://javascript.info/prototype-inheritance', type: 'article' },
            { title: 'JS Inheritance - Fun Fun Function', url: 'https://www.youtube.com/watch?v=wfMtDGfHWpA', type: 'video' },
            { title: 'Inheritance and Prototype Chain - MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain', type: 'docs' },
            { title: 'Composition over Inheritance - Fun Fun Function', url: 'https://www.youtube.com/watch?v=wfMtDGfHWpA', type: 'video' },
          ],
          project: {
            title: 'UI Component System',
            description: 'Build Component → Button, Input, Modal using class syntax. Add mixins for Draggable, Resizable behaviors. Show prototype chain with Object.getPrototypeOf().',
          },
        },
      ],
    },

    // ─── STAGE 4: POLYMORPHISM ──────────────────────────────────────────────────
    {
      id: 'polymorphism',
      title: 'Polymorphism',
      description: 'Learn how the same interface can have different implementations — compile-time and runtime polymorphism.',
      timeEstimate: '5-6 days',
      color: 'orange',
      topics: [
        {
          id: 'polymorphism-java',
          title: 'Polymorphism in Java',
          description: 'Master method overloading, overriding, interfaces, and runtime dispatch in Java.',
          variant: 'java',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Compile-time (static) polymorphism: method overloading',
            'Runtime (dynamic) polymorphism: method overriding',
            'Interface polymorphism (coding to interfaces)',
            'Covariant return types',
            'Generic types and bounded type parameters',
            'Method dispatch and vtable concept',
            'Functional interfaces and lambda expressions',
            'Default methods in interfaces (Java 8+)',
            'Pattern matching with instanceof (Java 16+)',
          ],
          resources: [
            { title: 'Polymorphism in Java - Telusko', url: 'https://www.youtube.com/watch?v=tYTOBRRmGCU', type: 'video' },
            { title: 'Java Polymorphism - Baeldung', url: 'https://www.baeldung.com/java-polymorphism', type: 'article' },
            { title: 'Java Interfaces - Oracle Docs', url: 'https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html', type: 'docs' },
            { title: 'Java Generics Tutorial - freeCodeCamp', url: 'https://www.youtube.com/watch?v=K1iu1kXkVoA', type: 'video' },
          ],
          project: {
            title: 'Payment Processing System',
            description: 'Create a Payment interface with process() method. Implement CreditCard, PayPal, Crypto payments. Use a PaymentProcessor that accepts any Payment type polymorphically.',
          },
        },
        {
          id: 'polymorphism-python',
          title: 'Polymorphism in Python',
          description: 'Learn duck typing, method overriding, protocols, and how Python achieves polymorphism without interfaces.',
          variant: 'python',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Duck typing: "if it quacks like a duck..."',
            'Method overriding and super()',
            'Operator overloading (__add__, __eq__, __lt__, etc.)',
            'Abstract methods with @abstractmethod',
            'Protocols (structural subtyping) - typing.Protocol',
            'Function overloading with @singledispatch',
            'Magic methods for polymorphic behavior',
            '__call__ for callable objects',
            'Type checking with isinstance() vs duck typing',
          ],
          resources: [
            { title: 'Python Polymorphism - Corey Schafer', url: 'https://www.youtube.com/watch?v=HTLu2DFOdTg', type: 'video' },
            { title: 'Duck Typing and Protocols - Real Python', url: 'https://realpython.com/python-protocol/', type: 'article' },
            { title: 'Operator Overloading - Python Docs', url: 'https://docs.python.org/3/reference/datamodel.html#special-method-names', type: 'docs' },
            { title: 'Python Magic Methods Guide', url: 'https://rszalski.github.io/magicmethods/', type: 'article' },
          ],
          project: {
            title: 'Shape Calculator with Operators',
            description: 'Build Shape classes with operator overloading. Circles + Circles = bigger circle, Shape == Shape compares area. Use Protocol for Drawable interface.',
          },
        },
        {
          id: 'polymorphism-cpp',
          title: 'Polymorphism in C++',
          description: 'Master compile-time (templates, overloading) and runtime (virtual functions, vtable) polymorphism in C++.',
          variant: 'cpp',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Function overloading (compile-time)',
            'Operator overloading',
            'Virtual functions and vtable mechanism',
            'Pure virtual functions and abstract classes',
            'Virtual destructors (why they\'re essential)',
            'Runtime type identification (RTTI): dynamic_cast, typeid',
            'Templates for compile-time polymorphism (generic programming)',
            'CRTP (Curiously Recurring Template Pattern)',
            'std::variant and std::visit (modern alternative to virtual)',
            'Static polymorphism vs dynamic polymorphism trade-offs',
          ],
          resources: [
            { title: 'C++ Virtual Functions - The Cherno', url: 'https://www.youtube.com/watch?v=oIV2KchSyGQ', type: 'video' },
            { title: 'C++ Polymorphism - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/cpp-polymorphism/', type: 'article' },
            { title: 'Templates in C++ - LearnCpp', url: 'https://www.learncpp.com/cpp-tutorial/function-templates/', type: 'course' },
            { title: 'C++ Virtual Dispatch - CppCon', url: 'https://www.youtube.com/watch?v=QzJL-8WbpuU', type: 'video' },
          ],
          project: {
            title: 'Plugin System',
            description: 'Build an abstract Plugin base with virtual load(), execute(), unload(). Create FilePlugin, NetworkPlugin, DatabasePlugin. Use dynamic_cast for type-specific operations.',
          },
        },
        {
          id: 'polymorphism-js',
          title: 'Polymorphism in JavaScript',
          description: 'Learn how JS achieves polymorphism through duck typing, method overriding, and dynamic dispatch.',
          variant: 'javascript',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Method overriding with class syntax',
            'Duck typing (no explicit interfaces needed)',
            'Symbol.iterator for polymorphic iteration',
            'toString() and valueOf() for type coercion control',
            'TypeScript interfaces for compile-time polymorphism',
            'Strategy pattern with functions as first-class citizens',
            'Polymorphic collections (arrays with mixed types)',
            'Optional chaining and duck typing patterns',
          ],
          resources: [
            { title: 'JavaScript Polymorphism - dcode', url: 'https://www.youtube.com/watch?v=e5LoIRDJcNo', type: 'video' },
            { title: 'Polymorphism - JavaScript.info', url: 'https://javascript.info/class-inheritance', type: 'article' },
            { title: 'Symbol.iterator - MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator', type: 'docs' },
          ],
          project: {
            title: 'Notification System',
            description: 'Build EmailNotifier, SMSNotifier, PushNotifier with the same send() interface. Create a NotificationManager that sends through any notifier polymorphically.',
          },
        },
      ],
    },

    // ─── STAGE 5: ABSTRACTION ──────────────────────────────────────────────────
    {
      id: 'abstraction',
      title: 'Abstraction & Interfaces',
      description: 'Learn to define contracts, hide complexity, and program to interfaces rather than implementations.',
      timeEstimate: '4-5 days',
      color: 'red',
      topics: [
        {
          id: 'abstraction-java',
          title: 'Abstraction in Java',
          description: 'Master abstract classes, interfaces, default methods, and the interface segregation principle.',
          variant: 'java',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Abstract classes vs interfaces — when to use which',
            'Interface with default and static methods',
            'Multiple interface implementation',
            'Interface segregation principle (ISP)',
            'Marker interfaces (Serializable, Cloneable)',
            'Functional interfaces (@FunctionalInterface)',
            'Sealed interfaces (Java 17+)',
            'Service provider interface (SPI) pattern',
            'Dependency inversion with interfaces',
          ],
          resources: [
            { title: 'Abstract Classes vs Interfaces - Programming with Mosh', url: 'https://www.youtube.com/watch?v=HvPlEJ3LHgE', type: 'video' },
            { title: 'Java Interfaces - Baeldung', url: 'https://www.baeldung.com/java-interfaces', type: 'article' },
            { title: 'Abstract Classes - Oracle Docs', url: 'https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html', type: 'docs' },
            { title: 'Interface Segregation - Clean Code', url: 'https://www.youtube.com/watch?v=JVWZR23KEMY', type: 'video' },
          ],
          project: {
            title: 'Database Abstraction Layer',
            description: 'Define a Database interface with connect(), query(), disconnect(). Implement MySQLDatabase, MongoDatabase, InMemoryDatabase. Swap implementations without changing client code.',
          },
        },
        {
          id: 'abstraction-python',
          title: 'Abstraction in Python',
          description: 'Learn abstract base classes, protocols, and Pythonic abstraction patterns.',
          variant: 'python',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'abc module: ABC, @abstractmethod, @abstractproperty',
            'When to use ABC vs Protocol',
            'Structural subtyping with typing.Protocol',
            'collections.abc abstract base classes',
            '__subclasshook__ for custom isinstance behavior',
            'Abstract properties and class methods',
            'Duck typing as Python\'s primary abstraction',
            'Zope.interface and formal interface libraries',
          ],
          resources: [
            { title: 'Abstract Classes in Python - Tech With Tim', url: 'https://www.youtube.com/watch?v=aWFvpqvR_-Q', type: 'video' },
            { title: 'ABC Module Guide - Real Python', url: 'https://realpython.com/python-interface/', type: 'article' },
            { title: 'typing.Protocol - PEP 544', url: 'https://peps.python.org/pep-0544/', type: 'docs' },
          ],
          project: {
            title: 'File Storage Abstraction',
            description: 'Create an abstract StorageBackend with save(), load(), delete(). Implement LocalStorage, S3Storage, and a MockStorage for testing. Use Protocol for type checking.',
          },
        },
        {
          id: 'abstraction-cpp',
          title: 'Abstraction in C++',
          description: 'Master abstract classes, pure virtual functions, interfaces via ABCs, and concepts (C++20).',
          variant: 'cpp',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Pure virtual functions (= 0) for abstract classes',
            'Interface pattern (class with only pure virtuals)',
            'Multiple interfaces via multiple inheritance',
            'Virtual destructors in abstract classes',
            'C++20 Concepts for compile-time constraints',
            'CRTP as static interface enforcement',
            'Template specialization for behavior customization',
            'std::function for callback abstraction',
            'Type erasure (std::any, std::function internals)',
          ],
          resources: [
            { title: 'C++ Abstract Classes - The Cherno', url: 'https://www.youtube.com/watch?v=UWAdd13EfM8', type: 'video' },
            { title: 'Pure Virtual Functions - LearnCpp', url: 'https://www.learncpp.com/cpp-tutorial/pure-virtual-functions-abstract-base-classes-and-interface-classes/', type: 'course' },
            { title: 'C++20 Concepts - GeeksForGeeks', url: 'https://www.geeksforgeeks.org/cpp-20-concepts/', type: 'article' },
            { title: 'C++ Concepts - CppCon', url: 'https://www.youtube.com/watch?v=_FoXWnrGuII', type: 'video' },
          ],
          project: {
            title: 'Logger Framework',
            description: 'Define abstract ILogger with log(), setLevel(). Implement ConsoleLogger, FileLogger, NetworkLogger. Use C++20 concepts to constrain what qualifies as a Logger.',
          },
        },
        {
          id: 'abstraction-js',
          title: 'Abstraction in JavaScript',
          description: 'Learn to create abstract-like patterns in JS/TS — from convention-based to TypeScript interfaces.',
          variant: 'javascript',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Simulating abstract classes (throw in base method)',
            'TypeScript interfaces and abstract classes',
            'Factory pattern for abstraction',
            'Module pattern for information hiding',
            'Dependency injection without frameworks',
            'Higher-order functions as abstraction',
            'TypeScript generics for type-safe abstraction',
            'The adapter pattern in JavaScript',
          ],
          resources: [
            { title: 'Abstract Classes in TypeScript', url: 'https://www.youtube.com/watch?v=UmHKrcpRqXE', type: 'video' },
            { title: 'TypeScript Interfaces - Official Docs', url: 'https://www.typescriptlang.org/docs/handbook/interfaces.html', type: 'docs' },
            { title: 'Factory Pattern in JS - Patterns.dev', url: 'https://www.patterns.dev/vanilla/factory-pattern', type: 'article' },
          ],
          project: {
            title: 'HTTP Client Abstraction',
            description: 'Create an HttpClient interface (TypeScript). Implement FetchClient, AxiosClient, MockClient. Client code depends only on the interface — swap implementations freely.',
          },
        },
      ],
    },

    // ─── STAGE 6: ADVANCED OOP ──────────────────────────────────────────────────
    {
      id: 'advanced-oop',
      title: 'Advanced OOP Concepts',
      description: 'Master design patterns, SOLID principles, and advanced techniques used in production codebases.',
      timeEstimate: '1-2 weeks',
      color: 'purple',
      topics: [
        {
          id: 'solid-principles',
          title: 'SOLID Principles',
          description: 'Learn the five foundational principles of object-oriented design that make code maintainable and extensible.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Single Responsibility Principle (SRP): one reason to change',
            'Open/Closed Principle (OCP): open for extension, closed for modification',
            'Liskov Substitution Principle (LSP): subtypes must be substitutable',
            'Interface Segregation Principle (ISP): no fat interfaces',
            'Dependency Inversion Principle (DIP): depend on abstractions',
            'Applying SOLID in real codebases',
            'When SOLID becomes over-engineering',
            'SOLID violations and code smells',
          ],
          resources: [
            { title: 'SOLID Principles in 8 Minutes', url: 'https://www.youtube.com/watch?v=yxf2spbpTSw', type: 'video' },
            { title: 'SOLID Principles - freeCodeCamp', url: 'https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/', type: 'article' },
            { title: 'SOLID in Java - Baeldung', url: 'https://www.baeldung.com/solid-principles', type: 'article' },
            { title: 'Uncle Bob SOLID Principles Talk', url: 'https://www.youtube.com/watch?v=zHiWqnTWsn4', type: 'video' },
          ],
          project: {
            title: 'Refactor a Monolith',
            description: 'Take a 200-line god class (e.g., UserManager that handles auth, email, DB, logging) and refactor it to follow all 5 SOLID principles. Document each change.',
          },
        },
        {
          id: 'design-patterns-creational',
          title: 'Creational Design Patterns',
          description: 'Learn patterns that control object creation — Singleton, Factory, Builder, and Prototype.',
          timeEstimate: '3-4 days',
          whatToLearn: [
            'Singleton: ensure one instance (and its problems)',
            'Factory Method: delegate object creation to subclasses',
            'Abstract Factory: families of related objects',
            'Builder: step-by-step complex object construction',
            'Prototype: cloning existing objects',
            'When each pattern is appropriate',
            'Anti-patterns: Singleton overuse',
          ],
          resources: [
            { title: 'Design Patterns in 100 Seconds - Fireship', url: 'https://www.youtube.com/watch?v=tv-_1er1mWI', type: 'video' },
            { title: 'Refactoring Guru - Creational Patterns', url: 'https://refactoring.guru/design-patterns/creational-patterns', type: 'article' },
            { title: 'Head First Design Patterns (Book Summary)', url: 'https://www.youtube.com/watch?v=v9ejT8FO-7I', type: 'video' },
            { title: 'Design Patterns - SourceMaking', url: 'https://sourcemaking.com/design_patterns', type: 'article' },
          ],
          project: {
            title: 'Document Generator',
            description: 'Build a document system: Factory creates PDF/HTML/Markdown docs. Builder constructs complex documents with headers, body, and footers. Prototype for templates.',
          },
        },
        {
          id: 'design-patterns-structural',
          title: 'Structural & Behavioral Patterns',
          description: 'Learn patterns for composing objects (Adapter, Decorator, Facade) and managing behavior (Observer, Strategy, Command).',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Adapter: make incompatible interfaces work together',
            'Decorator: add behavior without subclassing',
            'Facade: simplify complex subsystems',
            'Composite: tree structures with uniform interface',
            'Observer: event-driven decoupling',
            'Strategy: interchangeable algorithms',
            'Command: encapsulate requests as objects',
            'State: behavior changes with internal state',
            'Template Method: skeleton with customizable steps',
          ],
          resources: [
            { title: 'Refactoring Guru - All Patterns', url: 'https://refactoring.guru/design-patterns', type: 'article' },
            { title: 'Observer Pattern - Christopher Okhravi', url: 'https://www.youtube.com/watch?v=_BpmfnqjgzQ', type: 'video' },
            { title: 'Strategy Pattern - Derek Banas', url: 'https://www.youtube.com/watch?v=v9ejT8FO-7I', type: 'video' },
            { title: 'Patterns.dev - Modern Patterns', url: 'https://www.patterns.dev/', type: 'course' },
          ],
          project: {
            title: 'Event-Driven Todo App',
            description: 'Build a todo app using Observer (UI updates on data change), Strategy (sort algorithms), Command (undo/redo), and Decorator (priority, deadline decorators on tasks).',
          },
        },
        {
          id: 'composition-vs-inheritance',
          title: 'Composition Over Inheritance',
          description: 'Understand why modern OOP favors composition and delegation over deep inheritance trees.',
          timeEstimate: '2-3 days',
          whatToLearn: [
            'Problems with deep inheritance: fragile base class, tight coupling',
            'Composition: has-a vs is-a relationships',
            'Delegation pattern',
            'Mixins and traits as middle ground',
            'Entity-Component-System (ECS) architecture',
            'Dependency injection as composition',
            'When inheritance IS the right choice',
            'Real-world examples: React (composition), Game engines (ECS)',
          ],
          resources: [
            { title: 'Composition Over Inheritance - Fun Fun Function', url: 'https://www.youtube.com/watch?v=wfMtDGfHWpA', type: 'video' },
            { title: 'Favor Composition - Effective Java', url: 'https://www.baeldung.com/java-inheritance-composition', type: 'article' },
            { title: 'Entity Component System Explained', url: 'https://www.youtube.com/watch?v=2rW7ALyHaas', type: 'video' },
          ],
          project: {
            title: 'Game Character System',
            description: 'Build characters using composition: separate Movement, Attack, Health components. Characters assemble behaviors dynamically. Compare with a traditional inheritance approach.',
          },
        },
      ],
    },
  ],
};
