import { Roadmap } from '@/types/roadmap';

export const placementPreparationRoadmap: Roadmap = {
  slug: 'placement-preparation',
  title: 'Placement Preparation',
  description: 'Complete guide to crack campus placements — DSA, CS fundamentals, aptitude, system design, and interview skills.',
  icon: 'Map',
  accent: '#FFB36B',
  totalTime: '4-5 months',
  stages: [
    {
      id: 'programming-fundamentals',
      title: 'Programming Fundamentals',
      description: 'Pick a language and master its fundamentals.',
      timeEstimate: '2-3 weeks',
      color: 'green',
      topics: [
        {
          id: 'language-mastery',
          title: 'Language Mastery (C++/Java/Python)',
          description: 'Deep understanding of your primary coding language.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Syntax, data types, operators',
            'Control flow and loops',
            'Functions and recursion',
            'OOP (classes, inheritance, polymorphism, abstraction)',
            'STL/Collections framework',
            'Input/output handling',
            'Memory management basics',
          ],
          resources: [
            { title: 'C++ STL Guide - GeeksforGeeks', url: 'https://www.geeksforgeeks.org/the-c-standard-template-library-stl/', type: 'article' },
            { title: 'Java Collections - Kunal Kushwaha', url: 'https://www.youtube.com/watch?v=rI4kdGLaUiQ', type: 'video' },
            { title: 'Python for DSA - freeCodeCamp', url: 'https://www.youtube.com/watch?v=pkYVOmU3MgA', type: 'video' },
          ],
          project: {
            title: 'Library Management System',
            description: 'Build a console-based library system with OOP concepts — classes for Book, Member, Transaction with file I/O for persistence.',
          },
        },
        {
          id: 'time-space-complexity',
          title: 'Time & Space Complexity',
          description: 'Analyze algorithm efficiency like an expert.',
          timeEstimate: '4-5 days',
          whatToLearn: [
            'Big O, Big Theta, Big Omega notation',
            'Analyzing loops (single, nested, logarithmic)',
            'Space complexity (auxiliary vs total)',
            'Best, worst, average case analysis',
            'Amortized analysis (basics)',
            'Comparing algorithm complexities',
          ],
          resources: [
            { title: 'Big O Cheat Sheet', url: 'https://www.bigocheatsheet.com/', type: 'article' },
            { title: 'Time Complexity - Abdul Bari', url: 'https://www.youtube.com/watch?v=9TlHvipP5yA', type: 'video' },
            { title: 'Analysis of Algorithms - GFG', url: 'https://www.geeksforgeeks.org/fundamentals-of-algorithms/', type: 'article' },
          ],
          project: {
            title: 'Complexity Analyzer',
            description: 'Implement 10 common algorithms, measure their actual runtime for increasing input sizes, and plot the growth curves.',
          },
        },
      ],
    },
    {
      id: 'data-structures',
      title: 'Data Structures',
      description: 'Master all essential data structures with implementations.',
      timeEstimate: '5-6 weeks',
      color: 'lime',
      topics: [
        {
          id: 'arrays-strings',
          title: 'Arrays & Strings',
          description: 'Foundation patterns for linear data.',
          timeEstimate: '8-10 days',
          whatToLearn: [
            'Two-pointer technique',
            'Sliding window problems',
            'Prefix sum and difference arrays',
            'Matrix traversal patterns',
            'String manipulation and pattern matching',
            'Kadane\'s algorithm (max subarray)',
            'Dutch National Flag (3-way partition)',
          ],
          resources: [
            { title: 'NeetCode Arrays Playlist', url: 'https://www.youtube.com/playlist?list=PLot-Xpze53ldVwtstag2TL4HQhAnC8ATf', type: 'video' },
            { title: 'Striver A2Z Array Sheet', url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/', type: 'article' },
            { title: 'LeetCode Array Problems', url: 'https://leetcode.com/tag/array/', type: 'course' },
          ],
          project: {
            title: 'Solve 50 Array Problems',
            description: 'Solve 50 array/string problems on LeetCode (20 easy, 20 medium, 10 hard). Track patterns and time yourself.',
          },
        },
        {
          id: 'linked-lists-stacks-queues',
          title: 'Linked Lists, Stacks & Queues',
          description: 'Linear data structures with pointer manipulation.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Singly and doubly linked lists',
            'Fast and slow pointer technique',
            'Stack operations and applications',
            'Queue and circular queue',
            'Monotonic stack/queue patterns',
            'LRU Cache implementation',
            'Expression evaluation',
          ],
          resources: [
            { title: 'Linked List - Striver', url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0rAuz8tVcM0AymmhTRsfaLU', type: 'video' },
            { title: 'Stack Problems - NeetCode', url: 'https://neetcode.io/practice', type: 'course' },
            { title: 'Visualgo Visualizations', url: 'https://visualgo.net/en', type: 'docs' },
          ],
          project: {
            title: 'Browser History (Doubly LL)',
            description: 'Implement a browser history system using doubly linked list — back, forward, new page visit, with stack-based undo.',
          },
        },
        {
          id: 'trees-graphs',
          title: 'Trees & Graphs',
          description: 'Hierarchical and network data structures.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Binary tree traversals (inorder, preorder, postorder, level-order)',
            'BST operations (insert, delete, search)',
            'Tree problems (height, diameter, LCA, views)',
            'Graph representations (adjacency list/matrix)',
            'BFS and DFS traversals',
            'Shortest path (Dijkstra, BFS unweighted)',
            'Topological sort and cycle detection',
          ],
          resources: [
            { title: 'Trees - Striver (A2Z)', url: 'https://takeuforward.org/data-structure/binary-tree-traversals-in-binary-tree/', type: 'article' },
            { title: 'Graph Series - William Fiset', url: 'https://www.youtube.com/playlist?list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93B', type: 'video' },
            { title: 'NeetCode Graph Problems', url: 'https://neetcode.io/roadmap', type: 'course' },
          ],
          project: {
            title: 'Social Network Analyzer',
            description: 'Model a social network as a graph. Implement friend suggestions (BFS), mutual friends, shortest connection path, and community detection.',
          },
        },
        {
          id: 'hashing-heaps',
          title: 'Hashing & Heaps',
          description: 'Fast lookups and priority-based processing.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Hash maps and hash sets',
            'Collision handling (chaining, open addressing)',
            'Frequency counting patterns',
            'Min-heap and max-heap',
            'Priority queue applications',
            'Top-K problems',
            'Heap sort',
          ],
          resources: [
            { title: 'Hashing - GFG', url: 'https://www.geeksforgeeks.org/hashing-data-structure/', type: 'article' },
            { title: 'Heaps - Abdul Bari', url: 'https://www.youtube.com/watch?v=HqPJF2L5h9U', type: 'video' },
            { title: 'Priority Queue Problems - LeetCode', url: 'https://leetcode.com/tag/heap-priority-queue/', type: 'course' },
          ],
          project: {
            title: 'Real-time Leaderboard',
            description: 'Build a leaderboard system using heaps — add scores, get top-K players, update scores, and remove players efficiently.',
          },
        },
      ],
    },
    {
      id: 'algorithms',
      title: 'Algorithms',
      description: 'Core algorithmic techniques asked in interviews.',
      timeEstimate: '4-5 weeks',
      color: 'yellow',
      topics: [
        {
          id: 'sorting-searching',
          title: 'Sorting & Searching',
          description: 'Fundamental algorithms and binary search mastery.',
          timeEstimate: '6-7 days',
          whatToLearn: [
            'Merge sort and quick sort (implementations)',
            'Binary search on sorted arrays',
            'Binary search on answer space',
            'Search in rotated sorted array',
            'Finding peak elements',
            'Median of two sorted arrays',
          ],
          resources: [
            { title: 'Binary Search - Striver', url: 'https://takeuforward.org/data-structure/binary-search-explained/', type: 'article' },
            { title: 'Sorting Algorithms Visualized', url: 'https://www.youtube.com/watch?v=kPRA0W1kECg', type: 'video' },
            { title: 'Binary Search Problems - LeetCode', url: 'https://leetcode.com/tag/binary-search/', type: 'course' },
          ],
          project: {
            title: 'Custom Sort Visualizer',
            description: 'Build a visual sorting tool that animates merge sort, quick sort, and heap sort step-by-step with speed controls.',
          },
        },
        {
          id: 'dynamic-programming',
          title: 'Dynamic Programming',
          description: 'The most feared interview topic — demystified.',
          timeEstimate: '10-12 days',
          whatToLearn: [
            'Memoization (top-down) vs tabulation (bottom-up)',
            '1D DP (climbing stairs, house robber, coin change)',
            '2D DP (grid paths, LCS, edit distance)',
            'Subsequence problems (LIS, knapsack variants)',
            'Partition DP (MCM, palindrome partitioning)',
            'DP on strings',
            'State optimization techniques',
          ],
          resources: [
            { title: 'DP Series - Striver (50 problems)', url: 'https://takeuforward.org/dynamic-programming/striver-dp-series/', type: 'video' },
            { title: 'NeetCode DP Playlist', url: 'https://www.youtube.com/playlist?list=PLot-Xpze53lcvx_tjrr_m2lgD2NsRHlNO', type: 'video' },
            { title: 'Aditya Verma DP Playlist', url: 'https://www.youtube.com/playlist?list=PL_z_8CaSLPWekqhdCPmFohncHwz8TY2Go', type: 'video' },
          ],
          project: {
            title: 'Solve 40 DP Problems',
            description: 'Solve 40 DP problems following Striver\'s sheet. For each, write the recursive, memoized, and tabulated solutions.',
          },
        },
        {
          id: 'greedy-backtracking',
          title: 'Greedy & Backtracking',
          description: 'Optimization and exhaustive search strategies.',
          timeEstimate: '6-7 days',
          whatToLearn: [
            'Greedy algorithm design (activity selection, fractional knapsack)',
            'Interval scheduling and merging',
            'Huffman coding',
            'Backtracking framework',
            'N-Queens, Sudoku solver',
            'Subset/permutation generation',
            'Word search and path finding',
          ],
          resources: [
            { title: 'Greedy - Striver', url: 'https://takeuforward.org/data-structure/greedy-algorithms/', type: 'article' },
            { title: 'Backtracking - NeetCode', url: 'https://www.youtube.com/playlist?list=PLot-Xpze53lf5C3HSjCnyFghlW0G1HHXo', type: 'video' },
            { title: 'Recursion & Backtracking - Aditya Verma', url: 'https://www.youtube.com/playlist?list=PL_z_8CaSLPWeT1ffjiImo0sYTcnLzo-wY', type: 'video' },
          ],
          project: {
            title: 'Sudoku Solver with Visualization',
            description: 'Build a sudoku solver using backtracking with step-by-step visual animation showing the algorithm\'s decision process.',
          },
        },
      ],
    },
    {
      id: 'cs-fundamentals',
      title: 'CS Fundamentals',
      description: 'Core subjects asked in technical interviews.',
      timeEstimate: '3-4 weeks',
      color: 'orange',
      topics: [
        {
          id: 'os',
          title: 'Operating Systems',
          description: 'Process, memory, and storage management.',
          timeEstimate: '6-7 days',
          whatToLearn: [
            'Process vs thread, context switching',
            'CPU scheduling algorithms (FCFS, SJF, RR, Priority)',
            'Synchronization (mutex, semaphore, deadlock)',
            'Memory management (paging, segmentation, virtual memory)',
            'Page replacement algorithms (LRU, FIFO, Optimal)',
            'File systems and disk scheduling',
          ],
          resources: [
            { title: 'OS by Gate Smashers', url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p', type: 'video' },
            { title: 'OS Notes - GFG', url: 'https://www.geeksforgeeks.org/operating-systems/', type: 'article' },
            { title: 'InterviewBit OS Questions', url: 'https://www.interviewbit.com/operating-system-interview-questions/', type: 'article' },
          ],
          project: {
            title: 'OS Concepts Simulator',
            description: 'Simulate CPU scheduling (compare algorithms), page replacement (visualize hits/misses), and deadlock detection.',
          },
        },
        {
          id: 'dbms',
          title: 'Database Management',
          description: 'SQL, normalization, and database design.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'ER diagrams and relational model',
            'SQL queries (joins, subqueries, aggregation)',
            'Normalization (1NF to BCNF)',
            'Indexing and B+ trees',
            'Transactions (ACID properties)',
            'Concurrency control and isolation levels',
          ],
          resources: [
            { title: 'DBMS - Gate Smashers', url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y', type: 'video' },
            { title: 'SQL Practice - HackerRank', url: 'https://www.hackerrank.com/domains/sql', type: 'course' },
            { title: 'DBMS Notes - GFG', url: 'https://www.geeksforgeeks.org/dbms/', type: 'article' },
          ],
          project: {
            title: 'Design a Database Schema',
            description: 'Design a normalized schema for an e-commerce platform (users, products, orders, reviews) and write 20 complex SQL queries.',
          },
        },
        {
          id: 'cn',
          title: 'Computer Networks',
          description: 'How the internet works under the hood.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'OSI and TCP/IP model layers',
            'TCP vs UDP, 3-way handshake',
            'HTTP/HTTPS, DNS resolution',
            'IP addressing and subnetting',
            'Routing algorithms',
            'Network security basics (SSL/TLS, firewalls)',
          ],
          resources: [
            { title: 'CN - Gate Smashers', url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_', type: 'video' },
            { title: 'Computer Networking Top-Down (free chapters)', url: 'https://gaia.cs.umass.edu/kurose_ross/online_lectures.htm', type: 'course' },
            { title: 'CN Interview Questions - GFG', url: 'https://www.geeksforgeeks.org/commonly-asked-computer-networks-interview-questions-set-1/', type: 'article' },
          ],
          project: {
            title: 'Network Protocol Analyzer',
            description: 'Document the lifecycle of a web request (DNS → TCP → TLS → HTTP → Response) with diagrams and implement a simple HTTP server.',
          },
        },
      ],
    },
    {
      id: 'interview-prep',
      title: 'Interview & Soft Skills',
      description: 'Crack the actual interview with these final preparations.',
      timeEstimate: '3-4 weeks',
      color: 'purple',
      topics: [
        {
          id: 'system-design-basics',
          title: 'System Design (Basics)',
          description: 'High-level design thinking for freshers.',
          timeEstimate: '7-8 days',
          whatToLearn: [
            'Scalability concepts (horizontal vs vertical)',
            'Load balancing and caching',
            'Database sharding and replication',
            'Message queues and async processing',
            'Design URL shortener, chat app (basic level)',
            'API design best practices',
          ],
          resources: [
            { title: 'System Design Primer (GitHub)', url: 'https://github.com/donnemartin/system-design-primer', type: 'article' },
            { title: 'System Design - Gaurav Sen', url: 'https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX', type: 'video' },
            { title: 'High Level Design - Concept && Coding', url: 'https://www.youtube.com/playlist?list=PL6W8uoQQ2c61X_9e6Net0WdYZidm7zooW', type: 'video' },
          ],
          project: {
            title: 'Design 5 Systems',
            description: 'Write high-level design docs for: URL Shortener, Chat App, Twitter Feed, File Storage, and Notification System.',
          },
        },
        {
          id: 'aptitude',
          title: 'Aptitude & Reasoning',
          description: 'Clear online assessment rounds.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'Quantitative aptitude (percentages, ratios, probability)',
            'Logical reasoning (puzzles, seating arrangements)',
            'Verbal ability (reading comprehension, grammar)',
            'Data interpretation (charts, tables)',
            'Pattern recognition',
            'Time management for MCQ tests',
          ],
          resources: [
            { title: 'IndiaBix Aptitude', url: 'https://www.indiabix.com/', type: 'course' },
            { title: 'Aptitude - Placement Preparation - GFG', url: 'https://www.geeksforgeeks.org/aptitude-gq/', type: 'article' },
            { title: 'RS Aggarwal Quant (YouTube)', url: 'https://www.youtube.com/results?search_query=rs+aggarwal+aptitude', type: 'video' },
          ],
          project: {
            title: 'Daily Practice Routine',
            description: 'Solve 20 aptitude questions daily for 2 weeks. Track accuracy per topic and focus on weak areas.',
          },
        },
        {
          id: 'interview-skills',
          title: 'Interview Skills',
          description: 'HR rounds, behavioral questions, and presentation.',
          timeEstimate: '5-6 days',
          whatToLearn: [
            'STAR method for behavioral answers',
            'Self-introduction (30s, 1min, 2min versions)',
            'Common HR questions and answers',
            'Explaining projects clearly',
            'Salary negotiation basics',
            'Body language and communication',
            'Mock interview practice',
          ],
          resources: [
            { title: 'HR Interview Questions - GFG', url: 'https://www.geeksforgeeks.org/hr-interview-questions/', type: 'article' },
            { title: 'Mock Interview Tips', url: 'https://www.youtube.com/watch?v=1qw5ITr3k9E', type: 'video' },
            { title: 'Pramp (Free Mock Interviews)', url: 'https://www.pramp.com/', type: 'course' },
          ],
          project: {
            title: '10 Mock Interviews',
            description: 'Do 10 mock interviews with peers or on Pramp. Record yourself, review, and improve each time.',
          },
        },
      ],
    },
  ],
};
