'use client';

import { useState, useMemo, useCallback } from 'react';
import { Copy, Download, Check, Sparkles } from 'lucide-react';

/* ─── Technology Presets ─── */

interface TechPreset {
  id: string;
  label: string;
  group: 'languages' | 'os' | 'editors';
  patterns: string[];
}

const PRESETS: TechPreset[] = [
  {
    id: 'nodejs',
    label: 'Node.js',
    group: 'languages',
    patterns: [
      'node_modules/',
      'dist/',
      '.env',
      '.env.local',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      '.pnpm-debug.log*',
    ],
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    group: 'languages',
    patterns: ['.next/', 'out/', '.vercel'],
  },
  {
    id: 'react-vite',
    label: 'React / Vite',
    group: 'languages',
    patterns: ['dist/', '.env.local'],
  },
  {
    id: 'python',
    label: 'Python',
    group: 'languages',
    patterns: [
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '*.so',
      '.Python',
      'env/',
      'venv/',
      '.venv/',
      '*.egg-info/',
      'dist/',
      'build/',
      '.eggs/',
    ],
  },
  {
    id: 'java',
    label: 'Java',
    group: 'languages',
    patterns: ['*.class', '*.jar', '*.war', '*.ear', 'target/', '.gradle/', 'build/'],
  },
  {
    id: 'flutter',
    label: 'Flutter / Dart',
    group: 'languages',
    patterns: [
      '.dart_tool/',
      '.flutter-plugins',
      '.flutter-plugins-dependencies',
      '.packages',
      'build/',
      '*.iml',
    ],
  },
  {
    id: 'android',
    label: 'Android',
    group: 'languages',
    patterns: ['*.apk', '*.ap_', '*.dex', 'local.properties', '.gradle/', 'build/', 'captures/'],
  },
  {
    id: 'go',
    label: 'Go',
    group: 'languages',
    patterns: ['bin/', 'pkg/', '*.exe', '*.test', '*.out'],
  },
  {
    id: 'rust',
    label: 'Rust',
    group: 'languages',
    patterns: ['target/', 'Cargo.lock'],
  },
  {
    id: 'macos',
    label: 'macOS',
    group: 'os',
    patterns: ['.DS_Store', '.AppleDouble', '.LSOverride', '._*', '.Spotlight-V100', '.Trashes'],
  },
  {
    id: 'windows',
    label: 'Windows',
    group: 'os',
    patterns: ['Thumbs.db', 'ehthumbs.db', 'Desktop.ini', '$RECYCLE.BIN/'],
  },
  {
    id: 'linux',
    label: 'Linux',
    group: 'os',
    patterns: ['*~', '.nfs*'],
  },
  {
    id: 'vscode',
    label: 'VS Code',
    group: 'editors',
    patterns: ['.vscode/', '*.code-workspace'],
  },
  {
    id: 'jetbrains',
    label: 'JetBrains',
    group: 'editors',
    patterns: ['.idea/', '*.iml', '*.iws', 'out/'],
  },
  {
    id: 'vim',
    label: 'Vim',
    group: 'editors',
    patterns: ['*.swp', '*.swo', '*~', 'tags'],
  },
];

const COMMON_SELECTION = ['nodejs', 'macos', 'vscode'];

const GROUP_LABELS: Record<TechPreset['group'], string> = {
  languages: 'Languages & Frameworks',
  os: 'Operating Systems',
  editors: 'Editors / IDEs',
};

/* ─── Component ─── */

export function GitignoreGeneratorForm() {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [copied, setCopied] = useState(false);

  const toggle = useCallback((id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  const selectCommon = useCallback(() => {
    setSelected(new Set(COMMON_SELECTION));
  }, []);

  const generatedContent = useMemo(() => {
    if (selected.size === 0) return '';

    const sections: string[] = [];
    const seenPatterns = new Set<string>();

    for (const preset of PRESETS) {
      if (!selected.has(preset.id)) continue;

      const uniquePatterns = preset.patterns.filter((p) => !seenPatterns.has(p));
      if (uniquePatterns.length === 0) continue;

      uniquePatterns.forEach((p) => seenPatterns.add(p));
      sections.push(`# ${preset.label}\n${uniquePatterns.join('\n')}`);
    }

    return `# Generated by StudentKit .gitignore Generator\n# https://studentkit.in/tools/gitignore-generator\n\n${sections.join('\n\n')}\n`;
  }, [selected]);

  const handleCopy = useCallback(async () => {
    if (!generatedContent) return;
    try {
      await navigator.clipboard.writeText(generatedContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = generatedContent;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [generatedContent]);

  const handleDownload = useCallback(() => {
    if (!generatedContent) return;
    const blob = new Blob([generatedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.gitignore';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedContent]);

  const groups = useMemo(() => {
    const map: Record<TechPreset['group'], TechPreset[]> = {
      languages: [],
      os: [],
      editors: [],
    };
    for (const preset of PRESETS) {
      map[preset.group].push(preset);
    }
    return map;
  }, []);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Selection Panel */}
      <div className="p-6 md:p-8 border border-[var(--border-soft)] rounded-2xl bg-[var(--bg-surface)]">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-[var(--text-secondary)]">
              Selected:
            </span>
            <span className="inline-flex items-center justify-center min-w-[1.5rem] h-6 px-1.5 rounded-full bg-[var(--accent-primary)]/10 text-xs font-semibold text-[var(--accent-primary)]">
              {selected.size}
            </span>
          </div>
          <button
            type="button"
            onClick={selectCommon}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[var(--accent-primary)] border border-[var(--accent-primary)]/30 rounded-lg hover:bg-[var(--accent-primary)]/5 transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5" />
            Select Common
          </button>
        </div>

        {(Object.keys(groups) as TechPreset['group'][]).map((group) => (
          <div key={group} className="mb-5 last:mb-0">
            <h3 className="text-xs font-medium uppercase tracking-wider text-[var(--text-subtle)] mb-2.5">
              {GROUP_LABELS[group]}
            </h3>
            <div className="flex flex-wrap gap-2">
              {groups[group].map((preset) => {
                const isSelected = selected.has(preset.id);
                return (
                  <button
                    key={preset.id}
                    type="button"
                    onClick={() => toggle(preset.id)}
                    className={`px-3 py-1.5 text-sm font-medium rounded-lg border transition-all ${
                      isSelected
                        ? 'bg-[var(--accent-primary)] text-white border-[var(--accent-primary)] shadow-sm'
                        : 'bg-[var(--bg-subtle)] text-[var(--text-secondary)] border-[var(--border-soft)] hover:border-[var(--border-default)] hover:text-[var(--text-primary)]'
                    }`}
                  >
                    {preset.label}
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Output Panel */}
      <div className="p-6 md:p-8 border border-[var(--border-soft)] rounded-2xl bg-[var(--bg-surface)] flex flex-col">
        {selected.size === 0 ? (
          <div className="flex items-center justify-center h-full min-h-[240px]">
            <p className="text-sm text-[var(--text-subtle)] text-center">
              Select technologies from the left to generate your .gitignore file
            </p>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-medium uppercase tracking-wider text-[var(--text-subtle)]">
                .gitignore
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[var(--text-secondary)] border border-[var(--border-soft)] rounded-lg hover:border-[var(--border-default)] hover:text-[var(--text-primary)] transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-green-500" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      Copy
                    </>
                  )}
                </button>
                <button
                  type="button"
                  onClick={handleDownload}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[var(--text-secondary)] border border-[var(--border-soft)] rounded-lg hover:border-[var(--border-default)] hover:text-[var(--text-primary)] transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-auto rounded-xl bg-[#1e1e2e] p-4 border border-[var(--border-soft)]">
              <pre className="text-sm font-mono text-[#cdd6f4] leading-relaxed whitespace-pre-wrap break-words">
                {generatedContent}
              </pre>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
